<td class="insert_table center print_ignore">
    <a href="tbl_change.php<?php echo $tbl_url_query; ?>"><?php echo $titles['Insert']; ?></a>
</td>
<td class="center print_ignore"><?php echo $empty_table; ?></td>
<td class="center print_ignore">
    <a class="ajax drop_table_anchor 
    <?php if ($table_is_view || $current_table['ENGINE'] == null): ?>
        <?php echo ' view'; ?>
    <?php endif; ?>" href="sql.php<?php echo $tbl_url_query; ?>&amp;reload=1&amp;purge=1&amp;sql_query=<?php echo urlencode($drop_query); ?>&amp;message_to_show=<?php echo urlencode($drop_message); ?>" >
    <?php echo $titles['Drop']; ?>
    </a>
</td>