#!/bin/sh

if [ -z "$TRAVIS_COMMIT_RANGE" ] ; then
    find . -name '*.php' -not -path './vendor/*' | xargs -n1 -r php -l
else
    git diff --name-only $TRAVIS_COMMIT_RANGE -- '*.php' | xargs -n1 -r php -l
fi
