#!/bin/sh

if [ $TRAVIS_PHP_VERSION = "5.6" ] ; then
    git clone --depth=1 git://github.com/adrianguenter/runkit.git
else:
    git clone --depth=1 git://github.com/zenovich/runkit.git
fi
cd runkit
phpize
./configure
make
make install
cd ..

phpenv config-add test/travis.php.ini
