<?php
/**
 * @package PhpMyAdmin-test
 * This file has been generated by phpmyadmin/scripts:/develdocs/build.sh
 * @see https://github.com/phpmyadmin/scripts/blob/master/develdocs/sami.php
 * @see https://github.com/phpmyadmin/scripts/blob/master/develdocs/build.sh
 */
use Sami\Sami;
use Symfony\Component\Finder\Finder;

$iterator = Finder::create()
    ->files()
    ->name("*.php")
    ->in("./libraries")
;

return new Sami($iterator, [
    "title"                => "MySQL web administration tool",
    "build_dir"            => "./build/apidocs/",
    "cache_dir"            => "./tmp"
]);
