<tbody id="tbl_summary_row">
<tr>
<th class="print_ignore"></th>
<th class="tbl_num nowrap">
    <?php
    printf(_ngettext('%s table', '%s tables', $num_tables),
        PMA\libraries\Util::formatNumber($num_tables, 0)); ?>
</th>
<?php if ($server_slave_status): ?>
    <th> <?= __('Replication'); ?> </th>
<?php endif; ?>
<?php
$sum_colspan = ($db_is_system_schema ? 4 : 7);
if ($GLOBALS['cfg']['NumFavoriteTables'] == 0) {
    $sum_colspan--;
} ?>
<th colspan="<?= $sum_colspan; ?>" class="print_ignore" ><?= __('Sum'); ?></th>
<?php
$row_count_sum = PMA\libraries\Util::formatNumber($sum_entries, 0);
// If a table shows approximate rows count, display update-all-real-count anchor.
$row_sum_url = array();
if (isset($approx_rows)) {
    $row_sum_url = array(
        'ajax_request'       => true,
        'db'                 => $GLOBALS['db'],
        'real_row_count'     => 'true',
        'real_row_count_all' => 'true'
    );
}
$cell_text = ($approx_rows)
        ? '<a href="db_structure.php' . PMA\libraries\URL::getCommon($row_sum_url)
        . '" class="ajax row_count_sum">' . '~' . $row_count_sum . '</a>'
        : $row_count_sum;
?>
<th class="value tbl_rows"><?= $cell_text; ?></th>
<?php if (!($GLOBALS['cfg']['PropertiesNumColumns'] > 1)): ?>
    <?php
        // MySQL <= 5.5.2
        $default_engine = $GLOBALS['dbi']->fetchValue(
            "SELECT @@storage_engine;"
        );
        if (empty($default_engine)) {
            // MySQL >= 5.5.3
            $default_engine = $GLOBALS['dbi']->fetchValue(
                "SELECT @@default_storage_engine;"
            );
        }
    ?>
    <th class="center">
        <dfn title="<?php printf(__('%s is the default storage engine on this MySQL server.'),
                $default_engine); ?>"><?= $default_engine; ?></dfn>
    </th>
    <th>
        <?php if (! empty($db_collation)): ?>
            <dfn title="<?= PMA\libraries\Charsets::getCollationDescr($db_collation) , ' (' , __('Default') , ')'; ?>">
                <?= $db_collation; ?>
            </dfn>
        <?php endif; ?>
    </th>
<?php endif; ?>

<?php if ($is_show_stats): ?>
    <?php
        list($sum_formatted, $unit) = PMA\libraries\Util::formatByteDown(
            $sum_size, 3, 1
        );
        list($overhead_formatted, $overhead_unit)
            = PMA\libraries\Util::formatByteDown($overhead_size, 3, 1);
    ?>
    <th class="value tbl_size"><?= $sum_formatted , ' ' , $unit; ?></th>
    <th class="value tbl_overhead"><?= $overhead_formatted , ' ' , $overhead_unit; ?></th>
<?php endif; ?>

<?php if ($GLOBALS['cfg']['ShowDbStructureCharset']): ?>
    <th>
        <?= $db_charset; ?>
    </th>
<?php endif; ?>
<?php if ($GLOBALS['cfg']['ShowDbStructureComment']): ?>
    <th></th>
<?php endif; ?>
<?php if ($GLOBALS['cfg']['ShowDbStructureCreation']): ?>
    <th class="value tbl_creation">
        <?= ($create_time_all
                ? PMA\libraries\Util::localisedDate(strtotime($create_time_all))
                : '-'); ?>
    </th>
<?php endif; ?>
<?php if ($GLOBALS['cfg']['ShowDbStructureLastUpdate']): ?>
    <th class="value tbl_last_update"><?= ($update_time_all
                ? PMA\libraries\Util::localisedDate(strtotime($update_time_all))
                : '-'); ?></th>
<?php endif; ?>
<?php if ($GLOBALS['cfg']['ShowDbStructureLastCheck']): ?>
    <th class="value tbl_last_check"><?= ($check_time_all
                ? PMA\libraries\Util::localisedDate(strtotime($check_time_all))
                : '-');?></th>
<?php endif; ?>
</tr>
</tbody>
