<div class="clearfloat print_ignore">
    <img class="selectallarrow" src="<?= $pmaThemeImage , 'arrow_' , $text_dir , '.png'; ?>" width="38" height="22" alt="<?php __('With selected:'); ?>" />
    <input type="checkbox" id="tablesForm_checkall" class="checkall_box" title="<?= __('Check all'); ?>" />
    <label for="tablesForm_checkall"><?= __('Check all'); ?></label>
    <?php if ($overhead_check != ''): ?>
         / <a href="#" onclick="unMarkAllRows('tablesForm'); <?= $overhead_check; ?> return false;"><?= __('Check tables having overhead'); ?></a>
    <?php endif; ?>
    <select name="submit_mult" style="margin: 0 3em 0 3em;">
        <option value="<?= __('With selected:'); ?>" selected="selected"><?= __('With selected:'); ?></option>
        <option value="copy_tbl"><?= __('Copy table')?></option>
        <option value="show_create" ><?= __('Show create'); ?></option>
        <option value="export" ><?= __('Export'); ?></option>
        <?php if (!$db_is_system_schema
                    && !$GLOBALS['cfg']['DisableMultiTableMaintenance']): ?>
            <optgroup label="<?= __('Delete data or table'); ?>">
                <option value="empty_tbl" ><?= __('Empty'); ?></option>
                <option value="drop_tbl" ><?= __('Drop'); ?></option>
            </optgroup>
            <optgroup label="<?= __('Table maintenance'); ?>">
                <option value="analyze_tbl" ><?= __('Analyze table'); ?></option>
                <option value="check_tbl" ><?= __('Check table'); ?></option>
                <option value="checksum_tbl" ><?= __('Checksum table'); ?></option>
                <option value="optimize_tbl" ><?= __('Optimize table'); ?></option>
                <option value="repair_tbl" ><?= __('Repair table'); ?></option>
            </optgroup>
            <optgroup label="<?= __('Prefix'); ?>">
                <option value="add_prefix_tbl" ><?= __('Add prefix to table'); ?></option>
                <option value="replace_prefix_tbl" ><?= __('Replace table prefix'); ?></option>
                <option value="copy_tbl_change_prefix" ><?= __('Copy table with prefix'); ?></option>
            </optgroup>
        <?php endif; ?>
        <?php if (isset($GLOBALS['cfgRelation']['centralcolumnswork'])
                    && $GLOBALS['cfgRelation']['centralcolumnswork']): ?>
            <optgroup label="<?= __('Central columns'); ?>">
                <option value="sync_unique_columns_central_list" ><?= __('Add columns to central list'); ?></option>
                <option value="delete_unique_columns_central_list" ><?= __('Remove columns from central list'); ?></option>
                <option value="make_consistent_with_central_list" ><?= __('Make consistent with central list'); ?></option>
            </optgroup>
        <?php endif; ?>
    </select>
    <?= implode("\n", $hidden_fields); ?>
</div>