<fieldset>
    <legend><?= $title; ?></legend>
    <table class="show_create">
        <thead>
        <tr>
            <th><?= $raw_title; ?></th>
            <th>Create <?= $raw_title; ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $odd = true; ?>
        <?php foreach ($db_objects as $object): ?>
            <?php $row_class = ($odd) ? 'odd' : 'even'; ?>
            <tr class="<?= $row_class; ?>">
                <td><strong><?= PMA_mimeDefaultFunction($object); ?></strong></td>
                <td><?= PMA_mimeDefaultFunction($GLOBALS['dbi']->getTable($db, $object)->showCreate()); ?></td>
            </tr>
            <?php $odd = ! $odd; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</fieldset>