<fieldset>
    <legend><?php echo $title; ?></legend>
    <table class="show_create">
        <thead>
        <tr>
            <th><?php echo $raw_title; ?></th>
            <th>Create <?php echo $raw_title; ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $odd = true; ?>
        <?php foreach ($db_objects as $object): ?>
            <?php $row_class = ($odd) ? 'odd' : 'even'; ?>
            <tr class="<?php echo $row_class; ?>">
                <td><strong><?php echo PMA_mimeDefaultFunction($object); ?></strong></td>
                <td><?php echo PMA_mimeDefaultFunction($GLOBALS['dbi']->getTable($db, $object)->showCreate()); ?></td>
            </tr>
            <?php $odd = ! $odd; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</fieldset>
