<div class="show_create_results">
    <h2><?php echo __('Showing create queries'); ?></h2>
    <?php
        $views = array();
        $tables = array();
        foreach ($db_objects as $object) {
            if ($GLOBALS['dbi']->getTable($db, $object)->isView()) {
                $views [] = $object;
            } else {
                $tables [] = $object;
            }
        }
    ?>
    <?php if (! empty($tables)): ?>
        <?php
            echo PMA\Template::get('database/structure/show_create_row')->render(
              array(
                  'title' => __('Tables'),
                  'raw_title' => 'Table',
                  'db_objects' => $tables
              )
            );
        ?>
    <?php endif; ?>

    <?php if (! empty($views)): ?>
        <?php
        echo PMA\Template::get('database/structure/show_create_row')->render(
            array(
                'title' => __('Views'),
                'raw_title' => 'View',
                'db_objects' => $views
            )
        );
        ?>
    <?php endif; ?>
</div>