<div class="show_create_results">
    <h2><?= __('Showing create queries'); ?></h2>
    <?php
        $views = array();
        $tables = array();
        foreach ($db_objects as $object) {
            if ($GLOBALS['dbi']->getTable($db, $object)->isView()) {
                $views [] = $object;
            } else {
                $tables [] = $object;
            }
        }
    ?>
    <?php if (! empty($tables)): ?>
        <?= PhpMyAdmin\Template::get('database/structure/show_create_row')->render(
            array(
              'db' => $db,
              'title' => __('Tables'),
              'raw_title' => 'Table',
              'db_objects' => $tables,
              'dbi' => $GLOBALS['dbi'],
            )
        ) ?>
    <?php endif; ?>

    <?php if (! empty($views)): ?>
        <?= PhpMyAdmin\Template::get('database/structure/show_create_row')->render(
            array(
                'db' => $db,
                'title' => __('Views'),
                'raw_title' => 'View',
                'db_objects' => $views,
                'dbi' => $GLOBALS['dbi'],
            )
        ) ?>
    <?php endif; ?>
</div>
