<tr <?= ($table_is_view ? ' class="is_view"' : '') ?>
    id="row_tbl_<?= $curr; ?>">
    <td class="center print_ignore">
        <input type="checkbox"
               name="selected_tbl[]"
               class="checkall"
               value="<?= htmlspecialchars($current_table['TABLE_NAME']); ?>"
               id="checkbox_tbl_<?= $curr; ?>" />
    </td>
    <th>
        <?= $browse_table_label , $tracking_icon; ?>
    </th>
    <?php if ($server_slave_status): ?>
        <td class="center">
            <?= ($ignored ? PMA\libraries\Util::getImage('s_cancel.png', __('Not replicated')) : ''); ?>
            <?= ($do ? PMA\libraries\Util::getImage('s_success.png', __('Replicated')) : ''); ?>
        </td>
    <?php endif; ?>

    <?php
    //Favorite table anchor.
    ?>
    <?php if ($GLOBALS['cfg']['NumFavoriteTables'] > 0): ?>
        <td class="center print_ignore">
            <?= PMA\libraries\Template::get('database/structure/favorite_anchor')->render(
                array(
                    'db' => $db,
                    'current_table' => $current_table,
                    'titles' => $titles,
                    'already_favorite' => $already_favorite
                )
            ); ?>
        </td>
    <?php endif; ?>

    <td class="center print_ignore">
        <?= $browse_table; ?>
    </td>
    <td class="center print_ignore">
        <a href="tbl_structure.php<?= $tbl_url_query; ?>">
            <?= $titles['Structure']; ?>
        </a>
    </td>
    <td class="center print_ignore">
        <?= $search_table; ?>
    </td>

    <?php if (!$db_is_system_schema): ?>
        <td class="insert_table center print_ignore">
            <a href="tbl_change.php<?= $tbl_url_query; ?>"><?= $titles['Insert']; ?></a>
        </td>
        <td class="center print_ignore"><?= $empty_table; ?></td>
        <td class="center print_ignore">
            <a class="ajax drop_table_anchor <?= ($table_is_view || $current_table['ENGINE'] == null) ? ' view' : '' ?>"
               href="sql.php" data-post="<?= $tbl_url_query; ?>&amp;reload=1&amp;purge=1&amp;sql_query=<?= urlencode($drop_query); ?>&amp;message_to_show=<?= urlencode($drop_message); ?>" >
                <?= $titles['Drop']; ?>
            </a>
        </td>
    <?php endif; ?>

    <?php if (isset($current_table['TABLE_ROWS']) &&
        ($current_table['ENGINE'] != null || $table_is_view)): ?>

        <?php
        // Get the row count.
        $row_count = PMA\libraries\Util::formatNumber($current_table['TABLE_ROWS'], 0);

        // Content to be appended into 'tbl_rows' cell.
        // If row count is approximate, display it as an anchor to get real count.
        ?>
        <td class="value tbl_rows"
            data-table="<?= htmlspecialchars($current_table['TABLE_NAME']); ?>">
            <?php if ($approx_rows): ?>
                <a href="db_structure.php<?= PMA\libraries\URL::getCommon(
                    array(
                        'ajax_request'   => true,
                        'db'             => $GLOBALS['db'],
                        'table'          => $current_table['TABLE_NAME'],
                        'real_row_count' => 'true'
                    )
                ); ?>" class="ajax real_row_count">
                    <bdi>
                        ~<?= $row_count; ?>
                    </bdi>
                </a>
            <?php else: ?>
                <?= $row_count; ?>
            <?php endif; ?>
            <?= $show_superscript; ?>
        </td>

        <?php if (!($GLOBALS['cfg']['PropertiesNumColumns'] > 1)): ?>
            <td class="nowrap">
                <?php if (!empty($current_table['ENGINE'])): ?>
                    <?= $current_table['ENGINE']; ?>
                <?php elseif ($table_is_view): ?>
                    <?= __('View'); ?>
                <?php endif; ?>
            </td>
            <?php if (strlen($collation) > 0): ?>
                <td class="nowrap">
                    <?= $collation; ?>
                </td>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($is_show_stats): ?>
            <td class="value tbl_size">
                <a href="tbl_structure.php<?= $tbl_url_query ?>#showusage">
                    <span><?= $formatted_size; ?></span>
                    <span class="unit"><?= $unit; ?></span>
                </a>
            </td>
            <td class="value tbl_overhead">
                <?= $overhead; ?>
            </td>
        <?php endif; ?>

        <?php if (!($GLOBALS['cfg']['ShowDbStructureCharset'] > 1)): ?>
            <?php if (strlen($charset)): ?>
                <td class="nowrap">
                    <?= $charset; ?>
                </td>
            <?php endif; ?>
        <?php endif; ?>

        <?php if ($GLOBALS['cfg']['ShowDbStructureComment']): ?>
            <?php $comment = $current_table['Comment']; ?>
            <td>
                <?php if (mb_strlen($comment) > $GLOBALS['cfg']['LimitChars']): ?>
                    <abbr title="<?= htmlspecialchars($comment); ?>">
                        <?= htmlspecialchars(
                            mb_substr(
                                $comment, 0, $GLOBALS['cfg']['LimitChars']
                            )
                        ); ?>
                        ...
                    </abbr>
                <?php else: ?>
                    <?= htmlspecialchars($comment); ?>
                <?php endif; ?>
            </td>
        <?php endif; ?>

        <?php if ($GLOBALS['cfg']['ShowDbStructureCreation']): ?>
            <td class="value tbl_creation">
                <?= $create_time ? PMA\libraries\Util::localisedDate(strtotime($create_time)) : '-'; ?>
            </td>
        <?php endif; ?>

        <?php if ($GLOBALS['cfg']['ShowDbStructureLastUpdate']): ?>
            <td class="value tbl_last_update">
                <?= $update_time ? PMA\libraries\Util::localisedDate(strtotime($update_time)) : '-'; ?>
            </td>
        <?php endif; ?>

        <?php if ($GLOBALS['cfg']['ShowDbStructureLastCheck']): ?>
            <td class="value tbl_last_check">
                <?= $check_time ? PMA\libraries\Util::localisedDate(strtotime($check_time)) : '-'; ?>
            </td>
        <?php endif; ?>

    <?php elseif ($table_is_view): ?>

        <td class="value tbl_rows">-</td>
        <td class="nowrap">
            <?= __('View'); ?>
        </td>
        <td class="nowrap">---</td>
        <?php if ($is_show_stats): ?>
            <td class="value tbl_size">-</td>
            <td class="value tbl_overhead">-</td>
        <?php endif; ?>
        <?php if ($GLOBALS['cfg']['ShowDbStructureCharset']): ?>
            <td></td>
        <?php endif; ?>
        <?php if ($GLOBALS['cfg']['ShowDbStructureComment']): ?>
            <td></td>
        <?php endif; ?>
        <?php if ($GLOBALS['cfg']['ShowDbStructureCreation']): ?>
            <td class="value tbl_creation">-</td>
        <?php endif; ?>
        <?php if ($GLOBALS['cfg']['ShowDbStructureLastUpdate']): ?>
            <td class="value tbl_last_update">-</td>
        <?php endif; ?>
        <?php if ($GLOBALS['cfg']['ShowDbStructureLastCheck']): ?>
            <td class="value tbl_last_check">-</td>
        <?php endif; ?>

    <?php else: ?>

        <td colspan="<?= $colspan_for_structure - ($db_is_system_schema ? 6 : 9); ?>"
            class="center">
            <?= __('in use'); ?>
        </td>

    <?php endif; ?>
</tr>
