<?php
$cnt = 0; // Let's count the columns...

if ($db_is_system_schema) {
    $action_colspan = 3;
} else {
    $action_colspan = 6;
}
if ($GLOBALS['cfg']['NumFavoriteTables'] > 0) {
    $action_colspan++;
}
?>
<form method="post" action="db_structure.php" name="tablesForm" id="tablesForm">
<?= PMA_URL_getHiddenInputs($db); ?>
<table class="data">
    <thead>
        <tr>
            <th class="print_ignore"></th>
            <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                   array(
                       'title' => __('Table'),
                       'sort' => 'table',
                       'initial_sort_order' => 'ASC'
                   )
                ); ?></th>
            <?php if ($replication): ?>
                <th><?= __('Replication'); ?></th>
            <?php endif; ?>
            <th colspan="<?= $action_colspan; ?>" class="print_ignore">
                <?= __('Action'); ?>
            </th>
            <!-- larger values are more interesting so default sort order is DESC-->
            <th>
                <?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                    array(
                        'title' => __('Rows'),
                        'sort' => 'records',
                        'initial_sort_order' => 'DESC'
                    )
                ); ?>
                <?= PMA\libraries\Util::showHint(PMA_sanitize(
                    __('May be approximate. Click on the number to get the exact'
                        . ' count. See [doc@faq3-11]FAQ 3.11[/doc].'))); ?>
            </th>
            <?php if (!($GLOBALS['cfg']['PropertiesNumColumns'] > 1)): ?>
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Type'),
                            'sort' => 'type',
                            'initial_sort_order' => 'ASC'
                        )
                    ); $cnt++; ?></th>
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Collation'),
                            'sort' => 'collation',
                            'initial_sort_order' => 'ASC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>

            <?php if ($GLOBALS['is_show_stats']): ?>
                <!-- larger values are more interesting so default sort order is DESC -->
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Size'),
                            'sort' => 'size',
                            'initial_sort_order' => 'DESC'
                        )
                    ); $cnt++; ?></th>
                <!-- larger values are more interesting so default sort order is DESC -->
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Overhead'),
                            'sort' => 'overhead',
                            'initial_sort_order' => 'DESC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>

            <?php if ($GLOBALS['cfg']['ShowDbStructureComment']): ?>
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Comment'),
                            'sort' => 'comment',
                            'initial_sort_order' => 'ASC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>

            <?php if ($GLOBALS['cfg']['ShowDbStructureCreation']): ?>
                <!-- newer values are more interesting so default sort order is DESC -->
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Creation'),
                            'sort' => 'creation',
                            'initial_sort_order' => 'DESC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>

            <?php if ($GLOBALS['cfg']['ShowDbStructureLastUpdate']): ?>
                <!-- newer values are more interesting so default sort order is DESC -->
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Last update'),
                            'sort' => 'last_update',
                            'initial_sort_order' => 'DESC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>

            <?php if ($GLOBALS['cfg']['ShowDbStructureLastCheck']): ?>
                <!-- newer values are more interesting so default sort order is DESC -->
                <th><?= PMA\libraries\Template::get('database/structure/sortable_header')->render(
                        array(
                            'title' => __('Last check'),
                            'sort' => 'last_check',
                            'initial_sort_order' => 'DESC'
                        )
                    ); $cnt++; ?></th>
            <?php endif; ?>
        </tr>
    </thead>
    <tbody>
        <?php $GLOBALS['colspan_for_structure'] = $cnt + $action_colspan + 3; ?>