<table id="layer_upd_relation" style="display:none;" width="5%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td class="frams1" width="10px">
            </td>
            <td class="frams5" width="99%">
            </td>
            <td class="frams2" width="10px">
                <div class="bor">
                </div>
            </td>
        </tr>
        <tr>
            <td class="frams8">
            </td>
            <td class="input_tab">
                <table width="100%" class="center" cellpadding="2" cellspacing="0">
                    <tr>
                        <td colspan="3" class="center nowrap">
                            <strong>
                                <?= __('Delete relationship'); ?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="center nowrap">
                            <input id="del_button" name="Button" type="button" class="butt" value="<?= __('Delete'); ?>" />
                            <input id="cancel_button" type="button" class="butt" name="Button" value="<?= __('Cancel'); ?>" />
                        </td>
                    </tr>
                </table>
            </td>
            <td class="frams6">
            </td>
        </tr>
        <tr>
            <td class="frams4">
                <div class="bor">
                </div>
            </td>
            <td class="frams7">
            </td>
            <td class="frams3">
            </td>
        </tr>
    </tbody>
</table>