<?php $cfgRelation = PhpMyAdmin\Relation::getRelationsParam(); ?>
<form action="db_designer.php" method="post" name="edit_delete_pages" id="edit_delete_pages" class="ajax">
    <?= PhpMyAdmin\Url::getHiddenInputs($db); ?>
    <fieldset id="page_edit_delete_options">
        <input type="hidden" name="operation" value="<?= $operation; ?>" />
        <label for="selected_page">
            <?= $operation == 'editPage' ? __("Page to open") : __("Page to delete"); ?>:
        </label>
        <?= PhpMyAdmin\Template::get('database/designer/page_selector')->render([
            'pdfwork' => $cfgRelation['pdfwork'],
            'pages' => PhpMyAdmin\Database\Designer::getPageIdsAndNames($db),
        ]); ?>
    </fieldset>
</form>
