<?php $cfgRelation = PMA_getRelationsParam(); ?>
<form action="db_designer.php" method="post" name="edit_delete_pages" id="edit_delete_pages" class="ajax">
    <?= PMA\libraries\URL::getHiddenInputs($db); ?>
    <fieldset id="page_edit_delete_options">
        <input type="hidden" name="operation" value="<?= $operation; ?>" />
        <label for="selected_page">
            <?= $operation == 'editPage' ? __("Page to open") : __("Page to delete"); ?>:
        </label>
        <?= PMA_getHtmlForPageSelector($cfgRelation, $db); ?>
    </fieldset>
</form>
