<table id="layer_new_relation" style="display:none;" width="5%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td class="frams1" width="10px">
            </td>
            <td class="frams5" width="99%" >
            </td>
            <td class="frams2" width="10px">
                <div class="bor">
                </div>
            </td>
        </tr>
        <tr>
            <td class="frams8">
            </td>
            <td class="input_tab">
                <table width="168" class="center" cellpadding="2" cellspacing="0">
                    <thead>
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <strong>
                                    <?= __('Create relation'); ?>
                                </strong>
                            </td>
                        </tr>
                    </thead>
                    <tbody id="foreign_relation">
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <strong>
                                    FOREIGN KEY
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                on delete
                            </td>
                            <td width="102">
                                <select name="on_delete" id="on_delete">
                                    <option value="nix" selected="selected">
                                        --
                                    </option>
                                    <option value="CASCADE">
                                        CASCADE
                                    </option>
                                    <option value="SET NULL">
                                        SET NULL
                                    </option>
                                    <option value="NO ACTION">
                                        NO ACTION
                                    </option>
                                    <option value="RESTRICT">
                                        RESTRICT
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="nowrap">
                                on update
                            </td>
                            <td>
                                <select name="on_update" id="on_update">
                                    <option value="nix" selected="selected">
                                        --
                                    </option>
                                    <option value="CASCADE">
                                        CASCADE
                                    </option>
                                    <option value="SET NULL">
                                        SET NULL
                                    </option>
                                    <option value="NO ACTION">
                                        NO ACTION
                                    </option>
                                    <option value="RESTRICT">
                                        RESTRICT
                                    </option>
                                </select>
                            </td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <input type="button" id="ok_new_rel_panel" class="butt" name="Button" value="<?= __('OK'); ?>" />
                                <input type="button" id="cancel_new_rel_panel" class="butt" name="Button" value="<?= __('Cancel'); ?>" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td class="frams6">
            </td>
        </tr>
        <tr>
            <td class="frams4">
                <div class="bor">
                </div>
            </td>
            <td class="frams7">
            </td>
            <td class="frams3">
            </td>
        </tr>
    </tbody>
</table>