<table id="pmd_optionse" style="display:none;" width="5%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td class="frams1" width="10px">
            </td>
            <td class="frams5" width="99%" >
            </td>
            <td class="frams2" width="10px">
                <div class="bor">
                </div>
            </td>
        </tr>
        <tr>
            <td class="frams8">
            </td>
            <td class="input_tab">
                <table width="168" class="center" cellpadding="2" cellspacing="0">
                    <thead>
                        <tr>
                            <td colspan="2" rowspan="2" id="option_col_name" class="center nowrap">
                            </td>
                        </tr>
                    </thead>
                    <tbody id="where">
                        <tr>
                            <td class="center nowrap">
                                <b>
                                    WHERE
                                </b>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('Relation operator'); ?>
                            </td>
                            <td width="102">
                                <select name="rel_opt" id="rel_opt">
                                    <option value="--" selected="selected">
                                        --
                                    </option>
                                    <option value="=">
                                        =
                                    </option>
                                    <option value="&gt;">
                                        &gt;
                                    </option>
                                    <option value="&lt;">
                                        &lt;
                                    </option>
                                    <option value="&gt;=">
                                        &gt;=
                                    </option>
                                    <option value="&lt;=">
                                        &lt;=
                                    </option>
                                    <option value="NOT">
                                        NOT
                                    </option>
                                    <option value="IN">
                                        IN
                                    </option>
                                    <option value="EXCEPT">
                                        <?php echo __('Except'); ?>
                                    </option>
                                    <option value="NOT IN">
                                        NOT IN
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="nowrap">
                                <?php echo __('Value'); ?>
                                <br />
                                <?php echo __('subquery'); ?>
                            </td>
                            <td>
                                <textarea id="Query" value="" cols="18">
                                </textarea>
                            </td>
                        </tr>
                        <tr>
                            <td class="center nowrap">
                                <b>
                                    <?php echo __('Rename to'); ?>
                                </b>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('New name'); ?>
                            </td>
                            <td width="102">
                                <input type="text" value="" id="new_name"/>
                            </td>
                        </tr>
                        <tr>
                            <td class="center nowrap">
                                <b>
                                    <?php echo __('Aggregate'); ?>
                                </b>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('Operator'); ?>
                            </td>
                            <td width="102">
                                <select name="operator" id="operator">
                                    <option value="---" selected="selected">
                                        ---
                                    </option>
                                    <option value="sum" >
                                        SUM
                                    </option>
                                    <option value="min">
                                        MIN
                                    </option>
                                    <option value="max">
                                        MAX
                                    </option>
                                    <option value="avg">
                                        AVG
                                    </option>
                                    <option value="count">
                                        COUNT
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="center nowrap">
                                <b>
                                    GROUP BY
                                </b>
                            </td>
                            <td>
                                <input type="checkbox" value="groupby" id="groupby"/>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="center nowrap">
                                <b>
                                    ORDER BY
                                </b>
                            </td>
                            <td>
                                <select name="orderby" id="orderby">
                                    <option value="---" selected="selected">
                                        ---
                                    </option>
                                    <option value="ASC" >
                                        ASC
                                    </option>
                                    <option value="DESC">
                                        DESC
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td class="center nowrap">
                                <b>
                                    HAVING
                                </b>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('Operator'); ?>
                            </td>
                            <td width="102">
                                <select name="h_operator" id="h_operator">
                                    <option value="---" selected="selected">
                                        ---
                                    </option>
                                    <option value="None" >
                                        <?php echo __('None'); ?>
                                    </option>
                                    <option value="sum" >
                                        SUM
                                    </option>
                                    <option value="min">
                                        MIN
                                    </option>
                                    <option value="max">
                                        MAX
                                    </option>
                                    <option value="avg">
                                        AVG
                                    </option>
                                    <option value="count">
                                        COUNT
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('Relation operator'); ?>
                            </td>
                            <td width="102">
                                <select name="h_rel_opt" id="h_rel_opt">
                                    <option value="--" selected="selected">
                                        --
                                    </option>
                                    <option value="=">
                                        =
                                    </option>
                                    <option value="&gt;">
                                        &gt;
                                    </option>
                                    <option value="&lt;">
                                        &lt;
                                    </option>
                                    <option value="&gt;=">
                                        &gt;=
                                    </option>
                                    <option value="&lt;=">
                                        &lt;=
                                    </option>
                                    <option value="NOT">
                                        NOT
                                    </option>
                                    <option value="IN">
                                        IN
                                    </option>
                                    <option value="EXCEPT">
                                        <?php echo __('Except'); ?>
                                    </option>
                                    <option value="NOT IN">
                                        NOT IN
                                    </option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('Value'); ?>
                                <br/>
                                <?php echo __('subquery'); ?>
                            </td>
                            <td width="102">
                                <textarea id="having" value="" cols="18">
                                </textarea>
                            </td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <input type="button" id="ok_add_object" class="butt" name="Button" value="<?php echo __('OK'); ?>" />
                                <input type="button" id="cancel_close_option" class="butt" name="Button" value="<?php echo __('Cancel'); ?>" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td class="frams6">
            </td>
        </tr>
        <tr>
            <td class="frams4">
                <div class="bor">
                </div>
            </td>
            <td class="frams7">
            </td>
            <td class="frams3">
            </td>
        </tr>
    </tbody>
</table>