<?php
$cfgRelation = PMA_getRelationsParam();
$choices = array(
    'same' => __('Save to selected page'),
    'new' => __('Create a page and save to it')
);
?>
<form action="db_designer.php" method="post" name="save_as_pages" id="save_as_pages" class="ajax">
    <?= PMA\libraries\URL::getHiddenInputs($db); ?>
    <fieldset id="page_save_as_options">
        <table>
            <tbody>
                <tr>
                    <td>
                        <input type="hidden" name="operation" value="savePage" />
                        <?= PMA_getHtmlForPageSelector($cfgRelation, $db); ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= PMA\libraries\Util::getRadioFields('save_page', $choices, 'same', true); ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="selected_value"><?= __('New page name'); ?></label>
                        <input type="text" name="selected_value" id="selected_value" />
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</form>
