<div class="panel">
    <div style="clear:both;">
    </div>
    <div id="ab">
    </div>
    <div style="clear:both;">
    </div>
</div>
<a class="trigger" href="#">
    <?= __('Active options'); ?>
</a>
<div id="box">
    <form method="post" action="db_qbe.php" id="vqb_form">
        <textarea cols="80" name="sql_query" id="textSqlquery" rows="15">
        </textarea>
        <input type="hidden" name="submit_sql" value="true">
        <?= PMA_URL_getHiddenInputs($_GET['db']); ?>
    </form>
</div>