
<table id="query_rename_to" style="display:none;" width="5%" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td class="frams1" width="10px">
            </td>
            <td class="frams5" width="99%" >
            </td>
            <td class="frams2" width="10px">
                <div class="bor">
                </div>
            </td>
        </tr>
        <tr>
            <td class="frams8">
            </td>
            <td class="input_tab">
                <table width="168" class="center" cellpadding="2" cellspacing="0">
                    <thead>
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <strong>
                                    <?php echo __('Rename to'); ?>
                                </strong>
                            </td>
                        </tr>
                    </thead>
                    <tbody id="rename_to">
                        <tr>
                            <td width="58" class="nowrap">
                                <?php echo __('New name'); ?>
                            </td>
                            <td width="102">
                                <input type="text" value="" id="e_rename"/>
                            </td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <td colspan="2" class="center nowrap">
                                <input type="button" id="ok_edit_rename" class="butt" name="Button" value="<?php echo __('OK'); ?>" />
                                <input type="button"
                                       class="butt"
                                       name="Button"
                                       value="<?php echo __('Cancel'); ?>"
                                       onclick="document.getElementById('query_rename_to').style.display = 'none';" />
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td class="frams6">
            </td>
        </tr>
        <tr>
            <td class="frams4">
                <div class="bor">
                </div>
            </td>
            <td class="frams7">
            </td>
            <td class="frams3">
            </td>
        </tr>
    </tbody>
</table>