<form method="post" action="schema_export.php" class="disableAjax" id="id_export_pages">
    <fieldset>
        <?= PMA\libraries\URL::getHiddenInputs($db); ?>
        <label><?= __('Select Export Relational Type'); ?></label><br/>
        <?= PMA_pluginGetChoice(
            'Schema', 'export_type', $export_list, 'format'
        ); ?>
        <input type="hidden" name="page_number" value="<?= htmlspecialchars($page); ?>" />
        <?= PMA_pluginGetOptions('Schema', $export_list); ?>
    </fieldset>
</form>
