<form method="post" action="schema_export.php" class="disableAjax" id="id_export_pages">
    <fieldset>
        <?php echo PMA_URL_getHiddenInputs($db); ?>
        <label><?php echo __('Select Export Relational Type'); ?></label><br/>
        <?php echo PMA_pluginGetChoice(
            'Schema', 'export_type', $export_list, 'format'
        ); ?>
        <input type="hidden" name="page_number" value="<?php echo htmlspecialchars($page); ?>" />
        <?php echo PMA_pluginGetOptions('Schema', $export_list); ?>
    </fieldset>
</form>