<form method="post" action="schema_export.php" class="disableAjax" id="id_export_pages">
    <fieldset>
        <?= PhpMyAdmin\Url::getHiddenInputs($db); ?>
        <label><?= __('Select Export Relational Type'); ?></label><br/>
        <?= PhpMyAdmin\Plugins::getChoice(
            'Schema', 'export_type', $export_list, 'format'
        ); ?>
        <input type="hidden" name="page_number" value="<?= htmlspecialchars($page); ?>" />
        <?= PhpMyAdmin\Plugins::getOptions('Schema', $export_list); ?>
    </fieldset>
</form>
