<?php
function getImg($path)
{
    return $_SESSION['PMA_Theme']->getImgPath($path);
}
?>
<?php if (!$visualBuilder) : ?>
    <div id="name-panel" style="overflow:hidden">
        <span id="page_name" style="border:none">
            <?= $selected_page == null ? __("Untitled") : htmlspecialchars($selected_page); ?>
        </span>
        <span id="saved_state" style="border:none">
            <?= $selected_page == null ? '*' : ''; ?>
        </span>
    </div>
<?php endif; ?>
<div class="pmd_header side-menu" id="side_menu">
    <a class="M_butt" id="key_Show_left_menu" href="#">
        <img title="<?= __('Show/Hide tables list'); ?>"
             alt="v"
             src="<?= getImg('pmd/downarrow2_m.png'); ?>"
             data-down="<?= getImg('pmd/downarrow2_m.png'); ?>"
             data-up="<?= getImg('pmd/uparrow2_m.png'); ?>" />
        <span class="hide hidable">
            <?= __('Show/Hide tables list'); ?>
        </span>
    </a>
    <a href="#" id="toggleFullscreen" class="M_butt">
        <img title="<?= __('View in fullscreen'); ?>"
             src="<?= getImg('pmd/viewInFullscreen.png'); ?>"
             data-enter="<?= getImg('pmd/viewInFullscreen.png'); ?>"
             data-exit="<?= getImg('pmd/exitFullscreen.png'); ?>" />
        <span class="hide hidable"
              data-exit="<?= __('Exit fullscreen'); ?>"
              data-enter="<?= __('View in fullscreen'); ?>">
            <?= __('View in fullscreen'); ?>
        </span>
    </a>
    <?php if (! $visualBuilder) : ?>
        <a id="newPage" href="#" class="M_butt">
            <img title="<?= __('New page'); ?>"
                 alt=""
                 src="<?= getImg('pmd/page_add.png'); ?>" />
            <span class="hide hidable">
                <?= __('New page'); ?>
            </span>
        </a>
        <a href="#" id="editPage" class="M_butt ajax">
            <img title="<?= __('Open page'); ?>"
                 src="<?= getImg('pmd/page_edit.png'); ?>" />
            <span class="hide hidable">
                <?= __('Open page'); ?>
            </span>
        </a>
        <a href="#" id="savePos" class="M_butt">
            <img title="<?= __('Save page'); ?>"
                 src="<?= getImg('pmd/save.png'); ?>" />
            <span class="hide hidable">
                <?= __('Save page'); ?>
            </span>
        </a>
        <a href="#" id="SaveAs" class="M_butt ajax">
            <img title="<?= __('Save page as'); ?>"
                 src="<?= getImg('pmd/save_as.png'); ?>" />
            <span class="hide hidable">
                <?= __('Save page as'); ?>
            </span>
        </a>
        <a href="#" id="delPages" class="M_butt ajax">
            <img title="<?= __('Delete pages'); ?>"
                 src="<?= getImg('pmd/page_delete.png'); ?>" />
            <span class="hide hidable">
                <?= __('Delete pages'); ?>
            </span>
        </a>
        <a href="#" id="StartTableNew" class="M_butt">
            <img title="<?= __('Create table'); ?>"
                 src="<?= getImg('pmd/table.png'); ?>" />
            <span class="hide hidable">
                <?= __('Create table'); ?>
            </span>
        </a>
        <a href="#" class="M_butt" id="rel_button">
            <img title="<?= __('Create relationship'); ?>"
                 src="<?= getImg('pmd/relation.png'); ?>" />
            <span class="hide hidable">
                <?= __('Create relationship'); ?>
            </span>
        </a>
        <a href="#" class="M_butt" id="display_field_button">
            <img title="<?= __('Choose column to display'); ?>"
                 src="<?= getImg('pmd/display_field.png'); ?>" />
            <span class="hide hidable">
                <?= __('Choose column to display'); ?>
            </span>
        </a>
        <a href="#" id="reloadPage" class="M_butt">
            <img title="<?= __('Reload'); ?>"
                 src="<?= getImg('pmd/reload.png'); ?>" />
            <span class="hide hidable">
                <?= __('Reload'); ?>
            </span>
        </a>
        <a href="<?= PMA\libraries\Util::getDocuLink('faq', 'faq6-31'); ?>"
           target="documentation"
           class="M_butt">
            <img title="<?= __('Help'); ?>"
                 src="<?= getImg('pmd/help.png'); ?>" />
            <span class="hide hidable">
                <?= __('Help'); ?>
            </span>
        </a>
    <?php endif; ?>
    <a href="#" class="<?= $params_array['angular_direct']; ?>" id="angular_direct_button">
        <img title="<?= __('Angular links'); ?> / <?= __('Direct links'); ?>"
             src="<?= getImg('pmd/ang_direct.png'); ?>" />
        <span class="hide hidable">
            <?= __('Angular links'); ?> / <?= __('Direct links'); ?>
        </span>
    </a>
    <a href="#" class="<?= $params_array['snap_to_grid']; ?>" id="grid_button">
        <img title="<?= __('Snap to grid'); ?>" src="<?= getImg('pmd/grid.png'); ?>" />
        <span class="hide hidable">
            <?= __('Snap to grid'); ?>
        </span>
    </a>
    <a href="#" class="<?= $params_array['small_big_all']; ?>" id="key_SB_all">
        <img title="<?= __('Small/Big All'); ?>"
             alt="v"
             src="<?= getImg('pmd/downarrow1.png'); ?>"
             data-down="<?= getImg('pmd/downarrow1.png'); ?>"
             data-right="<?= getImg('pmd/rightarrow1.png') ?>" />
        <span class="hide hidable">
            <?= __('Small/Big All'); ?>
        </span>
    </a>
    <a href="#" id="SmallTabInvert" class="M_butt" >
        <img title="<?= __('Toggle small/big'); ?>"
             src="<?= getImg('pmd/bottom.png'); ?>" />
        <span class="hide hidable">
            <?= __('Toggle small/big'); ?>
        </span>
    </a>
    <a href="#" id="relLineInvert" class="<?= $params_array['relation_lines']; ?>" >
        <img title="<?= __('Toggle relationship lines'); ?>"
             src="<?= getImg('pmd/toggle_lines.png'); ?>" />
        <span class="hide hidable">
            <?= __('Toggle relationship lines'); ?>
        </span>
    </a>
    <?php if (! $visualBuilder) : ?>
        <a href="#" id="exportPages" class="M_butt" >
            <img title="<?= __('Export schema'); ?>"
                 src="<?= getImg('pmd/export.png'); ?>" />
            <span class="hide hidable">
                <?= __('Export schema'); ?>
            </span>
        </a>
    <?php else: ?>
        <a class="M_butt"
           href="#"
           onclick="build_query('SQL Query on Database', 0)"
           onmousedown="return false;"
           class="M_butt">
            <img title="<?= __('Build Query'); ?>"
                 src="<?= getImg('pmd/query_builder.png'); ?>" />
            <span class="hide hidable">
                <?= __('Build Query'); ?>
            </span>
        </a>
    <?php endif; ?>
    <a href="#" class="<?= $params_array['side_menu']; ?>" id="key_Left_Right">
        <img title="<?= __('Move Menu'); ?>" alt=">"
             data-right="<?= getImg('pmd/2leftarrow_m.png'); ?>"
             src="<?= getImg('pmd/2rightarrow_m.png'); ?>" />
        <span class="hide hidable">
            <?= __('Move Menu'); ?>
        </span>
    </a>
    <a href="#" class="<?= $params_array['pin_text']; ?>" id="pin_Text">
        <img title="<?= __('Pin text'); ?>"
             alt=">"
             data-right="<?= getImg('pmd/anchor.png'); ?>"
             src="<?= getImg('pmd/anchor.png'); ?>" />
        <span class="hide hidable">
            <?= __('Pin text'); ?>
        </span>
    </a>
</div>