<div id="layer_menu" style="display:none;">
    <div class="center">
        <a href="#" class="M_butt" target="_self" >
            <img title="<?= __('Hide/Show all'); ?>"
                 alt="v"
                 id="key_HS_all"
                 src="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/downarrow1.png'); ?>"
                 data-down="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/downarrow1.png'); ?>"
                 data-right="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/rightarrow1.png'); ?>" />
        </a>
        <a href="#" class="M_butt" target="_self" >
            <img alt="v"
                 id="key_HS"
                 title="<?= __('Hide/Show Tables with no relation'); ?>"
                 src="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/downarrow2.png'); ?>"
                 data-down="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/downarrow2.png'); ?>"
                 data-right="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/rightarrow2.png'); ?>" />
        </a>
    </div>
    <div id="id_scroll_tab" class="scroll_tab">
        <table width="100%" style="padding-left: 3px;">
            <?php $name_cnt = count($GLOBALS['PMD']['TABLE_NAME']);
            for ($i = 0; $i < $name_cnt; $i++) :
                $checked = (isset($tab_pos[$GLOBALS['PMD']["TABLE_NAME"][$i]])
                    && $tab_pos[$GLOBALS['PMD']["TABLE_NAME"][$i]]["H"])
                    || $display_page == -1; ?>
                <tr>
                    <td title="<?= __('Structure'); ?>"
                        width="1px"
                        onmouseover="this.className='L_butt2_2'"
                        onmouseout="this.className='L_butt2_1'"
                        class="L_butt2_1">
                        <img alt=""
                             table_name="<?= $GLOBALS['PMD_URL']['TABLE_NAME_SMALL'][$i]; ?>"
                             class="scroll_tab_struct"
                             src="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/exec.png'); ?>"/>
                    </td>
                    <td width="1px">
                        <input class="scroll_tab_checkbox"
                               title="<?= __('Hide'); ?>"
                               id="check_vis_<?= $GLOBALS['PMD_URL']["TABLE_NAME"][$i]; ?>"
                               style="margin:0;"
                               type="checkbox"
                               value="<?= $GLOBALS['PMD_URL']["TABLE_NAME"][$i]; ?>"
                               <?php if ($checked) : ?>checked="checked"<?php endif; ?> />
                    </td>
                    <td class="pmd_Tabs"
                        onmouseover="this.className='pmd_Tabs2'"
                        onmouseout="this.className='pmd_Tabs'"
                        pmd_url_table_name="<?= $GLOBALS['PMD_URL']['TABLE_NAME'][$i]; ?>">
                        <?= $GLOBALS['PMD_OUT']["TABLE_NAME"][$i]; ?>
                    </td>
                </tr>
            <?php endfor; ?>
        </table>
    </div>
    <!-- end id_scroll_tab -->
    <div class="center">
        <?= __('Number of tables:'); ?> <?= $name_cnt; ?>
    </div>
    <div id="layer_menu_sizer" onmousedown="layer_menu_cur_click=1">
        <div class="floatleft">
            <img class="icon"
                 data-right="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/resizeright.png'); ?>"
                 src="<?= $_SESSION['PMA_Theme']->getImgPath('pmd/resize.png'); ?>"/>
        </div>
    </div>
</div>
<!-- end layer_menu -->