# scrutinizer-ci.com configuration
imports:
  - javascript
  - php
filter:
  excluded_paths:
    - build/
    - js/vendor/
    - node_modules/
    - tmp/
    - vendor/
checks:
  javascript: true
  php: true
build:
  nodes:
    analysis:
      environment:
        php: 7.1
        node: 10
      dependencies:
        before:
          - composer install
          - composer require tecnickcom/tcpdf pragmarx/google2fa-qrcode samyoul/u2f-php-server
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
