const path = require('path');
const webpack = require('webpack');

module.exports = {
    context: path.resolve(__dirname, 'js'),
    entry: {
        'codemirror/addon/lint/sql-lint': './codemirror/addon/lint/sql-lint.js',
        'jqplot/plugins/jqplot.byteFormatter': './jqplot/plugins/jqplot.byteFormatter.js',
        'pmd/designer_db': './pmd/designer_db.js',
        'pmd/designer_objects': './pmd/designer_objects.js',
        'pmd/designer_page': './pmd/designer_page.js',
        'pmd/history': './pmd/history.js',
        'pmd/init': './pmd/init.js',
        'pmd/move': './pmd/move.js',
        'transformations/image_upload': './transformations/image_upload.js',
        'transformations/json_editor': './transformations/json_editor.js',
        'transformations/json': './transformations/json.js',
        'transformations/sql_editor': './transformations/sql_editor.js',
        'transformations/xml_editor': './transformations/xml_editor.js',
        'transformations/xml': './transformations/xml.js',
        'ajax': './ajax.js',
        'chart': './chart.js',
        'common': ['./menu-resizer.js', './common.js'],
        'config': './config.js',
        'console': ['./menu-resizer.js', './console.js'],
        'cross_framing_protection': './cross_framing_protection.js',
        'db_central_columns': './db_central_columns.js',
        'db_operations': './db_operations.js',
        'db_qbe': './db_qbe.js',
        'db_search': './db_search.js',
        'db_structure': './db_structure.js',
        'db_tracking': './db_tracking.js',
        'doclinks': './doclinks.js',
        'error_report': './error_report.js',
        'export': './export.js',
        'functions': ['./menu-resizer.js', './functions.js'],
        'get_image': ['./menu-resizer.js', './get_image.js'],
        'gis_data_editor': './gis_data_editor.js',
        'import': './import.js',
        'indexes': './indexes.js',
        'keyhandler': './keyhandler.js',
        'makegrid': './makegrid.js',
        'menu-resizer': './menu-resizer.js',
        'messages': './messages.js',
        'microhistory': './microhistory.js',
        'multi_column_sort': './multi_column_sort.js',
        'navigation': ['./menu-resizer.js', './navigation.js'],
        'normalization': './normalization.js',
        'page_settings': './page_settings.js',
        'replication': './replication.js',
        'rte': './rte.js',
        'server_databases': './server_databases.js',
        'server_plugins': './server_plugins.js',
        'server_privileges': './server_privileges.js',
        'server_status_advisor': './server_status_advisor.js',
        'server_status_monitor': './server_status_monitor.js',
        'server_status_processes': './server_status_processes.js',
        'server_status_queries': './server_status_queries.js',
        'server_status_sorter': './server_status_sorter.js',
        'server_status_variables': './server_status_variables.js',
        'server_user_groups': './server_user_groups.js',
        'server_variables': './server_variables.js',
        'shortcuts_handler': './shortcuts_handler.js',
        'sql': './sql.js',
        'tbl_change': './tbl_change.js',
        'tbl_chart': './tbl_chart.js',
        'tbl_find_replace': './tbl_find_replace.js',
        'tbl_gis_visualization': './tbl_gis_visualization.js',
        'tbl_operations': './tbl_operations.js',
        'tbl_relation': './tbl_relation.js',
        'tbl_select': './tbl_select.js',
        'tbl_structure': './tbl_structure.js',
        'tbl_tracking': './tbl_tracking.js',
        'tbl_zoom_plot_jqplot': './tbl_zoom_plot_jqplot.js',
        'whitelist': './whitelist.js',

        'vendor/codemirror/addon/hint/show-hint': 'codemirror/addon/hint/show-hint',
        'vendor/codemirror/addon/hint/sql-hint': 'codemirror/addon/hint/sql-hint',
        'vendor/codemirror/addon/lint/lint': 'codemirror/addon/lint/lint',
        'vendor/codemirror/addon/runmode/runmode': 'codemirror/addon/runmode/runmode',
        'vendor/codemirror/lib/codemirror': 'codemirror/lib/codemirror',
        'vendor/codemirror/mode/javascript/javascript': 'codemirror/mode/javascript/javascript',
        'vendor/codemirror/mode/sql/sql': 'codemirror/mode/sql/sql',
        'vendor/codemirror/mode/xml/xml': 'codemirror/mode/xml/xml',

        'vendor/jqplot/jquery.jqplot': './vendor/jqplot/jquery.jqplot.js',
        'vendor/jqplot/plugins/jqplot.barRenderer': './vendor/jqplot/plugins/jqplot.barRenderer.js',
        'vendor/jqplot/plugins/jqplot.canvasAxisLabelRenderer': './vendor/jqplot/plugins/jqplot.canvasAxisLabelRenderer.js',
        'vendor/jqplot/plugins/jqplot.canvasTextRenderer': './vendor/jqplot/plugins/jqplot.canvasTextRenderer.js',
        'vendor/jqplot/plugins/jqplot.categoryAxisRenderer': './vendor/jqplot/plugins/jqplot.categoryAxisRenderer.js',
        'vendor/jqplot/plugins/jqplot.cursor': './vendor/jqplot/plugins/jqplot.cursor.js',
        'vendor/jqplot/plugins/jqplot.dateAxisRenderer': './vendor/jqplot/plugins/jqplot.dateAxisRenderer.js',
        'vendor/jqplot/plugins/jqplot.enhancedPieLegendRenderer': './vendor/jqplot/plugins/jqplot.enhancedPieLegendRenderer.js',
        'vendor/jqplot/plugins/jqplot.highlighter': './vendor/jqplot/plugins/jqplot.highlighter.js',
        'vendor/jqplot/plugins/jqplot.pieRenderer': './vendor/jqplot/plugins/jqplot.pieRenderer.js',
        'vendor/jqplot/plugins/jqplot.pointLabels': './vendor/jqplot/plugins/jqplot.pointLabels.js',

        'vendor/jquery/jquery.min': 'jquery',
        'vendor/jquery/jquery-migrate-3.0.0': 'jquery-migrate',
        'vendor/jquery/jquery-ui.min': 'jquery-ui',
        'vendor/jquery/jquery-ui-timepicker-addon': [
            'jquery-ui/ui/widgets/datepicker',
            'jquery-ui-timepicker-addon'
        ],
        'vendor/jquery/jquery.event.drag-2.2': 'jquery.event.drag',
        'vendor/jquery/jquery.mousewheel': 'jquery-mousewheel',
        'vendor/jquery/jquery.validate': 'jquery-validation/dist/jquery.validate',
        'vendor/jquery/additional-methods': 'jquery-validation/dist/additional-methods',
        'vendor/jquery/jquery.ba-hashchange-1.3': './vendor/jquery/jquery.ba-hashchange-1.3.js',
        'vendor/jquery/jquery.debounce-1.0.5': './vendor/jquery/jquery.debounce-1.0.5.js',
        'vendor/jquery/jquery.fullscreen': './vendor/jquery/jquery.fullscreen.js',
        'vendor/jquery/jquery.sortableTable': './vendor/jquery/jquery.sortableTable.js',
        'vendor/jquery/jquery.svg': './vendor/jquery/jquery.svg.js',
        'vendor/jquery/jquery.tablesorter': './vendor/jquery/jquery.tablesorter.js',
        'vendor/jquery/jquery.uitablefilter': './vendor/jquery/jquery.uitablefilter.js',

        'vendor/openlayers/OpenLayers': './vendor/openlayers/OpenLayers.js',
        'vendor/js.cookie': 'js-cookie',
        'vendor/sprintf': 'locutus/php/strings/sprintf',
        'vendor/tracekit': 'tracekit',
        'vendor/zxcvbn': 'zxcvbn',
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'js/dist')
    },
    resolve: {
        alias: {
            jquery: 'jquery/src/jquery',
        }
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [/node_modules/],
                use: [{
                    loader: 'babel-loader',
                    options: {
                        presets: ['es2015']
                    },
                }],
            },
        ]
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
        }),
        new webpack.optimize.ModuleConcatenationPlugin(),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'commons',
            minChunks: 2
        }),
    ]
};
