const path = require('path');

module.exports = {
    mode: 'none',
    entry: {
        'ajax': './js/src/ajax.js',
        'chart': './js/src/chart.js',
        'codemirror/addon/lint/sql-lint': './js/src/codemirror/addon/lint/sql-lint.js',
        'common': './js/src/common.js',
        'config': './js/src/config.js',
        'console': './js/src/console.js',
        'cross_framing_protection': './js/src/cross_framing_protection.js',
        'database/central_columns': './js/src/database/central_columns.js',
        'database/events': './js/src/database/events.js',
        'database/multi_table_query': './js/src/database/multi_table_query.js',
        'database/operations': './js/src/database/operations.js',
        'database/qbe': './js/src/database/qbe.js',
        'database/query_generator': './js/src/database/query_generator.js',
        'database/routines': './js/src/database/routines.js',
        'database/search': './js/src/database/search.js',
        'database/structure': './js/src/database/structure.js',
        'database/tracking': './js/src/database/tracking.js',
        'database/triggers': './js/src/database/triggers.js',
        'designer/database': './js/src/designer/database.js',
        'designer/history': './js/src/designer/history.js',
        'designer/init': './js/src/designer/init.js',
        'designer/move': './js/src/designer/move.js',
        'designer/objects': './js/src/designer/objects.js',
        'designer/page': './js/src/designer/page.js',
        'doclinks': './js/src/doclinks.js',
        'drag_drop_import': './js/src/drag_drop_import.js',
        'error_report': './js/src/error_report.js',
        'export': './js/src/export.js',
        'export_output': './js/src/export_output.js',
        'functions': './js/src/functions.js',
        'gis_data_editor': './js/src/gis_data_editor.js',
        'home': './js/src/home.js',
        'import': './js/src/import.js',
        'indexes': './js/src/indexes.js',
        'jqplot/plugins/jqplot.byteFormatter': './js/src/jqplot/plugins/jqplot.byteFormatter.js',
        'jquery.sortable-table': './js/src/jquery.sortable-table.js',
        'keyhandler': './js/src/keyhandler.js',
        'makegrid': './js/src/makegrid.js',
        'menu_resizer': './js/src/menu_resizer.js',
        'multi_column_sort': './js/src/multi_column_sort.js',
        'name-conflict-fixes': './js/src/name-conflict-fixes.js',
        'navigation': './js/src/navigation.js',
        'normalization': './js/src/normalization.js',
        'page_settings': './js/src/page_settings.js',
        'replication': './js/src/replication.js',
        'server/databases': './js/src/server/databases.js',
        'server/plugins': './js/src/server/plugins.js',
        'server/privileges': './js/src/server/privileges.js',
        'server/user_groups': './js/src/server/user_groups.js',
        'server/variables': './js/src/server/variables.js',
        'setup/ajax': './js/src/setup/ajax.js',
        'setup/scripts': './js/src/setup/scripts.js',
        'shortcuts_handler': './js/src/shortcuts_handler.js',
        'sql': './js/src/sql.js',
        'table/change': './js/src/table/change.js',
        'table/chart': './js/src/table/chart.js',
        'table/find_replace': './js/src/table/find_replace.js',
        'table/gis_visualization': './js/src/table/gis_visualization.js',
        'table/operations': './js/src/table/operations.js',
        'table/relation': './js/src/table/relation.js',
        'table/select': './js/src/table/select.js',
        'table/structure': './js/src/table/structure.js',
        'table/tracking': './js/src/table/tracking.js',
        'table/zoom_plot_jqplot': './js/src/table/zoom_plot_jqplot.js',
        'transformations/image_upload': './js/src/transformations/image_upload.js',
        'transformations/json': './js/src/transformations/json.js',
        'transformations/json_editor': './js/src/transformations/json_editor.js',
        'transformations/sql_editor': './js/src/transformations/sql_editor.js',
        'transformations/xml': './js/src/transformations/xml.js',
        'transformations/xml_editor': './js/src/transformations/xml_editor.js',
        'u2f': './js/src/u2f.js',
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'js/dist'),
        iife: false,
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets:  ['@babel/preset-env']
                    }
                }
            }
        ],
    },
};
