<?php
/* AUTOGENERATED CONTENT - DO NOT EDIT */
/* ALL CHANGES WILL BE UNDONE */
/* RUN './scripts/generate-sprites' TO UPDATE THIS FILE */
function PMA_sprites() {
    return array(
        'b_bookmark' => array(
            'position' => '1',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_browse' => array(
            'position' => '2',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_calendar' => array(
            'position' => '3',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_chart' => array(
            'position' => '4',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_close' => array(
            'position' => '5',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_comment' => array(
            'position' => '6',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_browse' => array(
            'position' => '7',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_dbstatistics' => array(
            'position' => '8',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_deltbl' => array(
            'position' => '9',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_drop' => array(
            'position' => '10',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_edit' => array(
            'position' => '11',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_deltbl' => array(
            'position' => '12',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_empty' => array(
            'position' => '13',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_export' => array(
            'position' => '14',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_ftext' => array(
            'position' => '15',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_index' => array(
            'position' => '16',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_insrow' => array(
            'position' => '17',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_nextpage' => array(
            'position' => '18',
            'width'    => '8',
            'height'   => '13'
        ),
        'b_docs' => array(
            'position' => '19',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_primary' => array(
            'position' => '20',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_drop' => array(
            'position' => '21',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_sbrowse' => array(
            'position' => '22',
            'width'    => '10',
            'height'   => '10'
        ),
        'bd_select' => array(
            'position' => '23',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_spatial' => array(
            'position' => '24',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_unique' => array(
            'position' => '25',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_edit' => array(
            'position' => '26',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_empty' => array(
            'position' => '27',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_engine' => array(
            'position' => '28',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_event_add' => array(
            'position' => '29',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_events' => array(
            'position' => '30',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_export' => array(
            'position' => '31',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_ftext' => array(
            'position' => '32',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_help' => array(
            'position' => '33',
            'width'    => '11',
            'height'   => '11'
        ),
        'b_home' => array(
            'position' => '34',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_import' => array(
            'position' => '35',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_index' => array(
            'position' => '36',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_info' => array(
            'position' => '37',
            'width'    => '11',
            'height'   => '11'
        ),
        'b_inline_edit' => array(
            'position' => '38',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_insrow' => array(
            'position' => '39',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_minus' => array(
            'position' => '40',
            'width'    => '9',
            'height'   => '9'
        ),
        'b_more' => array(
            'position' => '41',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_newdb' => array(
            'position' => '42',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_newtbl' => array(
            'position' => '43',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_nextpage' => array(
            'position' => '44',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_plus' => array(
            'position' => '45',
            'width'    => '9',
            'height'   => '9'
        ),
        'b_primary' => array(
            'position' => '46',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_print' => array(
            'position' => '47',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_props' => array(
            'position' => '48',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_relations' => array(
            'position' => '49',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_routine_add' => array(
            'position' => '50',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_routines' => array(
            'position' => '51',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_save' => array(
            'position' => '52',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sbrowse' => array(
            'position' => '53',
            'width'    => '10',
            'height'   => '10'
        ),
        'b_search' => array(
            'position' => '54',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_selboard' => array(
            'position' => '55',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_select' => array(
            'position' => '56',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_snewtbl' => array(
            'position' => '57',
            'width'    => '10',
            'height'   => '10'
        ),
        'b_spatial' => array(
            'position' => '58',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sqlhelp' => array(
            'position' => '59',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sql' => array(
            'position' => '60',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblanalyse' => array(
            'position' => '61',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblexport' => array(
            'position' => '62',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblimport' => array(
            'position' => '63',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblops' => array(
            'position' => '64',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tbloptimize' => array(
            'position' => '65',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tipp' => array(
            'position' => '66',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_trigger_add' => array(
            'position' => '67',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_triggers' => array(
            'position' => '68',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_unique' => array(
            'position' => '69',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usradd' => array(
            'position' => '70',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrcheck' => array(
            'position' => '71',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrdrop' => array(
            'position' => '72',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usredit' => array(
            'position' => '73',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrlist' => array(
            'position' => '74',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_view' => array(
            'position' => '75',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_views' => array(
            'position' => '76',
            'width'    => '16',
            'height'   => '16'
        ),
        'col_drop' => array(
            'position' => '77',
            'width'    => '16',
            'height'   => '16'
        ),
        'docs_menu_bg' => array(
            'position' => '78',
            'width'    => '2',
            'height'   => '2'
        ),
        'eye_grey' => array(
            'position' => '79',
            'width'    => '16',
            'height'   => '16'
        ),
        'eye' => array(
            'position' => '80',
            'width'    => '16',
            'height'   => '16'
        ),
        'item_ltr' => array(
            'position' => '81',
            'width'    => '5',
            'height'   => '9'
        ),
        'item_rtl' => array(
            'position' => '82',
            'width'    => '5',
            'height'   => '9'
        ),
        'more' => array(
            'position' => '83',
            'width'    => '13',
            'height'   => '16'
        ),
        'new_data_hovered' => array(
            'position' => '84',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data' => array(
            'position' => '85',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data_selected_hovered' => array(
            'position' => '86',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data_selected' => array(
            'position' => '87',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_hovered' => array(
            'position' => '88',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct' => array(
            'position' => '89',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_selected_hovered' => array(
            'position' => '90',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_selected' => array(
            'position' => '91',
            'width'    => '16',
            'height'   => '16'
        ),
        's_asci' => array(
            'position' => '92',
            'width'    => '16',
            'height'   => '16'
        ),
        's_asc' => array(
            'position' => '93',
            'width'    => '11',
            'height'   => '9'
        ),
        's_cancel' => array(
            'position' => '94',
            'width'    => '16',
            'height'   => '16'
        ),
        's_cog' => array(
            'position' => '95',
            'width'    => '16',
            'height'   => '16'
        ),
        's_db' => array(
            'position' => '96',
            'width'    => '16',
            'height'   => '16'
        ),
        's_desc' => array(
            'position' => '97',
            'width'    => '11',
            'height'   => '9'
        ),
        's_error2' => array(
            'position' => '98',
            'width'    => '11',
            'height'   => '11'
        ),
        's_error' => array(
            'position' => '99',
            'width'    => '16',
            'height'   => '16'
        ),
        's_host' => array(
            'position' => '100',
            'width'    => '16',
            'height'   => '16'
        ),
        's_lang' => array(
            'position' => '101',
            'width'    => '16',
            'height'   => '16'
        ),
        's_loggoff' => array(
            'position' => '102',
            'width'    => '16',
            'height'   => '16'
        ),
        's_notice' => array(
            'position' => '103',
            'width'    => '16',
            'height'   => '16'
        ),
        's_passwd' => array(
            'position' => '104',
            'width'    => '16',
            'height'   => '16'
        ),
        's_really' => array(
            'position' => '105',
            'width'    => '11',
            'height'   => '11'
        ),
        's_reload' => array(
            'position' => '106',
            'width'    => '16',
            'height'   => '16'
        ),
        's_replication' => array(
            'position' => '107',
            'width'    => '16',
            'height'   => '16'
        ),
        's_rights' => array(
            'position' => '108',
            'width'    => '16',
            'height'   => '16'
        ),
        's_sortable' => array(
            'position' => '109',
            'width'    => '11',
            'height'   => '15'
        ),
        's_status' => array(
            'position' => '110',
            'width'    => '16',
            'height'   => '16'
        ),
        's_success' => array(
            'position' => '111',
            'width'    => '16',
            'height'   => '16'
        ),
        's_sync' => array(
            'position' => '112',
            'width'    => '16',
            'height'   => '16'
        ),
        's_tbl' => array(
            'position' => '113',
            'width'    => '16',
            'height'   => '16'
        ),
        's_theme' => array(
            'position' => '114',
            'width'    => '16',
            'height'   => '16'
        ),
        's_vars' => array(
            'position' => '115',
            'width'    => '16',
            'height'   => '16'
        ),
        's_views' => array(
            'position' => '116',
            'width'    => '10',
            'height'   => '10'
        ),
        'window-new' => array(
            'position' => '117',
            'width'    => '16',
            'height'   => '16'
        ),
    );
}
?>
