<table class="noclick">
    <thead>
        <tr>
            <th><?= __('Storage Engine'); ?></th>
            <th><?= __('Description'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($engines as $engine => $details): ?>
            <tr class="
                <?= $details['Support'] == 'NO' || $details['Support'] == 'DISABLED' ? ' disabled' : ''; ?>
                <?= $details['Support'] == 'DEFAULT' ? ' marked' : ''; ?>">
                <td>
                    <a rel="newpage" href="server_engines.php<?= \PMA\libraries\URL::getCommon(array('engine' => $engine)); ?>">
                        <?= htmlspecialchars($details['Engine']); ?>
                    </a>
                </td>
                <td><?= htmlspecialchars($details['Comment']); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
