<table class="noclick">
    <thead>
        <tr>
            <th><?php echo __('Storage Engine'); ?></th>
            <th><?php echo __('Description'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $odd_row = true; ?>
        <?php foreach ($engines as $engine => $details): ?>
            <tr class="
                <?php echo $odd_row ? 'odd' : 'even'; ?>
                <?php echo $details['Support'] == 'NO' || $details['Support'] == 'DISABLED' ? ' disabled' : ''; ?>
                <?php echo $details['Support'] == 'DEFAULT' ? ' marked' : ''; ?>">
                <td>
                    <a rel="newpage" href="server_engines.php<?php echo PMA_URL_getCommon(array('engine' => $engine)); ?>">
                        <?php echo htmlspecialchars($details['Engine']); ?>
                    </a>
                </td>
                <td><?php echo htmlspecialchars($details['Comment']); ?></td>
            </tr>
            <?php $odd_row = !$odd_row; ?>
        <?php endforeach; ?>
    </tbody>
</table>
