<h2>
    <?= \PMA\libraries\Util::getImage('b_engine.png'),
            '    ', htmlspecialchars($title),
            '    ', \PMA\libraries\Util::showMySQLDocu($helpPage); ?>
</h2>
<p>
    <em>
        <?= htmlspecialchars($comment); ?>
    </em>
</p>
<?php if (! empty($infoPages) && is_array($infoPages)): ?>
    <p>
        <strong>[</strong>
            <?php if (empty($_REQUEST['page'])): ?>
                <strong><?= __('Variables'); ?></strong>
            <?php else: ?>
                <a href="server_engines.php<?= PMA_URL_getCommon(array('engine' => $_REQUEST['engine'])); ?>">
                    <?= __('Variables'); ?>
                </a>
            <?php endif; ?>
            <?php foreach ($infoPages as $current => $label): ?>
                <strong>|</strong>
                <?php if (isset($_REQUEST['page']) && $_REQUEST['page'] == $current): ?>
                    <strong><?= htmlspecialchars($label); ?></strong>
                <?php else: ?>
                    <a href="server_engines.php<?= PMA_URL_getCommon(array('engine' => $_REQUEST['engine'], 'page' => $current)); ?>">
                        <?= htmlspecialchars($label); ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        <strong>]</strong>
    </p>
<?php endif; ?>

<?php if (! empty($pageOutput)): ?>
    <?= $pageOutput; ?>
<?php else: ?>
    <p>
        <?= $support; ?>
    </p>
    <?= $variables; ?>
<?php endif; ?>