<div id="div_mysql_charset_collations">
    <table class="data noclick">
        <tr>
            <th id="collationHeader"><?php echo __('Collation'); ?></th>
            <th><?php echo __('Description'); ?></th>
        </tr>
        <?php foreach ($mysqlCharsets as $current_charset): ?>
            <tr>
                <th colspan="2" class="right">
                    <?php echo htmlspecialchars($current_charset); ?>
                    <?php if (! empty($mysqlCharsetsDesc[$current_charset])): ?>
                        (<i><?php echo htmlspecialchars($mysqlCharsetsDesc[$current_charset]); ?></i>)
                    <?php endif; ?>
                </th>
            </tr>
            <?php $odd_row = true; ?>
            <?php foreach ($mysqlCollations[$current_charset] as $current_collation): ?>
                <tr class="
                    <?php echo ($odd_row ? 'odd' : 'even'); ?>
                    <?php echo ($mysqlDftCollations[$current_charset] == $current_collation ? ' marked' : ''); ?>
                    <?php echo ($mysqlCollAvailable[$current_collation] ? '' : ' disabled'); ?>
                    ">
                    <td><?php echo htmlspecialchars($current_collation); ?></td>
                    <td><?php echo PMA_getCollationDescr($current_collation); ?></td>
                </tr>
                <?php $odd_row = ! $odd_row; ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </table>
</div>