<table>

<thead>
<tr>
<th colspan="4"><?= __('Define new aliases') ?></th>
</tr>
</thead>

<tr>
<td>
<label><?= __('Select database:') ?></label>
</td>
<td>
<select id="db_alias_select"><option value=""></option></select>
</td>
<td>
<input id="db_alias_name" placeholder="<?= __('New database name') ?>" disabled="1" />
</td>
<td>
<button id="db_alias_button" class="ui-button ui-corner-all ui-widget" disabled="1"><?= __('Add') ?></button>
</td>
</tr>

<tr>
<td>
<label><?= __('Select table:') ?></label>
</td>
<td>
<select id="table_alias_select"><option value=""></option></select>
</td>
<td>
<input id="table_alias_name" placeholder="<?= __('New table name') ?>" disabled="1" />
</td>
<td>
<button id="table_alias_button" class="ui-button ui-corner-all ui-widget" disabled="1"><?= __('Add') ?></button>
</td>
</tr>

<tr>
<td>
<label><?= __('Select column:') ?></label>
</td>
<td>
<select id="column_alias_select"><option value=""></option></select>
</td>
<td>
<input id="column_alias_name" placeholder="<?= __('New column name') ?>" disabled="1" />
</td>
<td>
<button id="column_alias_button" class="ui-button ui-corner-all ui-widget" disabled="1"><?= __('Add') ?></button>
</td>
</tr>

</table>
