<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * Holds the PhpMyAdmin\ThemeGenerator class
 *
 * @package PhpMyAdmin
 */
declare(strict_types=1);

namespace PhpMyAdmin;

use PhpMyAdmin\Sanitize;
use PhpMyAdmin\Template;
use PhpMyAdmin\Theme\Common;
use PhpMyAdmin\Theme\Layout;
use PhpMyAdmin\Theme\Navigation;

/**
 * Set of functions for Automated Theme Generator in phpMyAdmin
 *
 * @package PhpMyAdmin
 */
class ThemeGenerator
{

    /**
     * Colour Picker HTML file
     *
     * @return string HTML for the color picker tool
     */
    public function colorPicker()
    {
        $output = Template::get('theme_generator/color_picker')->render();
        return $output;
    }

    /**
     * File creation form
     *
     * @return string HTML for the form submission
     */
    public function form()
    {
        $output = Template::get('theme_generator/form')->render();
        return $output;
    }

    /**
     * Creates file structure
     *
     * @param array $post POST form data
     *
     * @return array $out generated file data
     */
    public function createFileStructure(array $post)
    {
        $out = array();
        $nav = new Navigation();
        $layout = new Layout();
        $common = new Common();
        $post['theme_name'] = Sanitize::sanitizeFilename($post['theme_name'], true);
        $name = $post['theme_name'];
        if (!is_dir("themes/" . $name)) {
            mkdir("themes/" . $name);
            mkdir("themes/" . $name . "/css");
        }
        $out['json'] = $this->createJsonFile($name);
        $common->createCommonFile($name);
        $out['layout'] = $layout->createLayoutFile($post);
        $nav->createNavigationFile($name);
        return $out;
    }

    /**
     * Creates theme.json
     *
     * @param string $name name of new theme
     *
     * @return string $txt JSON file data
     */
    public function createJsonFile($name)
    {
        $file = fopen("themes/" . $name . "/theme.json", "w");
        $txt = '{';
        $txt .= '"name": "' . $name . '",';
        $txt .= '"version": "5.0",';
        $txt .= '"description": "Theme Generated by Automated Theme Generator",';
        $txt .= '"author": "phpMyAdmin developers",';
        $txt .= '"url": "https://www.phpmyadmin.net/",';
        $txt .= '"supports": ["5.0"]';
        $txt .= '}';
        fwrite($file, $txt);
        fclose($file);
        return $txt;
    }
}

