<?php

declare(strict_types=1);

// phpcs:disable Generic.Files.LineLength.TooLong
return [
    // Queries
    [
        'name' => 'Uptime below one day',
        'formula' => 'Uptime',
        'test' => 'value < 86400',
        'issue' => 'Uptime is less than 1 day, performance tuning may not be accurate.',
        'recommendation' => 'To have more accurate averages it is recommended to let the server run for longer than a day before running this analyzer',
        'justification' => 'The uptime is only %s | ADVISOR_timespanFormat(Uptime)',
    ],
    [
        'name' => 'Questions below 1,000',
        'formula' => 'Questions',
        'test' => 'value < 1000',
        'issue' => 'Fewer than 1,000 questions have been run against this server. The recommendations may not be accurate.',
        'recommendation' => 'Let the server run for a longer time until it has executed a greater amount of queries.',
        'justification' => 'Current amount of Questions: %s | Questions',
    ],
    [
        'name' => 'Percentage of slow queries',
        'precondition' => 'Questions > 0',
        'formula' => 'Slow_queries / Questions * 100',
        'test' => 'value >= 5',
        'issue' => 'There is a lot of slow queries compared to the overall amount of Queries.',
        'recommendation' => 'You might want to increase {long_query_time} or optimize the queries listed in the slow query log',
        'justification' => 'The slow query rate should be below 5%, your value is %s%. | round(value,2)',
    ],
    [
        'name' => 'Slow query rate',
        'precondition' => 'Questions > 0',
        'formula' => '(Slow_queries / Questions * 100) / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'There is a high percentage of slow queries compared to the server uptime.',
        'recommendation' => 'You might want to increase {long_query_time} or optimize the queries listed in the slow query log',
        'justification' => 'You have a slow query rate of %s per hour, you should have less than 1% per hour. | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Long query time',
        'formula' => 'long_query_time',
        'test' => 'value >= 10',
        'issue' => '{long_query_time} is set to 10 seconds or more, thus only slow queries that take above 10 seconds are logged.',
        'recommendation' => 'It is suggested to set {long_query_time} to a lower value, depending on your environment. Usually a value of 1-5 seconds is suggested.',
        'justification' => 'long_query_time is currently set to %ds. | value',
    ],
    [
        'name' => 'Slow query logging',
        'precondition' => 'PMA_MYSQL_INT_VERSION < 50600',
        'formula' => 'log_slow_queries',
        'test' => 'value == \'OFF\'',
        'issue' => 'The slow query log is disabled.',
        'recommendation' => 'Enable slow query logging by setting {log_slow_queries} to \'ON\'. This will help troubleshooting badly performing queries.',
        'justification' => 'log_slow_queries is set to \'OFF\'',
    ],
    [
        'name' => 'Slow query logging',
        'precondition' => 'PMA_MYSQL_INT_VERSION >= 50600',
        'formula' => 'slow_query_log',
        'test' => 'value == \'OFF\'',
        'issue' => 'The slow query log is disabled.',
        'recommendation' => 'Enable slow query logging by setting {slow_query_log} to \'ON\'. This will help troubleshooting badly performing queries.',
        'justification' => 'slow_query_log is set to \'OFF\'',
    ],
    // Versions
    [
        'name' => 'Release Series',
        'formula' => 'version',
        'test' => 'substr(value,0,2) <= \'5.\' && substr(value,2,1) < 1',
        'issue' => 'The MySQL server version less than 5.1.',
        'recommendation' => 'You should upgrade, as MySQL 5.1 has improved performance, and MySQL 5.5 even more so.',
        'justification' => 'Current version: %s | value',
    ],
    [
        'name' => 'Minor Version',
        'precondition' => '! fired(\'Release Series\')',
        'formula' => 'version',
        'test' => 'substr(value,0,2) <= \'5.\' && substr(value,2,1) <= 1 && substr(value,4,2) < 30',
        'issue' => 'Version less than 5.1.30 (the first GA release of 5.1).',
        'recommendation' => 'You should upgrade, as recent versions of MySQL 5.1 have improved performance and MySQL 5.5 even more so.',
        'justification' => 'Current version: %s | value',
    ],
    [
        'name' => 'Minor Version',
        'precondition' => '! fired(\'Release Series\')',
        'formula' => 'version',
        'test' => 'substr(value,0,1) == 5 && substr(value,2,1) == 5 && substr(value,4,2) < 8',
        'issue' => 'Version less than 5.5.8 (the first GA release of 5.5).',
        'recommendation' => 'You should upgrade, to a stable version of MySQL 5.5.',
        'justification' => 'Current version: %s | value',
    ],
    [
        'name' => 'Distribution',
        'formula' => 'version_comment',
        'test' => 'preg_match(\'/source/i\',value)',
        'issue' => 'Version is compiled from source, not a MySQL official binary.',
        'recommendation' => 'If you did not compile from source, you may be using a package modified by a distribution. The MySQL manual only is accurate for official MySQL binaries, not any package distributions (such as RedHat, Debian/Ubuntu etc).',
        'justification' => '\'source\' found in version_comment',
    ],
    [
        'name' => 'Distribution',
        'formula' => 'version_comment',
        'test' => 'preg_match(\'/percona/i\',value)',
        'issue' => 'The MySQL manual only is accurate for official MySQL binaries.',
        'recommendation' => 'Percona documentation is at <a href="https://www.percona.com/software/documentation/">https://www.percona.com/software/documentation/</a>',
        'justification' => '\'percona\' found in version_comment',
    ],
    [
        'name' => 'MySQL Architecture',
        'formula' => 'system_memory',
        'test' => 'value > 3072*1024 && !preg_match(\'/64/\',version_compile_machine) && !preg_match(\'/64/\',version_compile_os)',
        'issue' => 'MySQL is not compiled as a 64-bit package.',
        'recommendation' => 'Your memory capacity is above 3 GiB (assuming the Server is on localhost), so MySQL might not be able to access all of your memory. You might want to consider installing the 64-bit version of MySQL.',
        'justification' => 'Available memory on this host: %s | ADVISOR_formatByteDown(value*1024, 2, 2)',
    ],
    // Query cache
    [
        'name' => 'Query caching method',
        'precondition' => '!fired(\'Query cache disabled\')',
        'formula' => 'Questions / Uptime',
        'test' => 'value > 100',
        'issue' => 'Suboptimal caching method.',
        'recommendation' => 'You are using the MySQL Query cache with a fairly high traffic database. It might be worth considering to use <a href="https://dev.mysql.com/doc/refman/5.6/en/ha-memcached.html">memcached</a> instead of the MySQL Query cache, especially if you have multiple slaves.',
        'justification' => 'The query cache is enabled and the server receives %d queries per second. This rule fires if there is more than 100 queries per second. | round(value,1)',
    ],
    // Sorts
    [
        'name' => 'Percentage of sorts that cause temporary tables',
        'precondition' => 'Sort_scan + Sort_range > 0',
        'formula' => 'Sort_merge_passes / (Sort_scan + Sort_range) * 100',
        'test' => 'value > 10',
        'issue' => 'Too many sorts are causing temporary tables.',
        'recommendation' => 'Consider increasing {sort_buffer_size} and/or {read_rnd_buffer_size}, depending on your system memory limits.',
        'justification' => '%s% of all sorts cause temporary tables, this value should be lower than 10%. | round(value,1)',
    ],
    [
        'name' => 'Rate of sorts that cause temporary tables',
        'formula' => 'Sort_merge_passes / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'Too many sorts are causing temporary tables.',
        'recommendation' => 'Consider increasing {sort_buffer_size} and/or {read_rnd_buffer_size}, depending on your system memory limits.',
        'justification' => 'Temporary tables average: %s, this value should be less than 1 per hour. | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Sort rows',
        'formula' => 'Sort_rows / Uptime',
        'test' => 'value * 60 >= 1',
        'issue' => 'There are lots of rows being sorted.',
        'recommendation' => 'While there is nothing wrong with a high amount of row sorting, you might want to make sure that the queries which require a lot of sorting use indexed columns in the ORDER BY clause, as this will result in much faster sorting.',
        'justification' => 'Sorted rows average: %s | ADVISOR_bytime(value,2)',
    ],
    // Joins, scans
    [
        'name' => 'Rate of joins without indexes',
        'formula' => '(Select_range_check + Select_scan + Select_full_join) / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'There are too many joins without indexes.',
        'recommendation' => 'This means that joins are doing full table scans. Adding indexes for the columns being used in the join conditions will greatly speed up table joins.',
        'justification' => 'Table joins average: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Rate of reading first index entry',
        'formula' => 'Handler_read_first / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'The rate of reading the first index entry is high.',
        'recommendation' => 'This usually indicates frequent full index scans. Full index scans are faster than table scans but require lots of CPU cycles in big tables, if those tables that have or had high volumes of UPDATEs and DELETEs, running \'OPTIMIZE TABLE\' might reduce the amount of and/or speed up full index scans. Other than that full index scans can only be reduced by rewriting queries.',
        'justification' => 'Index scans average: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Rate of reading fixed position',
        'formula' => 'Handler_read_rnd / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'The rate of reading data from a fixed position is high.',
        'recommendation' => 'This indicates that many queries need to sort results and/or do a full table scan, including join queries that do not use indexes. Add indexes where applicable.',
        'justification' => 'Rate of reading fixed position average: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Rate of reading next table row',
        'formula' => 'Handler_read_rnd_next / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'The rate of reading the next table row is high.',
        'recommendation' => 'This indicates that many queries are doing full table scans. Add indexes where applicable.',
        'justification' => 'Rate of reading next table row: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    // Temp tables
    [
        'name' => 'Different tmp_table_size and max_heap_table_size',
        'formula' => 'tmp_table_size - max_heap_table_size',
        'test' => 'value !=0',
        'issue' => '{tmp_table_size} and {max_heap_table_size} are not the same.',
        'recommendation' => 'If you have deliberately changed one of either: The server uses the lower value of either to determine the maximum size of in-memory tables. So if you wish to increase the in-memory table limit you will have to increase the other value as well.',
        'justification' => 'Current values are tmp_table_size: %s, max_heap_table_size: %s | ADVISOR_formatByteDown(tmp_table_size, 2, 2), ADVISOR_formatByteDown(max_heap_table_size, 2, 2)',
    ],
    [
        'name' => 'Percentage of temp tables on disk',
        'precondition' => 'Created_tmp_tables + Created_tmp_disk_tables > 0',
        'formula' => 'Created_tmp_disk_tables / (Created_tmp_tables + Created_tmp_disk_tables) * 100',
        'test' => 'value > 25',
        'issue' => 'Many temporary tables are being written to disk instead of being kept in memory.',
        'recommendation' => 'Increasing {max_heap_table_size} and {tmp_table_size} might help. However some temporary tables are always being written to disk, independent of the value of these variables. To eliminate these you will have to rewrite your queries to avoid those conditions (Within a temporary table: Presence of a BLOB or TEXT column or presence of a column bigger than 512 bytes) as mentioned in the beginning of an <a href="https://www.facebook.com/note.php?note_id=10150111255065841&comments">Article by the Pythian Group</a>',
        'justification' => '%s% of all temporary tables are being written to disk, this value should be below 25% | round(value,1)',
    ],
    [
        'name' => 'Temp disk rate',
        'precondition' => '!fired(\'Percentage of temp tables on disk\')',
        'formula' => 'Created_tmp_disk_tables / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'Many temporary tables are being written to disk instead of being kept in memory.',
        'recommendation' => 'Increasing {max_heap_table_size} and {tmp_table_size} might help. However some temporary tables are always being written to disk, independent of the value of these variables. To eliminate these you will have to rewrite your queries to avoid those conditions (Within a temporary table: Presence of a BLOB or TEXT column or presence of a column bigger than 512 bytes) as mentioned in the <a href="https://dev.mysql.com/doc/refman/8.0/en/internal-temporary-tables.html">MySQL Documentation</a>',
        'justification' => 'Rate of temporary tables being written to disk: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    // MyISAM index cache
    [
        'name' => 'MyISAM key buffer size',
        'formula' => 'key_buffer_size',
        'test' => 'value == 0',
        'issue' => 'Key buffer is not initialized. No MyISAM indexes will be cached.',
        'recommendation' => 'Set {key_buffer_size} depending on the size of your MyISAM indexes. 64M is a good start.',
        'justification' => 'key_buffer_size is 0',
    ],
    [
        'name' => 'Max % MyISAM key buffer ever used',
        'precondition' => 'key_buffer_size > 0',
        'formula' => 'Key_blocks_used * key_cache_block_size / key_buffer_size * 100',
        'test' => 'value < 95',
        'issue' => 'MyISAM key buffer (index cache) % used is low.',
        'recommendation' => 'You may need to decrease the size of {key_buffer_size}, re-examine your tables to see if indexes have been removed, or examine queries and expectations about what indexes are being used.',
        'justification' => 'max % MyISAM key buffer ever used: %s%, this value should be above 95% | round(value,1)',
    ],
    [
        'name' => 'Percentage of MyISAM key buffer used',
        // Don't fire if above rule fired - we don't need the same advice twice
        'precondition' => 'key_buffer_size > 0 && !fired(\'Max % MyISAM key buffer ever used\')',
        'formula' => '( 1 - Key_blocks_unused * key_cache_block_size / key_buffer_size) * 100',
        'test' => 'value < 95',
        'issue' => 'MyISAM key buffer (index cache) % used is low.',
        'recommendation' => 'You may need to decrease the size of {key_buffer_size}, re-examine your tables to see if indexes have been removed, or examine queries and expectations about what indexes are being used.',
        'justification' => '% MyISAM key buffer used: %s%, this value should be above 95% | round(value,1)',
    ],
    [
        'name' => 'Percentage of index reads from memory',
        'precondition' => 'Key_read_requests > 0',
        'formula' => '100 - (Key_reads / Key_read_requests * 100)',
        'test' => 'value < 95',
        'issue' => 'The % of indexes that use the MyISAM key buffer is low.',
        'recommendation' => 'You may need to increase {key_buffer_size}.',
        'justification' => 'Index reads from memory: %s%, this value should be above 95% | round(value,1)',
    ],
    // Other caches
    [
        'name' => 'Rate of table open',
        'formula' => 'Opened_tables / Uptime',
        'test' => 'value*60*60 > 10',
        'issue' => 'The rate of opening tables is high.',
        'recommendation' => 'Opening tables requires disk I/O which is costly. Increasing {table_open_cache} might avoid this.',
        'justification' => 'Opened table rate: %s, this value should be less than 10 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Percentage of used open files limit',
        'formula' => 'Open_files / open_files_limit * 100',
        'test' => 'value > 85',
        'issue' => 'The number of open files is approaching the max number of open files.  You may get a "Too many open files" error.',
        'recommendation' => 'Consider increasing {open_files_limit}, and check the error log when restarting after changing {open_files_limit}.',
        'justification' => 'The number of opened files is at %s% of the limit. It should be below 85% | round(value,1)',
    ],
    [
        'name' => 'Rate of open files',
        'formula' => 'Open_files / Uptime',
        'test' => 'value * 60 * 60 > 5',
        'issue' => 'The rate of opening files is high.',
        'recommendation' => 'Consider increasing {open_files_limit}, and check the error log when restarting after changing {open_files_limit}.',
        'justification' => 'Opened files rate: %s, this value should be less than 5 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Immediate table locks %',
        'precondition' => 'Table_locks_waited + Table_locks_immediate > 0',
        'formula' => 'Table_locks_immediate / (Table_locks_waited + Table_locks_immediate) * 100',
        'test' => 'value < 95',
        'issue' => 'Too many table locks were not granted immediately.',
        'recommendation' => 'Optimize queries and/or use InnoDB to reduce lock wait.',
        'justification' => 'Immediate table locks: %s%, this value should be above 95% | round(value,1)',
    ],
    [
        'name' => 'Table lock wait rate',
        'formula' => 'Table_locks_waited / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'Too many table locks were not granted immediately.',
        'recommendation' => 'Optimize queries and/or use InnoDB to reduce lock wait.',
        'justification' => 'Table lock wait rate: %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Thread cache',
        'formula' => 'thread_cache_size',
        'test' => 'value < 1',
        'issue' => 'Thread cache is disabled, resulting in more overhead from new connections to MySQL.',
        'recommendation' => 'Enable the thread cache by setting {thread_cache_size} > 0.',
        'justification' => 'The thread cache is set to 0',
    ],
    [
        'name' => 'Thread cache hit rate %',
        'precondition' => 'thread_cache_size > 0',
        'formula' => '100 - Threads_created / Connections',
        'test' => 'value < 80',
        'issue' => 'Thread cache is not efficient.',
        'recommendation' => 'Increase {thread_cache_size}.',
        'justification' => 'Thread cache hitrate: %s%, this value should be above 80% | round(value,1)',
    ],
    [
        'name' => 'Threads that are slow to launch',
        'precondition' => 'slow_launch_time > 0',
        'formula' => 'Slow_launch_threads',
        'test' => 'value > 0',
        'issue' => 'There are too many threads that are slow to launch.',
        'recommendation' => 'This generally happens in case of general system overload as it is pretty simple operations. You might want to monitor your system load carefully.',
        'justification' => '%s thread(s) took longer than %s seconds to start, it should be 0 | value, slow_launch_time',
    ],
    [
        'name' => 'Slow launch time',
        'formula' => 'slow_launch_time',
        'test' => 'value > 2',
        'issue' => 'Slow_launch_time is above 2s.',
        'recommendation' => 'Set {slow_launch_time} to 1s or 2s to correctly count threads that are slow to launch.',
        'justification' => 'slow_launch_time is set to %s | value',
    ],
    // Connections
    [
        'name' => 'Percentage of used connections',
        'formula' => 'Max_used_connections / max_connections * 100',
        'test' => 'value > 80',
        'issue' => 'The maximum amount of used connections is getting close to the value of {max_connections}.',
        'recommendation' => 'Increase {max_connections}, or decrease {wait_timeout} so that connections that do not close database handlers properly get killed sooner. Make sure the code closes database handlers properly.',
        'justification' => 'Max_used_connections is at %s% of max_connections, it should be below 80% | round(value,1)',
    ],
    [
        'name' => 'Percentage of aborted connections',
        'formula' => 'Aborted_connects / Connections * 100',
        'test' => 'value > 1',
        'issue' => 'Too many connections are aborted.',
        'recommendation' => 'Connections are usually aborted when they cannot be authorized. <a href="https://www.percona.com/blog/2008/08/23/how-to-track-down-the-source-of-aborted_connects/">This article</a> might help you track down the source.',
        'justification' => '%s% of all connections are aborted. This value should be below 1% | round(value,1)',
    ],
    [
        'name' => 'Rate of aborted connections',
        'formula' => 'Aborted_connects / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'Too many connections are aborted.',
        'recommendation' => 'Connections are usually aborted when they cannot be authorized. <a href="https://www.percona.com/blog/2008/08/23/how-to-track-down-the-source-of-aborted_connects/">This article</a> might help you track down the source.',
        'justification' => 'Aborted connections rate is at %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    [
        'name' => 'Percentage of aborted clients',
        'formula' => 'Aborted_clients / Connections * 100',
        'test' => 'value > 2',
        'issue' => 'Too many clients are aborted.',
        'recommendation' => 'Clients are usually aborted when they did not close their connection to MySQL properly. This can be due to network issues or code not closing a database handler properly. Check your network and code.',
        'justification' => '%s% of all clients are aborted. This value should be below 2% | round(value,1)',
    ],
    [
        'name' => 'Rate of aborted clients',
        'formula' => 'Aborted_clients / Uptime',
        'test' => 'value * 60 * 60 > 1',
        'issue' => 'Too many clients are aborted.',
        'recommendation' => 'Clients are usually aborted when they did not close their connection to MySQL properly. This can be due to network issues or code not closing a database handler properly. Check your network and code.',
        'justification' => 'Aborted client rate is at %s, this value should be less than 1 per hour | ADVISOR_bytime(value,2)',
    ],
    // InnoDB
    [
        'name' => 'Is InnoDB disabled?',
        'precondition' => 'PMA_MYSQL_INT_VERSION < 50600',
        'formula' => 'have_innodb',
        'test' => 'value != "YES"',
        'issue' => 'You do not have InnoDB enabled.',
        'recommendation' => 'InnoDB is usually the better choice for table engines.',
        'justification' => 'have_innodb is set to \'value\'',
    ],
    [
        'name' => 'InnoDB log size',
        'precondition' => 'innodb_buffer_pool_size > 0',
        'formula' => '(innodb_log_file_size * innodb_log_files_in_group)/ innodb_buffer_pool_size * 100',
        'test' => 'value < 20 && innodb_log_file_size / (1024 * 1024) < 256',
        'issue' => 'The InnoDB log file size is not an appropriate size, in relation to the InnoDB buffer pool.',
        'recommendation' => 'Especially on a system with a lot of writes to InnoDB tables you should set {innodb_log_file_size} to 25% of {innodb_buffer_pool_size}. However the bigger this value, the longer the recovery time will be when database crashes, so this value should not be set much higher than 256 MiB. Please note however that you cannot simply change the value of this variable. You need to shutdown the server, remove the InnoDB log files, set the new value in my.cnf, start the server, then check the error logs if everything went fine. See also <a href="https://mysqldatabaseadministration.blogspot.com/2007/01/increase-innodblogfilesize-proper-way.html">this blog entry</a>',
        'justification' => 'Your InnoDB log size is at %s% in relation to the InnoDB buffer pool size, it should not be below 20% | round(value,1)',
    ],
    [
        'name' => 'Max InnoDB log size',
        'precondition' => 'innodb_buffer_pool_size > 0 && innodb_log_file_size / innodb_buffer_pool_size * 100 < 30',
        'formula' => 'innodb_log_file_size / (1024 * 1024)',
        'test' => 'value > 256',
        'issue' => 'The InnoDB log file size is inadequately large.',
        'recommendation' => 'It is usually sufficient to set {innodb_log_file_size} to 25% of the size of {innodb_buffer_pool_size}. A very big {innodb_log_file_size} slows down the recovery time after a database crash considerably. See also <a href="https://www.percona.com/blog/2006/07/03/choosing-proper-innodb_log_file_size/">this Article</a>. You need to shutdown the server, remove the InnoDB log files, set the new value in my.cnf, start the server, then check the error logs if everything went fine. See also <a href="https://mysqldatabaseadministration.blogspot.com/2007/01/increase-innodblogfilesize-proper-way.html">this blog entry</a>',
        'justification' => 'Your absolute InnoDB log size is %s MiB | round(value,1)',
    ],
    [
        'name' => 'InnoDB buffer pool size',
        'precondition' => 'system_memory > 0',
        'formula' => 'innodb_buffer_pool_size / system_memory * 100',
        'test' => 'value < 60',
        'issue' => 'Your InnoDB buffer pool is fairly small.',
        'recommendation' => 'The InnoDB buffer pool has a profound impact on performance for InnoDB tables. Assign all your remaining memory to this buffer. For database servers that use solely InnoDB as storage engine and have no other services (e.g. a web server) running, you may set this as high as 80% of your available memory. If that is not the case, you need to carefully assess the memory consumption of your other services and non-InnoDB-Tables and set this variable accordingly. If it is set too high, your system will start swapping, which decreases performance significantly. See also <a href="https://www.percona.com/blog/2007/11/03/choosing-innodb_buffer_pool_size/">this article</a>',
        'justification' => 'You are currently using %s% of your memory for the InnoDB buffer pool. This rule fires if you are assigning less than 60%, however this might be perfectly adequate for your system if you don\'t have much InnoDB tables or other services running on the same machine. | value',
    ],
    // Other
    [
        'name' => 'MyISAM concurrent inserts',
        'formula' => 'concurrent_insert',
        'test' => 'value === 0 || value === \'NEVER\'',
        'issue' => 'Enable {concurrent_insert} by setting it to 1',
        'recommendation' => 'Setting {concurrent_insert} to 1 reduces contention between readers and writers for a given table. See also <a href="https://dev.mysql.com/doc/refman/5.5/en/concurrent-inserts.html">MySQL Documentation</a>',
        'justification' => 'concurrent_insert is set to 0',
    ],
];
