<?php

declare(strict_types=1);

return [
    [
        'name' => 49,
        'formula' => 50,
        'test' => 51,
        'issue' => 52,
        'recommendation' => 53,
        'justification' => 54,
    ],
    [
        'name' => 56,
        'formula' => 57,
        'test' => 58,
        'issue' => 59,
        'recommendation' => 60,
        'justification' => 61,
    ],
    [
        'name' => 63,
        'precondition' => 63,
        'formula' => 64,
        'test' => 65,
        'issue' => 66,
        'recommendation' => 67,
        'justification' => 68,
    ],
    [
        'name' => 70,
        'precondition' => 70,
        'formula' => 71,
        'test' => 72,
        'issue' => 73,
        'recommendation' => 74,
        'justification' => 75,
    ],
    [
        'name' => 77,
        'formula' => 78,
        'test' => 79,
        'issue' => 80,
        'recommendation' => 81,
        'justification' => 82,
    ],
    [
        'name' => 84,
        'precondition' => 84,
        'formula' => 85,
        'test' => 86,
        'issue' => 87,
        'recommendation' => 88,
        'justification' => 89,
    ],
    [
        'name' => 91,
        'precondition' => 91,
        'formula' => 92,
        'test' => 93,
        'issue' => 94,
        'recommendation' => 95,
        'justification' => 96,
    ],
    [
        'name' => 100,
        'formula' => 101,
        'test' => 102,
        'issue' => 103,
        'recommendation' => 104,
        'justification' => 105,
    ],
    [
        'name' => 107,
        'precondition' => 107,
        'formula' => 108,
        'test' => 109,
        'issue' => 110,
        'recommendation' => 111,
        'justification' => 112,
    ],
    [
        'name' => 114,
        'precondition' => 114,
        'formula' => 115,
        'test' => 116,
        'issue' => 117,
        'recommendation' => 118,
        'justification' => 119,
    ],
    [
        'name' => 121,
        'formula' => 122,
        'test' => 123,
        'issue' => 124,
        'recommendation' => 125,
        'justification' => 126,
    ],
    [
        'name' => 128,
        'formula' => 129,
        'test' => 130,
        'issue' => 131,
        'recommendation' => 132,
        'justification' => 133,
    ],
    [
        'name' => 135,
        'formula' => 136,
        'test' => 137,
        'issue' => 138,
        'recommendation' => 139,
        'justification' => 140,
    ],
    [
        'name' => 145,
        'precondition' => 145,
        'formula' => 146,
        'test' => 147,
        'issue' => 148,
        'recommendation' => 149,
        'justification' => 150,
    ],
    [
        'name' => 154,
        'precondition' => 154,
        'formula' => 155,
        'test' => 156,
        'issue' => 157,
        'recommendation' => 158,
        'justification' => 159,
    ],
    [
        'name' => 161,
        'formula' => 162,
        'test' => 163,
        'issue' => 164,
        'recommendation' => 165,
        'justification' => 166,
    ],
    [
        'name' => 168,
        'formula' => 169,
        'test' => 170,
        'issue' => 171,
        'recommendation' => 172,
        'justification' => 173,
    ],
    [
        'name' => 176,
        'formula' => 177,
        'test' => 178,
        'issue' => 179,
        'recommendation' => 180,
        'justification' => 181,
    ],
    [
        'name' => 183,
        'formula' => 184,
        'test' => 185,
        'issue' => 186,
        'recommendation' => 187,
        'justification' => 188,
    ],
    [
        'name' => 190,
        'formula' => 191,
        'test' => 192,
        'issue' => 193,
        'recommendation' => 194,
        'justification' => 195,
    ],
    [
        'name' => 197,
        'formula' => 198,
        'test' => 199,
        'issue' => 200,
        'recommendation' => 201,
        'justification' => 202,
    ],
    [
        'name' => 205,
        'formula' => 206,
        'test' => 207,
        'issue' => 208,
        'recommendation' => 209,
        'justification' => 210,
    ],
    [
        'name' => 212,
        'precondition' => 212,
        'formula' => 213,
        'test' => 214,
        'issue' => 215,
        'recommendation' => 216,
        'justification' => 217,
    ],
    [
        'name' => 219,
        'precondition' => 219,
        'formula' => 220,
        'test' => 221,
        'issue' => 222,
        'recommendation' => 223,
        'justification' => 224,
    ],
    [
        'name' => 228,
        'formula' => 229,
        'test' => 230,
        'issue' => 231,
        'recommendation' => 232,
        'justification' => 233,
    ],
    [
        'name' => 235,
        'precondition' => 235,
        'formula' => 236,
        'test' => 237,
        'issue' => 238,
        'recommendation' => 239,
        'justification' => 240,
    ],
    [
        'name' => 243,
        'precondition' => 243,
        'formula' => 244,
        'test' => 245,
        'issue' => 246,
        'recommendation' => 247,
        'justification' => 248,
    ],
    [
        'name' => 250,
        'precondition' => 250,
        'formula' => 251,
        'test' => 252,
        'issue' => 253,
        'recommendation' => 254,
        'justification' => 255,
    ],
    [
        'name' => 259,
        'formula' => 260,
        'test' => 261,
        'issue' => 262,
        'recommendation' => 263,
        'justification' => 264,
    ],
    [
        'name' => 266,
        'formula' => 267,
        'test' => 268,
        'issue' => 269,
        'recommendation' => 270,
        'justification' => 271,
    ],
    [
        'name' => 273,
        'formula' => 274,
        'test' => 275,
        'issue' => 276,
        'recommendation' => 277,
        'justification' => 278,
    ],
    [
        'name' => 280,
        'precondition' => 280,
        'formula' => 281,
        'test' => 282,
        'issue' => 283,
        'recommendation' => 284,
        'justification' => 285,
    ],
    [
        'name' => 287,
        'formula' => 288,
        'test' => 289,
        'issue' => 290,
        'recommendation' => 291,
        'justification' => 292,
    ],
    [
        'name' => 294,
        'formula' => 295,
        'test' => 296,
        'issue' => 297,
        'recommendation' => 298,
        'justification' => 299,
    ],
    [
        'name' => 301,
        'precondition' => 301,
        'formula' => 302,
        'test' => 303,
        'issue' => 304,
        'recommendation' => 305,
        'justification' => 306,
    ],
    [
        'name' => 308,
        'precondition' => 308,
        'formula' => 309,
        'test' => 310,
        'issue' => 311,
        'recommendation' => 312,
        'justification' => 313,
    ],
    [
        'name' => 315,
        'formula' => 316,
        'test' => 317,
        'issue' => 318,
        'recommendation' => 319,
        'justification' => 320,
    ],
    [
        'name' => 324,
        'formula' => 325,
        'test' => 326,
        'issue' => 327,
        'recommendation' => 328,
        'justification' => 329,
    ],
    [
        'name' => 331,
        'formula' => 332,
        'test' => 333,
        'issue' => 334,
        'recommendation' => 335,
        'justification' => 336,
    ],
    [
        'name' => 338,
        'formula' => 339,
        'test' => 340,
        'issue' => 341,
        'recommendation' => 342,
        'justification' => 343,
    ],
    [
        'name' => 345,
        'formula' => 346,
        'test' => 347,
        'issue' => 348,
        'recommendation' => 349,
        'justification' => 350,
    ],
    [
        'name' => 352,
        'formula' => 353,
        'test' => 354,
        'issue' => 355,
        'recommendation' => 356,
        'justification' => 357,
    ],
    [
        'name' => 361,
        'precondition' => 361,
        'formula' => 362,
        'test' => 363,
        'issue' => 364,
        'recommendation' => 365,
        'justification' => 366,
    ],
    [
        'name' => 368,
        'precondition' => 368,
        'formula' => 369,
        'test' => 370,
        'issue' => 371,
        'recommendation' => 372,
        'justification' => 373,
    ],
    [
        'name' => 375,
        'precondition' => 375,
        'formula' => 376,
        'test' => 377,
        'issue' => 378,
        'recommendation' => 379,
        'justification' => 380,
    ],
    [
        'name' => 382,
        'precondition' => 382,
        'formula' => 383,
        'test' => 384,
        'issue' => 385,
        'recommendation' => 386,
        'justification' => 387,
    ],
    [
        'name' => 391,
        'formula' => 392,
        'test' => 393,
        'issue' => 394,
        'recommendation' => 395,
        'justification' => 396,
    ],
];
