<?php
/**
 * AUTOGENERATED CONTENT - DO NOT EDIT!
 * ALL CHANGES WILL BE UNDONE!
 * RUN `./scripts/generate-sprites` TO UPDATE THIS FILE
 *
 * @package PhpMyAdmin-theme
 */

/**
 * Returns map of sprites inside sprite.png
 *
 * @return array Data of sprites
 */
function PMA_sprites()
{
    return array(
        'asc_order' => array(
            'position' => '1',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_bookmark' => array(
            'position' => '2',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_browse' => array(
            'position' => '3',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_calendar' => array(
            'position' => '4',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_chart' => array(
            'position' => '5',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_close' => array(
            'position' => '6',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_column_add' => array(
            'position' => '7',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_comment' => array(
            'position' => '8',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_dbstatistics' => array(
            'position' => '9',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_deltbl' => array(
            'position' => '10',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_docs' => array(
            'position' => '11',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_docsql' => array(
            'position' => '12',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_drop' => array(
            'position' => '13',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_edit' => array(
            'position' => '14',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_empty' => array(
            'position' => '15',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_engine' => array(
            'position' => '16',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_event_add' => array(
            'position' => '17',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_events' => array(
            'position' => '18',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_export' => array(
            'position' => '19',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_favorite' => array(
            'position' => '20',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_find_replace' => array(
            'position' => '21',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_firstpage' => array(
            'position' => '22',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_ftext' => array(
            'position' => '23',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_group' => array(
            'position' => '24',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_help' => array(
            'position' => '25',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_home' => array(
            'position' => '26',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_import' => array(
            'position' => '27',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_index' => array(
            'position' => '28',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_index_add' => array(
            'position' => '29',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_info' => array(
            'position' => '30',
            'width'    => '11',
            'height'   => '11'
        ),
        'b_inline_edit' => array(
            'position' => '31',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_insrow' => array(
            'position' => '32',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_lastpage' => array(
            'position' => '33',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_minus' => array(
            'position' => '34',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_more' => array(
            'position' => '35',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_move' => array(
            'position' => '36',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_newdb' => array(
            'position' => '37',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_newtbl' => array(
            'position' => '38',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_nextpage' => array(
            'position' => '39',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_no_favorite' => array(
            'position' => '40',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_pdfdoc' => array(
            'position' => '41',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_plus' => array(
            'position' => '42',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_prevpage' => array(
            'position' => '43',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_primary' => array(
            'position' => '44',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_print' => array(
            'position' => '45',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_props' => array(
            'position' => '46',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_relations' => array(
            'position' => '47',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_report' => array(
            'position' => '48',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_routine_add' => array(
            'position' => '49',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_routines' => array(
            'position' => '50',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_save' => array(
            'position' => '51',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_saveimage' => array(
            'position' => '52',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sbrowse' => array(
            'position' => '53',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sdb' => array(
            'position' => '54',
            'width'    => '10',
            'height'   => '10'
        ),
        'b_search' => array(
            'position' => '55',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_selboard' => array(
            'position' => '56',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_select' => array(
            'position' => '57',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_snewtbl' => array(
            'position' => '58',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_spatial' => array(
            'position' => '59',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sql' => array(
            'position' => '60',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sqldoc' => array(
            'position' => '61',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_sqlhelp' => array(
            'position' => '62',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_table_add' => array(
            'position' => '63',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblanalyse' => array(
            'position' => '64',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblexport' => array(
            'position' => '65',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblimport' => array(
            'position' => '66',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tblops' => array(
            'position' => '67',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tbloptimize' => array(
            'position' => '68',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_tipp' => array(
            'position' => '69',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_trigger_add' => array(
            'position' => '70',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_triggers' => array(
            'position' => '71',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_undo' => array(
            'position' => '72',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_unique' => array(
            'position' => '73',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usradd' => array(
            'position' => '74',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrcheck' => array(
            'position' => '75',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrdrop' => array(
            'position' => '76',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usredit' => array(
            'position' => '77',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_usrlist' => array(
            'position' => '78',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_versions' => array(
            'position' => '79',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_view' => array(
            'position' => '80',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_view_add' => array(
            'position' => '81',
            'width'    => '16',
            'height'   => '16'
        ),
        'b_views' => array(
            'position' => '82',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_browse' => array(
            'position' => '83',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_deltbl' => array(
            'position' => '84',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_drop' => array(
            'position' => '85',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_edit' => array(
            'position' => '86',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_empty' => array(
            'position' => '87',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_export' => array(
            'position' => '88',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_firstpage' => array(
            'position' => '89',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_ftext' => array(
            'position' => '90',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_index' => array(
            'position' => '91',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_insrow' => array(
            'position' => '92',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_lastpage' => array(
            'position' => '93',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_nextpage' => array(
            'position' => '94',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_prevpage' => array(
            'position' => '95',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_primary' => array(
            'position' => '96',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_routine_add' => array(
            'position' => '97',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_sbrowse' => array(
            'position' => '98',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_select' => array(
            'position' => '99',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_spatial' => array(
            'position' => '100',
            'width'    => '16',
            'height'   => '16'
        ),
        'bd_unique' => array(
            'position' => '101',
            'width'    => '16',
            'height'   => '16'
        ),
        'centralColumns' => array(
            'position' => '102',
            'width'    => '16',
            'height'   => '16'
        ),
        'centralColumns_add' => array(
            'position' => '103',
            'width'    => '16',
            'height'   => '16'
        ),
        'centralColumns_delete' => array(
            'position' => '104',
            'width'    => '16',
            'height'   => '16'
        ),
        'col_drop' => array(
            'position' => '105',
            'width'    => '16',
            'height'   => '16'
        ),
        'console' => array(
            'position' => '106',
            'width'    => '16',
            'height'   => '16'
        ),
        'database' => array(
            'position' => '107',
            'width'    => '16',
            'height'   => '16'
        ),
        'eye' => array(
            'position' => '108',
            'width'    => '16',
            'height'   => '16'
        ),
        'eye_grey' => array(
            'position' => '109',
            'width'    => '16',
            'height'   => '16'
        ),
        'item' => array(
            'position' => '110',
            'width'    => '9',
            'height'   => '9'
        ),
        'lightbulb' => array(
            'position' => '111',
            'width'    => '16',
            'height'   => '16'
        ),
        'lightbulb_off' => array(
            'position' => '112',
            'width'    => '16',
            'height'   => '16'
        ),
        'more' => array(
            'position' => '113',
            'width'    => '13',
            'height'   => '16'
        ),
        'new_data' => array(
            'position' => '114',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data_hovered' => array(
            'position' => '115',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data_selected' => array(
            'position' => '116',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_data_selected_hovered' => array(
            'position' => '117',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct' => array(
            'position' => '118',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_hovered' => array(
            'position' => '119',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_selected' => array(
            'position' => '120',
            'width'    => '16',
            'height'   => '16'
        ),
        'new_struct_selected_hovered' => array(
            'position' => '121',
            'width'    => '16',
            'height'   => '16'
        ),
        'normalize' => array(
            'position' => '122',
            'width'    => '16',
            'height'   => '16'
        ),
        'pause' => array(
            'position' => '123',
            'width'    => '16',
            'height'   => '16'
        ),
        'php_sym' => array(
            'position' => '124',
            'width'    => '16',
            'height'   => '16'
        ),
        'play' => array(
            'position' => '125',
            'width'    => '16',
            'height'   => '16'
        ),
        's_asc' => array(
            'position' => '126',
            'width'    => '16',
            'height'   => '16'
        ),
        's_asci' => array(
            'position' => '127',
            'width'    => '16',
            'height'   => '16'
        ),
        's_attention' => array(
            'position' => '128',
            'width'    => '16',
            'height'   => '16'
        ),
        's_cancel' => array(
            'position' => '129',
            'width'    => '16',
            'height'   => '16'
        ),
        's_cancel2' => array(
            'position' => '130',
            'width'    => '16',
            'height'   => '16'
        ),
        's_cog' => array(
            'position' => '131',
            'width'    => '16',
            'height'   => '16'
        ),
        's_db' => array(
            'position' => '132',
            'width'    => '16',
            'height'   => '16'
        ),
        's_desc' => array(
            'position' => '133',
            'width'    => '16',
            'height'   => '16'
        ),
        's_error' => array(
            'position' => '134',
            'width'    => '16',
            'height'   => '16'
        ),
        's_error2' => array(
            'position' => '135',
            'width'    => '11',
            'height'   => '11'
        ),
        's_host' => array(
            'position' => '136',
            'width'    => '16',
            'height'   => '16'
        ),
        's_info' => array(
            'position' => '137',
            'width'    => '16',
            'height'   => '16'
        ),
        's_lang' => array(
            'position' => '138',
            'width'    => '16',
            'height'   => '16'
        ),
        's_link' => array(
            'position' => '139',
            'width'    => '16',
            'height'   => '16'
        ),
        's_lock' => array(
            'position' => '140',
            'width'    => '16',
            'height'   => '16'
        ),
        's_loggoff' => array(
            'position' => '141',
            'width'    => '16',
            'height'   => '16'
        ),
        's_notice' => array(
            'position' => '142',
            'width'    => '16',
            'height'   => '16'
        ),
        's_okay' => array(
            'position' => '143',
            'width'    => '16',
            'height'   => '16'
        ),
        's_passwd' => array(
            'position' => '144',
            'width'    => '16',
            'height'   => '16'
        ),
        's_process' => array(
            'position' => '145',
            'width'    => '16',
            'height'   => '16'
        ),
        's_really' => array(
            'position' => '146',
            'width'    => '11',
            'height'   => '11'
        ),
        's_reload' => array(
            'position' => '147',
            'width'    => '16',
            'height'   => '16'
        ),
        's_replication' => array(
            'position' => '148',
            'width'    => '16',
            'height'   => '16'
        ),
        's_rights' => array(
            'position' => '149',
            'width'    => '16',
            'height'   => '16'
        ),
        's_sortable' => array(
            'position' => '150',
            'width'    => '16',
            'height'   => '16'
        ),
        's_status' => array(
            'position' => '151',
            'width'    => '16',
            'height'   => '16'
        ),
        's_success' => array(
            'position' => '152',
            'width'    => '16',
            'height'   => '16'
        ),
        's_sync' => array(
            'position' => '153',
            'width'    => '16',
            'height'   => '16'
        ),
        's_tbl' => array(
            'position' => '154',
            'width'    => '16',
            'height'   => '16'
        ),
        's_theme' => array(
            'position' => '155',
            'width'    => '16',
            'height'   => '16'
        ),
        's_top' => array(
            'position' => '156',
            'width'    => '16',
            'height'   => '16'
        ),
        's_unlink' => array(
            'position' => '157',
            'width'    => '16',
            'height'   => '16'
        ),
        's_vars' => array(
            'position' => '158',
            'width'    => '16',
            'height'   => '16'
        ),
        's_views' => array(
            'position' => '159',
            'width'    => '16',
            'height'   => '16'
        ),
        'window-new' => array(
            'position' => '160',
            'width'    => '16',
            'height'   => '16'
        ),
    );
}
?>
