<input type="hidden" name="dbname" value="<?= htmlspecialchars($database); ?>"/>

<label for="text_routinename"><?= __('Add privileges on the following routine:'); ?></label>

<?php if (! empty($routines)) : ?>
    <select name="pred_routinename" class="autosubmit">
        <option value="" selected="selected"><?= __('Use text field'); ?>:</option>
        <?php foreach ($routines as $routine) : ?>
            <option value="<?= htmlspecialchars($routine); ?>"><?= htmlspecialchars($routine); ?></option>
        <?php endforeach; ?>
    </select>
<?php endif; ?>

<input type="text" id="text_routinename" name="routinename" />