<fieldset id="fieldset_delete_user">
    <legend>
        <?= PMA\libraries\Util::getIcon('b_usrdrop.png')?><?= __('Remove selected user accounts') ?>
    </legend>
    <input type="hidden" name="mode" value="2" />
    ( <?= __('Revoke all active privileges from the users and delete them afterwards.') ?> )
    <br />
    <input type="checkbox" title="<?= __('Drop the databases that have the same names as the users.') ?>"
        name="drop_users_db" id="checkbox_drop_users_db" />
    <label for="checkbox_drop_users_db" title=<?= __('Drop the databases that have the same names as the users.')?> >
        <?= __('Drop the databases that have the same names as the users.') ?>
    </label>
</fieldset>

<fieldset id="fieldset_delete_user_footer" class="tblFooters">
    <input type="submit" name="delete" value="<?= __('Go') ?>" id="buttonGo" class="ajax" />
</fieldset>
