<div id="edit_user_dialog">
    <?= $header; ?>
    <form class="submenu-item" name="usersForm" id="addUsersForm" action="server_privileges.php" method="post">
        <?= PMA_URL_getHiddenInputs(); ?>
        <input type="hidden" name="username" value="<?= htmlspecialchars($username); ?>">
        <input type="hidden" name="hostname" value="<?= htmlspecialchars($hostname); ?>">
        <input type="hidden" name="dbname" value="<?= htmlspecialchars($database); ?>">
        <input type="hidden" name="routinename" value="<?= htmlspecialchars($routine); ?>">
        <input type="hidden" name="grant_count" value="<?= $grantCount; ?>">
        <fieldset id="fieldset_user_global_rights">
            <legend data-submenu-label="<?= __('Routine')?>">
                <?= __('Routine-specific privileges'); ?>
            </legend>
            <p>
                <small>
                    <i><?= __('Note: MySQL privilege names are expressed in English.'); ?></i>
                </small>
            </p>
            <?= $privCheckboxes; ?>
        </fieldset>
        <fieldset id="fieldset_user_privtable_footer" class="tblFooters">
            <input type="hidden" name="update_privs" value="1">
            <input type="submit" value="Go">
        </fieldset>
    </form>
</div>