<fieldset>
    <legend>SSL</legend>
    <div id="require_ssl_div">
        <?php foreach ($require_options as $require_option) : ?>
            <?php if ($require_option['name'] === 'ssl_cipher') : ?>
                <div id="specified_div" style="padding-left:20px;">
            <?php endif; ?>
            <?=
                PMA\libraries\Template::get('privileges/require_options_item')->render(
                    array('require_option' => $require_option)
                );
            ?>
        <?php endforeach; ?>
        </div> <!-- END specified_div -->
    </div> <!-- END require_ssl_div -->
</fieldset>