<fieldset>
    <legend><?= __('Resource limits') ?></legend>
    <p>
        <small>
            <i><?= __('Note: Setting these options to 0 (zero) removes the limit.') ?></i>
        </small>
    </p>
    <?php foreach ($limits as $limit) : ?>
        <?=
            PMA\libraries\Template::get('privileges/resource_limit_item')->render(
                array('limit' => $limit)
            );
        ?>
    <?php endforeach; ?>
</fieldset>

