<div class="item">
    <label for="text_<?= $limit['input_name'] ?>">
        <code>
        <dfn title="<?= $limit['description'] ?>">
            <?= $limit['name_main'] ?>
        </dfn>
        </code>
    </label>
    <input type="number" name="<?= $limit['input_name'] ?>" id="text_<?= $limit['input_name'] ?>"
        value="<?= $limit['value'] ?>" title="<?= $limit['description'] ?>" />
</div>