name: Security report
description: Disclose a security vulnerability responsibly by first reporting it to us privately
title: "[Security]: "
labels: ["Bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: DON'T REPORT IN HERE
      placeholder: |
        Security problems should not be reported here.

        See our security page: https://www.phpmyadmin.net/security/

        Thanks for your help!
    validations:
      required: true
