<table class="data_full_width"
    id="plugins-<?= preg_replace('/[^a-z]/', '', mb_strtolower($plugin_type)); ?>">
    <caption class="tblHeaders">
        <?= htmlspecialchars($plugin_type); ?>
    </caption>
    <thead>
        <tr>
            <th><?=  __('Plugin'); ?></th>
            <th><?=  __('Description'); ?></th>
            <th><?=  __('Version'); ?></th>
            <th><?=  __('Author'); ?></th>
            <th><?=  __('License'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($plugin_list as $plugin): ?>
            <tr class="noclick">
                <th>
                    <?= htmlspecialchars($plugin['plugin_name']); ?>
                    <?php if (! $plugin['is_active']): ?>
                        <small class="attention"><?= __('disabled'); ?></small>
                    <?php endif; ?>
                </th>
                <td><?= htmlspecialchars($plugin['plugin_description']); ?></td>
                <td><?= htmlspecialchars($plugin['plugin_type_version']); ?></td>
                <td><?= htmlspecialchars($plugin['plugin_author']); ?></td>
                <td><?= htmlspecialchars($plugin['plugin_license']); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>