<form action="error_report.php" method="post" name="report_frm" id="report_frm"
      class="ajax">
    <fieldset style="padding-top:0">

        <p>
            <?= __(
                'This report automatically includes data about the error and'
                . ' information about relevant configuration settings.'
                . ' It will be sent to the phpMyAdmin team for debugging the error.'
            ) ?>
        </p>

        <div class="label"><label><strong>
                    <?= __('Can you tell us the steps leading to this error? It decisively helps in debugging:') ?>
                </strong></label>
        </div>
        <textarea class="report-description" name="description"
                  id="report_description"></textarea>

        <div class="label"><label><p>
                    <?= __('You may examine the data in the error report:') ?>
                </p></label></div>
        <pre class="report-data"><?= htmlspecialchars($report_data) ?></pre>

        <input type="checkbox" name="always_send" id="always_send_checkbox" />
        <label for="always_send_checkbox">
            <?= __('Automatically send report next time') ?>
        </label>

    </fieldset>

    <?= $hidden_inputs ?>
    <?= $hidden_fields ?>
</form>