<tr <?= $tr_class ? ('class="' . $tr_class . '"') : ''; ?> data-filter-row="<?= htmlspecialchars(mb_strtoupper($current['SCHEMA_NAME'])); ?>">
    <?php if ($GLOBALS['dbi']->isSuperuser() || $GLOBALS['cfg']['AllowUserDropDatabase']): ?>
        <td class="tool">
            <input type="checkbox" name="selected_dbs[]" class="checkall"
                   title="<?= htmlspecialchars($current['SCHEMA_NAME']); ?>"
                   value="<?= htmlspecialchars($current['SCHEMA_NAME']); ?>"
            <?php if ($GLOBALS['dbi']->isSystemSchema($current['SCHEMA_NAME'], true)): ?>
                disabled="disabled";
            <?php endif; ?>
            />
        </td>
    <?php endif; ?>
    <td class="name">
        <a href="<?= \PhpMyAdmin\Util::getScriptNameForOption($GLOBALS['cfg']['DefaultTabDatabase'], 'database') , \PhpMyAdmin\Url::getCommon(array('db' => $current['SCHEMA_NAME'])); ?>"
           title="<?= sprintf(__('Jump to database'), htmlspecialchars($current['SCHEMA_NAME'])); ?>">
            <?= htmlspecialchars($current['SCHEMA_NAME']); ?>
        </a>
    </td>
    <?php foreach ($column_order as $stat_name => $stat):
        if (! array_key_exists($stat_name, $current)) {
            continue;
        }

        if ($stat['format'] === 'byte') {
            list($value, $unit) = \PhpMyAdmin\Util::formatByteDown($current[$stat_name], 3, 1);
        } elseif ($stat['format'] === 'number') {
            $value = \PhpMyAdmin\Util::formatNumber($current[$stat_name], 0);
        } else {
            $value = htmlentities($current[$stat_name], 0);
        } ?>

        <td class="value">
            <?php if (isset($stat['description_function'])): ?>
                <dfn title="<?= $stat['description_function']($current[$stat_name]); ?>">
                    <?= $value; ?>
                </dfn>
            <?php else: ?>
                <?= $value; ?>
            <?php endif; ?>
        </td>
        <?php if ($stat['format'] === 'byte'): ?>
            <td class="unit"><?= $unit; ?></td>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if ($master_replication_status): ?>
        <td class="tool center">
            <?= $master_replication; ?>
        </td>
    <?php endif; ?>

    <?php if ($slave_replication_status): ?>
        <td class="tool center">
            <?= $slave_replication; ?>
        </td>
    <?php endif; ?>

    <td class="tool">
        <a class="server_databases" data="<?= PhpMyAdmin\Sanitize::jsFormat($current['SCHEMA_NAME']) ?>"
           href="server_privileges.php<?= \PhpMyAdmin\Url::getCommon(array('db' => $current['SCHEMA_NAME'], 'checkprivsdb' => $current['SCHEMA_NAME'])); ?>"
           title="<?= htmlspecialchars(sprintf(__('Check privileges for database "%s".'), $current['SCHEMA_NAME'])); ?>">
           <?= \PhpMyAdmin\Util::getIcon('s_rights.png', __('Check privileges')); ?>
        </a>
    </td>
</tr>
