<?php if ($GLOBALS['is_superuser'] || $GLOBALS['cfg']['AllowUserDropDatabase']): ?>
    <td class="tool">
        <input type="checkbox" name="selected_dbs[]" class="checkall" '
               title="<?php echo htmlspecialchars($current['SCHEMA_NAME']); ?>"
               value="<?php echo htmlspecialchars($current['SCHEMA_NAME']); ?>"
        <?php if ($GLOBALS['dbi']->isSystemSchema($current['SCHEMA_NAME'], true)): ?>
            disabled="disabled"';
        <?php endif; ?>
        />
    </td>
<?php endif; ?>
<td class="name">
    <a href="<?php echo \PMA\libraries\Util::getScriptNameForOption($GLOBALS['cfg']['DefaultTabDatabase'], 'database') . $url_query . '&amp;db=' . urlencode($current['SCHEMA_NAME']); ?>"
       title="<?php echo sprintf(__('Jump to database'), htmlspecialchars($current['SCHEMA_NAME'])); ?>">
        <?php echo htmlspecialchars($current['SCHEMA_NAME']); ?>
    </a>
</td>
<?php foreach ($column_order as $stat_name => $stat):
    if (! array_key_exists($stat_name, $current)) {
        continue;
    }

    if ($stat['format'] === 'byte') {
        list($value, $unit) = \PMA\libraries\Util::formatByteDown($current[$stat_name], 3, 1);
    } elseif ($stat['format'] === 'number') {
        $value = \PMA\libraries\Util::formatNumber($current[$stat_name], 0);
    } else {
        $value = htmlentities($current[$stat_name], 0);
    } ?>

    <td class="value">
        <?php if (isset($stat['description_function'])): ?>
            <dfn title="<?php echo $stat['description_function']($stat['footer']); ?>">
                <?php echo $value; ?>
            </dfn>
        <?php else: ?>
            <?php echo $value; ?>
        <?php endif; ?>
    </td>
    <?php if ($stat['format'] === 'byte'): ?>
        <td class="unit"><?php echo $unit; ?></td>
    <?php endif; ?>
<?php endforeach; ?>

<?php if ($master_replication_status): ?>
    <td class="tool" style="text-align: center;">
        <?php echo $master_replication; ?>
    </td>
<?php endif; ?>

<?php if ($slave_replication_status): ?>
    <td class="tool" style="text-align: center;">
        <?php echo $slave_replication; ?>
    </td>
<?php endif; ?>

<td class="tool">
    <a onclick="PMA_commonActions.setDb('<?php echo PMA_jsFormat($current['SCHEMA_NAME']) ?>');"
       href="server_privileges.php<?php echo $url_query; ?>&amp;db=<?php echo urlencode($current['SCHEMA_NAME']); ?>&amp;checkprivsdb=<?php echo urlencode($current['SCHEMA_NAME']); ?>"
       title="<?php echo sprintf(__('Check privileges for database "%s".'), htmlspecialchars($current['SCHEMA_NAME'])); ?>">
       <?php echo \PMA\libraries\Util::getIcon('s_rights.png', __('Check privileges')); ?>
    </a>
</td>