<tr <?= $tr_class ? ('class="' . $tr_class . '"') : ''; ?>>
    <?php if ($GLOBALS['is_superuser'] || $GLOBALS['cfg']['AllowUserDropDatabase']): ?>
        <td class="tool">
            <input type="checkbox" name="selected_dbs[]" class="checkall"
                   title="<?= htmlspecialchars($current['SCHEMA_NAME']); ?>"
                   value="<?= htmlspecialchars($current['SCHEMA_NAME']); ?>"
            <?php if ($GLOBALS['dbi']->isSystemSchema($current['SCHEMA_NAME'], true)): ?>
                disabled="disabled";
            <?php endif; ?>
            />
        </td>
    <?php endif; ?>
    <td class="name">
        <a href="<?= \PMA\libraries\Util::getScriptNameForOption($GLOBALS['cfg']['DefaultTabDatabase'], 'database') , $url_query , '&amp;db=' , urlencode($current['SCHEMA_NAME']); ?>"
           title="<?= sprintf(__('Jump to database'), htmlspecialchars($current['SCHEMA_NAME'])); ?>">
            <?= htmlspecialchars($current['SCHEMA_NAME']); ?>
        </a>
    </td>
    <?php foreach ($column_order as $stat_name => $stat):
        if (! array_key_exists($stat_name, $current)) {
            continue;
        }

        if ($stat['format'] === 'byte') {
            list($value, $unit) = \PMA\libraries\Util::formatByteDown($current[$stat_name], 3, 1);
        } elseif ($stat['format'] === 'number') {
            $value = \PMA\libraries\Util::formatNumber($current[$stat_name], 0);
        } else {
            $value = htmlentities($current[$stat_name], 0);
        } ?>

        <td class="value">
            <?php if (isset($stat['description_function'])): ?>
                <dfn title="<?= $stat['description_function']($stat['footer']); ?>">
                    <?= $value; ?>
                </dfn>
            <?php else: ?>
                <?= $value; ?>
            <?php endif; ?>
        </td>
        <?php if ($stat['format'] === 'byte'): ?>
            <td class="unit"><?= $unit; ?></td>
        <?php endif; ?>
    <?php endforeach; ?>

    <?php if ($master_replication_status): ?>
        <td class="tool" style="text-align: center;">
            <?= $master_replication; ?>
        </td>
    <?php endif; ?>

    <?php if ($slave_replication_status): ?>
        <td class="tool" style="text-align: center;">
            <?= $slave_replication; ?>
        </td>
    <?php endif; ?>

    <td class="tool">
        <a onclick="PMA_commonActions.setDb('<?= PMA_jsFormat($current['SCHEMA_NAME']) ?>');"
           href="server_privileges.php<?= $url_query; ?>&amp;db=<?= urlencode($current['SCHEMA_NAME']); ?>&amp;checkprivsdb=<?= urlencode($current['SCHEMA_NAME']); ?>"
           title="<?= htmlspecialchars(sprintf(__('Check privileges for database "%s".'), $current['SCHEMA_NAME'])); ?>">
           <?= \PMA\libraries\Util::getIcon('s_rights.png', __('Check privileges')); ?>
        </a>
    </td>
</tr>
