<table class="data" <?php if ($searchType == 'zoom'): ?>
                        id="tableFieldsId"
                   <?php endif; ?>>
    <?= PhpMyAdmin\Template::get('table/search/table_header')
        ->render(array(
            'geom_column_flag' => $geomColumnFlag
        )); ?>
    <tbody>
    <?php if ($searchType == 'zoom'): ?>
        <?= PhpMyAdmin\Template::get('table/search/rows_zoom')
            ->render(array(
                'self' => $self,
                'columnNames' => $columnNames
        )) ?>
    <?php else: ?>
        <?= PhpMyAdmin\Template::get('table/search/rows_normal')
            ->render(array(
                'self' => $self,
                'geom_column_flag' => $geomColumnFlag,
                'column_names' => $columnNames,
                'column_types' => $columnTypes,
                'column_collations' => $columnCollations
        )) ?>
    <?php endif; ?>
    </tbody>
</table>
