<?php
$scriptName = '';
$formId = '';
switch ($searchType) {
    case 'normal' :
        $scriptName = 'tbl_select.php';
        $formId = 'tbl_search_form';
        break;
    case 'zoom' :
        $scriptName = 'tbl_zoom_select.php';
        $formId = 'zoom_search_form';
        break;
    case 'replace' :
        $scriptName = 'tbl_find_replace.php';
        $formId = 'find_replace_form';
        break;
}
?>
<form method="post" action="<?= $scriptName; ?>" name="insertForm" id="<?= $formId; ?>" class="ajax lock-page">
    <?= \PMA\libraries\URL::getHiddenInputs($db, $table); ?>
    <input type="hidden" name="goto" value="<?= $goto; ?>" />
    <input type="hidden" name="back" value="<?= $scriptName; ?>" />
