<form method="post"
      action="tbl_find_replace.php"
      name="previewForm"
      id="previewForm">
    <?= PMA_URL_getHiddenInputs($db, $table); ?>
    <input type="hidden" name="replace" value="true" />
    <input type="hidden" name="columnIndex" value="<?= $columnIndex; ?>" />
    <input type="hidden" name="findString" value="<?= htmlspecialchars($find); ?>" />
    <input type="hidden" name="replaceWith" value="<?= htmlspecialchars($replaceWith); ?>" />
    <input type="hidden" name="useRegex" value="<?= $useRegex; ?>" />

    <fieldset id="fieldset_find_replace_preview">
        <legend><?= __('Find and replace - preview'); ?></legend>
        <table id="previewTable">
            <thead>
            <tr>
                <th><?= __('Count'); ?></th>
                <th><?= __('Original string'); ?></th>
                <th><?= __('Replaced string'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $odd = true; ?>
            <?php if (is_array($result)): ?>
                <?php foreach ($result as $row): ?>
                    <?php $val = $row[0]; $replaced = $row[1]; $count = $row[2]; ?>
                    <tr class="<?= ($odd ? 'odd' : 'even'); ?>">
                        <td class="right"><?= htmlspecialchars($count); ?></td>
                        <td><?= htmlspecialchars($val); ?></td>
                        <td><?= htmlspecialchars($replaced); ?></td>
                    </tr>
                    <?php $odd = ! $odd; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </fieldset>

    <fieldset class="tblFooters">
        <input type="submit" name="replace" value="<?= __('Replace'); ?>" />
    </fieldset>
</form>