<?php
$odd_row = true;
// for every column present in table
for (
    $column_index = 0, $nb = count($columnNames);
    $column_index < $nb;
    $column_index++
): ?>
    <tr class="noclick <?= $odd_row ? 'odd' : 'even'; ?>">
        <?php $odd_row = !$odd_row; ?>
        <!-- If 'Function' column is present -->
        <?php if ($geomColumnFlag): ?>
            <?= PMA\libraries\Template::get('table/search/geom_func')
                ->render(array(
                    'column_index' => $column_index,
                    'columnTypes' => $columnTypes,
                )); ?>
        <?php endif; ?>
        <!-- Displays column's name, type, collation and value -->
        <th>
            <?= htmlspecialchars($columnNames[$column_index]); ?>
        </th>
        <?php $properties = $self->getColumnProperties($column_index, $column_index); ?>
        <td dir="ltr">
            <?= htmlspecialchars($properties['type']); ?>
        </td>
        <td>
            <?= $properties['collation']; ?>
        </td>
        <td>
            <?= $properties['func']; ?>
        </td>
        <!-- here, the data-type attribute is needed for a date/time picker-->
        <td data-type="<?= htmlspecialchars($properties['type']); ?>">
            <?= $properties['value']; ?>
        </td>
    </tr>
    <!-- Displays hidden fields -->
    <tr>
        <td>
            <input type="hidden"
                   name="criteriaColumnNames[<?= $column_index; ?>]"
                   value="<?= htmlspecialchars($columnNames[$column_index]); ?>" />
            <input type="hidden"
                   name="criteriaColumnTypes[<?= $column_index; ?>]"
                   value="<?= htmlspecialchars($columnTypes[$column_index]); ?>" />
            <input type="hidden"
                   name="criteriaColumnCollations[<?= $column_index; ?>]"
                   value="<?= $columnCollations[$column_index]; ?>" />
        </td>
    </tr>
<?php endfor; ?>