<?= __('Find:'); ?>
<input type="text" value="" name="find" required />
<?= __('Replace with:'); ?>
<input type="text" value="" name="replaceWith" />

<?= __('Column:'); ?>
<select name="columnIndex">
    <?php for ($i = 0, $nb = count($columnNames); $i < $nb; $i++): ?>
        <?php $type = preg_replace('@\(.*@s', '', $columnTypes[$i]); ?>
        <?php if ($GLOBALS['PMA_Types']->getTypeClass($type) == 'CHAR'): ?>
            <?php $column = $columnNames[$i]; ?>
            <option value="<?= $i; ?>">
                <?= htmlspecialchars($column); ?>
            </option>
        <?php endif; ?>
    <?php endfor; ?>
</select>

<br>
<?= PMA\libraries\Template::get('checkbox')
->render(
    array(
        'html_field_name'   => 'useRegex',
        'label'             => __('Use regular expression'),
        'checked'           => false,
        'onclick'           => false,
        'html_field_id'     => 'useRegex',
    )
); ?>
