<?php
$scriptName = '';
$formId = '';
switch ($searchType) {
    case 'normal' :
        $scriptName = 'tbl_select.php';
        $formId = 'tbl_search_form';
        break;
    case 'zoom' :
        $scriptName = 'tbl_zoom_select.php';
        $formId = 'zoom_search_form';
        break;
    case 'replace' :
        $scriptName = 'tbl_find_replace.php';
        $formId = 'find_replace_form';
        break;
}
?>
<?= PhpMyAdmin\Template::get('table/search/form_tag')
    ->render(array(
        'script_name' => $scriptName,
        'form_id' => $formId,
        'db' => $db,
        'table' => $table,
        'goto' => $goto
    )) ?>
<?php if ($searchType == 'zoom'): ?>
    <fieldset id="fieldset_zoom_search">
        <fieldset id="inputSection">
            <legend>
                <?= __('Do a "query by example" (wildcard: "%") for two different columns'); ?>
            </legend>
            <?= PhpMyAdmin\Template::get('table/search/fields_table')
                ->render(array(
                    'self' => $self,
                    'searchType' => $searchType,
                    'geomColumnFlag' => $geomColumnFlag,
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes,
                    'columnCollations' => $columnCollations
                ))
            ?>
            <?= PhpMyAdmin\Template::get('table/search/options_zoom')
                ->render(array(
                    'dataLabel' => $dataLabel,
                    'columnNames' => $columnNames
            )) ?>
        </fieldset>
    </fieldset>
<?php elseif ($searchType == 'normal'): ?>
    <fieldset id="fieldset_table_search">
        <fieldset id="fieldset_table_qbe">
            <legend>
                <?= __('Do a "query by example" (wildcard: "%")'); ?>
            </legend>
            <div class="responsivetable jsresponsive">
                <?= PhpMyAdmin\Template::get('table/search/fields_table')
                ->render(array(
                    'self' => $self,
                    'searchType' => $searchType,
                    'geomColumnFlag' => $geomColumnFlag,
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes,
                    'columnCollations' => $columnCollations
                )); ?>
            </div>
            <div id="gis_editor">
            </div>
            <div id="popup_background">
            </div>
        </fieldset>
        <?= PhpMyAdmin\Template::get('table/search/options')
            ->render(array(
                'column_names' => $columnNames,
                'max_rows' => intval($GLOBALS['cfg']['MaxRows'])
            )); ?>
    </fieldset>
<?php elseif ($searchType == 'replace'): ?>
    <fieldset id="fieldset_find_replace">
        <fieldset id="fieldset_find">
            <legend>
                <?= __('Find and replace'); ?>
            </legend>
            <?= PhpMyAdmin\Template::get('table/search/search_and_replace')
                ->render(array(
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes
                )); ?>
        </fieldset>
    </fieldset>
<?php endif; ?>

<!--Displays selection form's footer elements-->
<fieldset class="tblFooters">
    <input type="submit"
           name="<?= ($searchType == 'zoom' ? 'zoom_submit' : 'submit'); ?>"
           <?php if ($searchType == 'zoom'): ?>
               id="inputFormSubmitId"
           <?php endif; ?>
           value="<?= __('Go'); ?>" />
</fieldset>
</form>
<div id="sqlqueryresultsouter"></div>
