<?= PMA\libraries\Template::get('table/search/form_tag')
    ->render(array(
        'searchType' => $searchType,
        'db' => $db,
        'table' => $table,
        'goto' => $goto
    )) ?>
<?php if ($searchType == 'zoom'): ?>
    <fieldset id="fieldset_zoom_search">
        <fieldset id="inputSection">
            <legend>
                <?= __('Do a "query by example" (wildcard: "%") for two different columns'); ?>
            </legend>
            <?= PMA\libraries\Template::get('table/search/fields_table')
                ->render(array(
                    'self' => $self,
                    'searchType' => $searchType,
                    'geomColumnFlag' => $geomColumnFlag,
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes,
                    'columnCollations' => $columnCollations
                ))
            ?>
            <?= PMA\libraries\Template::get('table/search/options_zoom')
                ->render(array(
                    'dataLabel' => $dataLabel,
                    'columnNames' => $columnNames
            )) ?>
        </fieldset>
    </fieldset>
<?php elseif ($searchType == 'normal'): ?>
    <fieldset id="fieldset_table_search">
        <fieldset id="fieldset_table_qbe">
            <legend>
                <?= __('Do a "query by example" (wildcard: "%")'); ?>
            </legend>
            <?= PMA\libraries\Template::get('table/search/fields_table')
                ->render(array(
                    'self' => $self,
                    'searchType' => $searchType,
                    'geomColumnFlag' => $geomColumnFlag,
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes,
                    'columnCollations' => $columnCollations
                )); ?>
            <div id="gis_editor">
            </div>
            <div id="popup_background">
            </div>
        </fieldset>
        <?= PMA\libraries\Template::get('table/search/options')
            ->render(array(
                'columnNames' => $columnNames
            )); ?>
    </fieldset>
<?php elseif ($searchType == 'replace'): ?>
    <fieldset id="fieldset_find_replace">
        <fieldset id="fieldset_find">
            <legend>
                <?= __('Find and replace'); ?>
            </legend>
            <?= PMA\libraries\Template::get('table/search/search_and_replace')
                ->render(array(
                    'columnNames' => $columnNames,
                    'columnTypes' => $columnTypes
                )); ?>
        </fieldset>
    </fieldset>
<?php endif; ?>

<!--Displays selection form's footer elements-->
<fieldset class="tblFooters">
    <input type="submit"
           name="<?= ($searchType == 'zoom' ? 'zoom_submit' : 'submit'); ?>"
           <?php if ($searchType == 'zoom'): ?>
               id="inputFormSubmitId"
           <?php endif; ?>
           value="<?= __('Go'); ?>" />
</fieldset>
</form>
<div id="sqlqueryresultsouter"></div>