<form id="create_table_form_minimal" method="post" action="tbl_create.php" class="lock-page">
    <fieldset>
        <legend>
        <?php if (PMA\libraries\Util::showIcons('ActionLinksMode')): ?>
            <?= PMA\libraries\Util::getImage('b_table_add.png'); ?>&nbsp
        <?php endif; ?>
        <?= __('Create table'); ?>
        </legend>
        <?= PMA\libraries\URL::getHiddenInputs($db); ?>
        <div class="formelement">
            <?= __('Name'); ?>:
            <input type="text" name="table" maxlength="64" size="30" required="required" />
        </div>
        <div class="formelement">
            <?= __('Number of columns'); ?>:
            <input type="number" min="1" name="num_fields" value="4" required="required" />
        </div>
        <div class="clearfloat"></div>
    </fieldset>
    <fieldset class="tblFooters">
        <input type="submit" value="<?= __('Go'); ?>" />
    </fieldset>
</form>
