<form id="create_table_form_minimal" method="post" action="tbl_create.php" class="lock-page">
    <fieldset>
        <legend>
        <?php if (PMA_Util::showIcons('ActionLinksMode')): ?>
            <?php echo PMA_Util::getImage('b_table_add.png'); ?>&nbsp
        <?php endif; ?>
        <?php echo __('Create table'); ?>
        </legend>
        <?php echo PMA_URL_getHiddenInputs($db); ?>
        <div class="formelement">
            <?php echo __('Name'); ?>:
            <input type="text" name="table" maxlength="64" size="30" required="required" />
        </div>
        <div class="formelement">
            <?php echo __('Number of columns'); ?>:
            <input type="number" min="1" name="num_fields" value="4" required="required" />
        </div>
        <div class="clearfloat"></div>
    </fieldset>
    <fieldset class="tblFooters">
        <input type="submit" value="<?php echo __('Go'); ?>" />
    </fieldset>
</form>
