<?php require_once 'libraries/url_generating.lib.php'; ?>
<script type="text/javascript">
    pma_token = '<?php echo $_SESSION[' PMA_token ']; ?>';
    url_query = '<?php echo $url_query; ?>';
</script>
<!-- Display Chart options -->
<div id="div_view_options">
    <form method="post" id="tblchartform" action="tbl_chart.php" class="ajax">
        <?php echo PMA_URL_getHiddenInputs($url_params); ?>
        <fieldset>
            <legend>
                <?php echo __('Display chart'); ?>
            </legend>
            <div class="chartOption">
                <div class="formelement">
                    <input type="radio" name="chartType" value="bar" id="radio_bar" />
                    <label for ="radio_bar"><?php echo _pgettext('Chart type', 'Bar') ?></label>
                </div>
                <div class="formelement">
                    <input type="radio" name="chartType" value="column" id="radio_column" />
                    <label for ="radio_column"><?php echo _pgettext('Chart type', 'Column') ?></label>
                </div>
                <div class="formelement">
                    <input type="radio" name="chartType" value="line" id="radio_line" checked="checked" />
                    <label for ="radio_line"><?php echo _pgettext('Chart type', 'Line') ?></label>
                </div>
                <div class="formelement">
                    <input type="radio" name="chartType" value="spline" id="radio_spline" />
                    <label for ="radio_spline"><?php echo _pgettext('Chart type', 'Spline') ?></label>
                </div>
                <div class="formelement">
                    <input type="radio" name="chartType" value="area" id="radio_area" />
                    <label for ="radio_area"><?php echo _pgettext('Chart type', 'Area') ?></label>
                </div>
                <span class="span_pie" style="display:none;">
                    <input type="radio" name="chartType" value="pie" id="radio_pie" />
                    <label for ="radio_pie"><?php echo _pgettext('Chart type', 'Pie') ?></label>
                </span>
                <span class="span_timeline" style="display:none;">
                    <input type="radio" name="chartType" value="timeline" id="radio_timeline" />
                    <label for ="radio_timeline"><?php echo _pgettext('Chart type', 'Timeline') ?></label>
                </span>
                <span class="span_scatter" style="display:none;">
                <input type="radio" name="chartType" value="scatter" id="radio_scatter" />
                <label for ="radio_scatter"><?php echo _pgettext('Chart type', 'Scatter') ?></label>
                </span>
                <br /><br />
                <span class="barStacked" style="display:none;">
                    <input type="checkbox" name="barStacked" value="1" id="checkbox_barStacked" />
                    <label for ="checkbox_barStacked"><?php echo __('Stacked') ?></label>
                </span>
                <br /><br />
                <input type="text" name="chartTitle" value="<?php echo __('Chart title'); ?>">
            </div>
            <?php $xaxis = null; ?>
            <div class="chartOption">
                <label for="select_chartXAxis"><?php echo __('X-Axis:'); ?></label>
                <select name="chartXAxis" id="select_chartXAxis">
                    <?php foreach ($keys as $idx => $key) : ?>
                        <?php if ($xaxis === null) : ?>
                            <?php $xaxis = $idx; ?>
                        <?php endif; ?>
                        <?php if ($xaxis === $idx) : ?>
                            <option value="<?php echo htmlspecialchars($idx); ?>" selected="selected"><?php echo htmlspecialchars($key); ?></option>
                        <?php else : ?>
                            <option value="<?php echo htmlspecialchars($idx); ?>"><?php echo htmlspecialchars($key); ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
                <br />
                <label for="select_chartSeries">
                    <?php echo __('Series:'); ?>
                </label>
                <select name="chartSeries" id="select_chartSeries" multiple="multiple">
                    <?php foreach ($keys as $idx => $key) : ?>
                        <?php if (in_array($fields_meta[$idx]->type, $numeric_types)) : ?>
                            <?php if ($idx == $xaxis && $numeric_column_count > 1) : ?>
                                <option value="<?php echo htmlspecialchars($idx); ?>"><?php echo htmlspecialchars($key); ?></option>
                            <?php else : ?>
                                <option value="<?php echo htmlspecialchars($idx); ?>" selected="selected"><?php echo htmlspecialchars($key); ?></option>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach;?>
                </select>
                <input type="hidden" name="dateTimeCols" value="<?php $date_time_types = array('date', 'datetime', 'timestamp');
                    foreach ($keys as $idx => $key) {
                        if (in_array($fields_meta[$idx]->type, $date_time_types)) {
                            echo $idx . ' ';
                        }
                    }?>"
                />
                <input type="hidden" name="numericCols" value="<?php
                    foreach ($keys as $idx => $key) {
                        if (in_array($fields_meta[$idx]->type, $numeric_types)) {
                            echo $idx . ' ';
                        }
                    }?>"
                />
            </div>
            <div class="chartOption">
                <label for="xaxis_panel">
                    <?php echo __('X-Axis label:'); ?>
                </label>
                <input style="margin-top:0;" type="text" name="xaxis_label" id="xaxis_label" value="<?php echo (($xaxis == -1) ? __('X Values') : htmlspecialchars($keys[$xaxis])); ?>" />
                <br />
                <label for="yaxis_label">
                    <?php echo __('Y-Axis label:'); ?>
                </label>
                <input type="text" name="yaxis_label" id="yaxis_label" value="<?php echo __('Y Values'); ?>" />
                <br />
            </div>
            <p style="clear:both;">&nbsp;</p>
            <div>
                <input type="checkbox" id="chkAlternative" name="chkAlternative" value="alternativeFormat" />
                <label for="chkAlternative"><?php echo __('Series names are in a column'); ?></label>
                <br />
                <label for="select_seriesColumn">
                    <?php echo __('Series column:'); ?>
                </label>
                <select name="chartSeriesColumn" id="select_seriesColumn" disabled>
                    <?php foreach ($keys as $idx => $key) : ?>
                        <option value="<?php echo htmlspecialchars($idx);
                        if ($idx == 1) : echo ' selected="selected"'; endif;
                        $seriesColumn = $idx; ?>">
                            <?php echo htmlspecialchars($key); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <label for="select_valueColumn">
                    <?php echo __('Value Column:'); ?>
                </label>
                <select name="chartValueColumn" id="select_valueColumn" disabled>
                    <?php $selected = false;
                    foreach ($keys as $idx => $key) : ?>
                        <?php if (in_array($fields_meta[$idx]->type, $numeric_types)) : ?>
                            <?php if (! $selected && $idx != $xaxis && $idx != $seriesColumn) : ?>
                                <option value="<?php echo htmlspecialchars($idx); ?>" selected="selected"><?php echo htmlspecialchars($key); $selected = true; ?></option>
                            <?php else: ?>
                                <option value="<?php echo htmlspecialchars($idx); ?>"><?php echo htmlspecialchars($key); ?></option>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <?php echo PMA_Util::getStartAndNumberOfRowsPanel($sql_query); ?>
            <p style="clear:both;">&nbsp;</p>
            <div id="resizer" style="width:600px; height:400px;">
                <div style="position: absolute; right: 10px; top: 10px; cursor: pointer; z-index: 1000;">
                    <a class="disableAjax" id="saveChart" href="#" download="chart.png">
                        <?php echo PMA_Util::getImage('b_saveimage', __('Save chart as image')); ?>
                    </a>
                </div>
                <div id="querychart" dir="ltr">
                </div>
            </div>
        </fieldset>
    </form>
</div>