<input type="checkbox" name="<?= $html_field_name ; ?>"
        <?php if (isset($html_field_id)):           ?>
            id="<?= $html_field_id ;                ?>"
        <?php endif ;
        if (isset($checked) && $checked):           ?>
            checked="checked"
        <?php endif ;
        if (isset($onclick) && $onclick):           ?>
            class="autosubmit"
        <?php endif ;                               ?> />
<label  <?php if (isset($html_field_id)):           ?>
            for="<?= $html_field_id ; endif ;       ?>"><?= $label ; ?></label>
