<?php if($InitialSlidersState == 'disabled'): ?>
    <div <?= $id? "id=\"$id\"": '' ?>>
<?php else: ?>
    <?php /**
        * Bad hack on the next line. document.write() conflicts with jQuery,
        * hence, opening the <div> with PHP itself instead of JavaScript.
        *
        * @todo find a better solution that uses $.append(), the recommended
        * method maybe by using an additional param, the id of the div to
        * append to
        */ ?>
    <div <?= $id? "id=\"$id\"": '' ?>
        <?= ($InitialSlidersState == 'closed')? ' style="display: none; overflow:auto;"':'' ?> class="pma_auto_slider"
        <?= $message? 'title="'. htmlspecialchars($message) . '"': ""?> >
<?php endif; ?>
