<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * Manage HTML redirection
 *
 * @package PhpMyAdmin-template
 *
 * @param string $uri Redirection location
 */
$uri = isset($uri) ? $uri : null;
?>
<html>
<head>
    <title>- - -</title>
    <meta http-equiv="expires" content="0">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Refresh" content="0;url=<?= htmlspecialchars($uri) ?>">
    <script type="text/javascript">
        //<![CDATA[
        setTimeout("window.location = decodeURI('<?= PMA_escapeJsString($uri) ?>')", 2000);
        //]]>
    </script>
</head>
<body>
<script type="text/javascript">
    //<![CDATA[
    document.write('<p><a href="<?= PMA_escapeJsString(htmlspecialchars($uri)) ?>"><?php echo __('Go') ?></a></p>');
    //]]>
</script>
</body>
</html>
