<html>
<head>
    <title>- - -</title>
    <meta http-equiv="expires" content="0">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Refresh" content="0;url=<?php echo htmlspecialchars($uri) ?>">
    <script type="text/javascript">
        //<![CDATA[
        setTimeout("window.location = unescape('<?php echo PMA_escapeJsString($uri) ?>')", 2000);
        //]]>
    </script>
</head>
<body>
<script type="text/javascript">
    //<![CDATA[
    document.write('<p><a href="<?php echo htmlspecialchars($uri) ?>"><?php echo __('Go') ?></a></p>');
    //]]>
</script>
</body>
</html>