<?php if( !empty($class) ): ?>
<div class="<?= $class ?>">
<?php endif ?>
<input type="radio" name="<?=$html_field_name?>" id="<?=$html_field_id?>" value="<?=htmlspecialchars($choice_value)?>"<?= $checked? ' checked="checked"' : ''?> />
<label for="<?= $html_field_id ?>"><?= $escape_label? htmlspecialchars($choice_label) : $choice_label ?></label>
<?php if( $is_line_break ): ?>
<br />
<?php endif ?>
<?php if( !empty($class) ): ?>
</div>
<?php endif ?>