<img class="selectallarrow" src="<?= $pmaThemeImage . 'arrow_' . $text_dir . '.png' ; ?>"
    width="38" height="22" alt="<?= __('With selected:') ; ?>" />
<input type="checkbox" id="<?= $formName . '_checkall' ;   ?>" class="checkall_box"
    title="<?= __('Check all') ;      ?>" />
<label for="<?= $formName . '_checkall'?>"> <?= __('Check all') ;?> </label>
<i style="margin-left: 2em">
    <?= __('With selected:') ;                             ?> </i>
