    <form method="get" action="index.php" class="disableAjax">
    <?= PMA\libraries\URL::getHiddenInputs($_form_params) ?>

    <?php if ($use_fieldset) : ?>
        <fieldset>
            <legend lang="en" dir="ltr"> <?= $language_title ?> </legend>
    <?php else : ?>
        <bdo lang="en" dir="ltr">
            <label for="sel-lang"><?= $language_title ?> </label>
        </bdo>
    <?php endif; ?>

    <select name="lang" class="autosubmit" lang="en" dir="ltr" id="sel-lang">

    <?php foreach ($available_languages as $language): ?>
        <!-- Is current one active ?  -->
        <option value=<?= '"', strtolower($language->getCode()), '"' ?>
            <?php if ($language->isActive()) : ?>
                    selected="selected"
            <?php endif; ?>
            >
        <?= $language->getName(); ?>
        </option>
    <?php endforeach; ?>

    </select>

    <?php if ($use_fieldset): ?>
        </fieldset>
    <?php endif; ?>

    </form>
