<!-- TOGGLE START -->
<div class='wrapper toggleAjax hide'>
      <div class='toggleButton'>
            <div title=" <?= __('Click to toggle') ?>" class='container <?=$state?>'>
                  <img src="<?= htmlspecialchars($pmaThemeImage) ?>toggle-<?= htmlspecialchars($text_dir) ?>.png" alt='' />
                  <table class='nospacing nopadding'>
                        <tbody>
                              <tr>
                                    <td class='toggleOn'>
                                        <span class='hide'><?= $link_on ?></span>
                                        <div><?= $toggleOn ?></div>
                                    </td>
                                    <td><div>&nbsp;</div></td>
                                    <td class='toggleOff'>
                                        <span class='hide'><?= $link_off ?></span>
                                        <div><?= $toggleOff ?></div>
                                    </td>
                              </tr>
                        </tbody>
                  </table>
                  <span class='hide callback'><?= htmlspecialchars($callback) ?></span>
                  <span class='hide text_direction'><?= $text_dir ?></span>
            </div>
      </div>
</div>
<!-- TOGGLE END -->