#!/bin/sh

set -e

for file in `find js -name '*.js' -not -name '*min.js'` ; do
    mkdir -p sources/`dirname $file`
    mv $file sources/$file
    java -jar ./scripts/google-javascript-compiler/compiler.jar --js sources/$file --js_output_file $file
done
