#!/bin/sh
if [ x$1 = x--quiet ] ; then
    stats=""
else
    stats="--statistics"
fi

for x in po/*.po  ; do 
    lang=`echo $x | sed 's@po/\(.*\)\.po@\1@'`
    if [ ! -z "$stas" ] ; then
        echo -n "$lang: "
    fi
    mkdir -p locale/$lang/LC_MESSAGES
    msgfmt $stats --check -o locale/$lang/LC_MESSAGES/phpmyadmin.mo $x
done
