#!/bin/sh
if [ x$1 = x--quiet ] ; then
    stats=""
    shift
else
    stats="--statistics"
fi

compile() {
    lang=`echo $1 | sed 's@po/\(.*\)\.po@\1@'`
    if [ ! -z "$stats" ] ; then
        echo -n "$lang: "
    fi
    mkdir -p locale/$lang/LC_MESSAGES
    msgfmt $stats --check -o locale/$lang/LC_MESSAGES/phpmyadmin.mo $1
}

if [ ! -z "$1" ] ; then
    compile po/$1.po
    exit 0
fi

for x in po/*.po  ; do 
    compile $x
done
