#!/bin/sh
# Do not run as CGI
if [ -n "$GATEWAY_INTERFACE" ] ; then
    echo 'Can not invoke as CGI!'
    exit 1
fi

for x in po/*.po  ; do
    grep 'Team' $x | sed 's/.*: \(.*\)<.*/\1/'
    git shortlog -sne --no-merges -- $x | grep '^  [ 0-9][0-9]\{3\}'
done
