#!/bin/sh
for x in po/*.po  ; do 
    grep 'Team' $x | sed 's/.*: \(.*\)<.*/\1/'
    git shortlog -sne --no-merges -- $x | grep '^  [ 0-9][0-9]\{3\}'
#    lang=`basename $x`
#    echo -n "$lang: "
#    msgfmt --statistics --check -o - $x > /dev/null
done
