#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:
export LC_ALL=C
LOCS=`ls po/*.po | sed 's@.*/\(.*\)\.po@\1@'`
xgettext \
    -d phpmyadmin \
    --msgid-bugs-address=phpmyadmin-devel@lists.sourceforge.net \
    -o po/phpmyadmin.pot \
    --language=PHP \
    --add-comments=l10n \
    --add-location \
    --debug \
    --keyword=__ --keyword=_pgettext:1c,2 --keyword=_ngettext:1,2 \
    --copyright-holder="phpMyAdmin devel team" \
    `find . -name '*.php' -not -path './test/*' | sort`

ver=`sed -n "/PMA_VERSION', '/ s/.*PMA_VERSION', '\(.*\)'.*/\1/p" libraries/Config.class.php`

sed -i '
    s/SOME DESCRIPTIVE TITLE/phpMyAdmin translation/;
    s/PACKAGE/phpMyAdmin/;
    s/(C) YEAR/(C) 2003 - '`date +%Y`'/;
    s/VERSION/'$ver'/;
    ' po/phpmyadmin.pot

for loc in $LOCS ; do
    sed -i '
        s/SOME DESCRIPTIVE TITLE/phpMyAdmin translation/;
        s/PACKAGE/phpMyAdmin/;
        s/(C) YEAR/(C) 2003 - '`date +%Y`'/;
        s/VERSION/'$ver'/;
        s/Project-Id-Version: phpMyAdmin .*/Project-Id-Version: phpMyAdmin '$ver'\\n"/;
        ' po/$loc.po
    if [ -f ../localized_docs/po/$loc.po ] ; then
        msgmerge --previous -C ../localized_docs/po/$loc.po -U po/$loc.po po/phpmyadmin.pot
    else
        msgmerge --previous -U po/$loc.po po/phpmyadmin.pot
    fi
done
