<li class="<?= $class; ?>">
<?php if ($type == 'text'
        || $type == 'blob'
        || 'ARCHIVE' == $tbl_storage_engine
        || $hasField
    ): ?>
    <?= $titles['No' . $action]; ?>
<?php else: ?>
    <a rel="samepage" class="ajax add_key print_ignore
        <?php if ($hasLinkClass): ?>
             add_primary_key_anchor"
        <?php elseif ($action=='Index'): ?>
             add_index_anchor"
        <?php elseif ($action=='Unique'): ?>
             add_unique_anchor"
        <?php elseif ($action=='Spatial'): ?>
             add_spatial_anchor"
        <?php else: ?>
            "
        <?php endif; ?> href="tbl_structure.php<?= $url_query; ?>&amp;add_key=1&amp;sql_query=<?= urlencode(
                'ALTER TABLE ' . PMA\libraries\Util::backquote($GLOBALS['table'])
                . ($isPrimary ? ($primary ? ' DROP PRIMARY KEY,' : '') : '')
                . ' ' . $syntax . '('
                . PMA\libraries\Util::backquote($row['Field']) . ');'); ?>&amp;message_to_show=<?= urlencode(sprintf($message, htmlspecialchars($row['Field']))); ?>" >
            <?= $titles[$action]; ?>
    </a>
<?php endif; ?>
</li>