<td class="print_ignore"><ul class="table-structure-actions resizable-menu">
    <!-- Add primary -->
    <?php use PMA\libraries\Util; ?>

    <?= PMA\libraries\Template::get('table/structure/action_row_in_structure_table')->render(
            array(
                'type' => $type,
                'tbl_storage_engine' => $tbl_storage_engine,
                'class' => 'primary nowrap',
                'hasField' => ($primary && $primary->hasColumn($field_name)),
                'hasLinkClass' => true,
                'url_query' => $url_query,
                'primary' => $primary,
                'syntax' => 'ADD PRIMARY KEY',
                'message' => __('A primary key has been added on %s.'),
                'action' => 'Primary',
                'titles' => $titles,
                'row' => $row,
                'isPrimary' => true
            )
        )
    ?>
    <!-- Add unique -->
    <?= PMA\libraries\Template::get('table/structure/action_row_in_structure_table')->render(
            array(
                'type' => $type,
                'tbl_storage_engine' => $tbl_storage_engine,
                'class' => 'add_unique unique nowrap',
                'hasField' => in_array($field_name, $columns_with_unique_index),
                'hasLinkClass' => false,
                'url_query' => $url_query,
                'primary' => $primary,
                'syntax' => 'ADD UNIQUE',
                'message' => __('An index has been added on %s.'),
                'action' => 'Unique',
                'titles' => $titles,
                'row' => $row,
                'isPrimary' => false
            )
        )
    ?>
    <!-- Add index -->
    <?= PMA\libraries\Template::get('table/structure/action_row_in_structure_table')->render(
            array(
                'type' => $type,
                'tbl_storage_engine' => $tbl_storage_engine,
                'class' => 'add_index nowrap',
                'hasField' => false,
                'hasLinkClass' => false,
                'url_query' => $url_query,
                'primary' => $primary,
                'syntax' => 'ADD INDEX',
                'message' => __('An index has been added on %s.'),
                'action' => 'Index',
                'titles' => $titles,
                'row' => $row,
                'isPrimary' => false
            )
        )
    ?>

    <!-- Add spatial -->
    <?php $spatial_types = array(
            'geometry', 'point', 'linestring', 'polygon', 'multipoint',
            'multilinestring', 'multipolygon', 'geomtrycollection'
        );
    ?>
    <?= PMA\libraries\Template::get('table/structure/action_row_in_structure_table')->render(
            array(
                'type' => $type,
                'tbl_storage_engine' => $tbl_storage_engine,
                'class' => 'spatial nowrap',
                'hasField' => ! (in_array($type, $spatial_types) && ('MYISAM' == $tbl_storage_engine || PMA_MYSQL_INT_VERSION >= 50705)),
                'hasLinkClass' => false,
                'url_query' => $url_query,
                'primary' => $primary,
                'syntax' => 'ADD SPATIAL',
                'message' => __('An index has been added on %s.'),
                'action' => 'Spatial',
                'titles' => $titles,
                'row' => $row,
                'isPrimary' => false
            )
        )
    ?>
    <!-- FULLTEXT is possible on TEXT, CHAR and VARCHAR -->
    <li class="fulltext nowrap">
    <?php if (! empty($tbl_storage_engine)
                && ($tbl_storage_engine == 'MYISAM'
                || $tbl_storage_engine == 'ARIA'
                || $tbl_storage_engine == 'MARIA'
                || ($tbl_storage_engine == 'INNODB' && PMA_MYSQL_INT_VERSION >= 50604))
                && (mb_strpos($type, 'text') !== false
                || mb_strpos($type, 'char') !== false)
            ): ?>
        <a rel="samepage" class="ajax add_key add_fulltext_anchor" href="tbl_structure.php<?= $url_query; ?>&amp;add_key=1&amp;sql_query=<?= urlencode(
            'ALTER TABLE ' . Util::backquote($GLOBALS['table'])
            . ' ADD FULLTEXT(' . Util::backquote($row['Field'])
            . ');'); ?>&amp;message_to_show=<?= urlencode(sprintf(
                __('An index has been added on %s.'),
                htmlspecialchars($row['Field']))); ?>">
            <?= $titles['IdxFulltext']; ?>
        </a>
    <?php else: ?>
        <?= $titles['NoIdxFulltext']; ?>
    <?php endif; ?>
    </li>
    <!-- Distinct value action -->
    <li class="browse nowrap">
        <a href="sql.php<?= $url_query; ?>&amp;sql_query=<?= urlencode(
                'SELECT COUNT(*) AS ' . PMA\libraries\Util::backquote(__('Rows'))
                . ', ' . PMA\libraries\Util::backquote($row['Field'])
                . ' FROM ' . PMA\libraries\Util::backquote($GLOBALS['table'])
                . ' GROUP BY ' . PMA\libraries\Util::backquote($row['Field'])
                . ' ORDER BY ' . PMA\libraries\Util::backquote($row['Field'])
            ); ?>&amp;is_browse_distinct=1">
            <?= $titles['DistinctValues']; ?>
        </a>
    </li>
    <?php if ($GLOBALS['cfgRelation']['centralcolumnswork']): ?>
        <li class="browse nowrap">
        <?php if ($isInCentralColumns): ?>
            <a href="#" onclick="$('input:checkbox').prop('checked', false);
                $('#checkbox_row_<?= $rownum; ?>').prop('checked', true);
                $('button[value=remove_from_central_columns]').click();">
            <?= PMA\libraries\Util::getIcon(
                'centralColumns_delete.png',
                __('Remove from central columns')
            ); ?></a>
        <?php else: ?>
            <a href="#" onclick="$('input:checkbox').prop('checked', false);
                $('#checkbox_row_<?= $rownum ?>').prop('checked', true);
                $('button[value=add_to_central_columns]').click();">
            <?= PMA\libraries\Util::getIcon(
                'centralColumns_add.png',
                __('Add to central columns')
            ); ?></a>
        <?php endif; ?>
        </li>
    <?php endif; ?>
</ul></td>