<form method="post" action="tbl_addfield.php" id="addColumns" name="addColumns" onsubmit="return checkFormElementInRange(this, 'num_fields', '<?php echo str_replace('\'', '\\\'', __('You have to add at least one column.')); ?>', 1)">
    <?php echo PMA_URL_getHiddenInputs($GLOBALS['db'], $GLOBALS['table']); ?>
    <?php if (PMA_Util::showIcons('ActionLinksMode')): ?>
        <?php echo PMA_Util::getImage('b_insrow.png', __('Add column')); ?>&nbsp;
    <?php endif; ?>
    <?php $num_fields = '<input type="number" name="num_fields" value="1" onfocus="this.select()" min="1" required />'; ?>
    <?php echo sprintf(__('Add %s column(s)'), $num_fields); ?>
    <input type="hidden" name="field_where" value="after"/>&nbsp;
    <!-- I tried displaying the drop-down inside the label but with Firefox the drop-down was blinking -->
    <select name="after_field" onchange="checkFirst()">
        <option value="first" data-pos = "first">
            <?php echo __('at beginning of table'); ?>
        </option>
        <?php $cols_count = count($columns_list);
         foreach ($columns_list as $one_column_name): ?>
            <?php if (--$cols_count == 0): ?>
                <option value="<?php echo htmlspecialchars($one_column_name); ?>" selected="selected">
            <?php else: ?>
                <option value="<?php echo htmlspecialchars($one_column_name); ?>">
            <?php endif; ?>
            <?php echo sprintf(__('after %s'), htmlspecialchars($one_column_name)); ?>
            </option>
        <?php endforeach; ?>
    </select>
    <input type="submit" value="<?php echo __('Go'); ?>" />
</form>
