<div class="print_ignore" >
    <?php echo PMA_Util::getWithSelected($pmaThemeImage, $text_dir, "fieldsForm"); ?>
    <?php echo PMA_Util::getButtonOrImage(
    'submit_mult', 'mult_submit', 'submit_mult_browse',
    __('Browse'), 'b_browse.png', 'browse'
    ); ?>

    <?php if (! $tbl_is_view && ! $db_is_system_schema): ?>
        <?php echo PMA_Util::getButtonOrImage(
        'submit_mult', 'mult_submit change_columns_anchor ajax',
        'submit_mult_change', __('Change'), 'b_edit.png', 'change'
        ); ?>
        <?php echo PMA_Util::getButtonOrImage(
        'submit_mult', 'mult_submit', 'submit_mult_drop',
        __('Drop'), 'b_drop.png', 'drop'
        ); ?>

        <?php if ('ARCHIVE' != $tbl_storage_engine): ?>
            <?php
                echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_primary',
                    __('Primary'), 'b_primary.png', 'primary'
                );
                echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_unique',
                    __('Unique'), 'b_unique.png', 'unique'
                );
                echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_index',
                    __('Index'), 'b_index.png', 'index'
                );
            ?>

            <?php if (! empty($tbl_storage_engine)
                        && ($tbl_storage_engine == 'MYISAM'
                        || $tbl_storage_engine == 'ARIA'
                        || $tbl_storage_engine == 'MARIA')): ?>
                <?php echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_fulltext',
                    __('Fulltext'), 'b_ftext.png', 'ftext'
                ); ?>
            <?php endif; ?>

            <?php if ($GLOBALS['cfgRelation']['centralcolumnswork']): ?>
                <?php
                echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_central_columns_add',
                    __('Add to central columns'), 'centralColumns_add.png',
                    'add_to_central_columns');
                echo PMA_Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_central_columns_remove',
                    __('Remove from central columns'), 'centralColumns_delete.png',
                    'remove_from_central_columns'); ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
