<div class="print_ignore" >
    <?= PMA\libraries\Util::getWithSelected($pmaThemeImage, $text_dir, "fieldsForm") ?>
    <?= PMA\libraries\Util::getButtonOrImage(
    'submit_mult', 'mult_submit', 'submit_mult_browse',
    __('Browse'), 'b_browse.png', 'browse'
    ) ?>

    <?php if (! $tbl_is_view && ! $db_is_system_schema): ?>
        <?= PMA\libraries\Util::getButtonOrImage(
        'submit_mult', 'mult_submit change_columns_anchor ajax',
        'submit_mult_change', __('Change'), 'b_edit.png', 'change'
        ) ?>
        <?= PMA\libraries\Util::getButtonOrImage(
        'submit_mult', 'mult_submit', 'submit_mult_drop',
        __('Drop'), 'b_drop.png', 'drop'
        ) ?>

        <?php if ('ARCHIVE' != $tbl_storage_engine): ?>
            <?= PMA\libraries\Util::getButtonOrImage(
                'submit_mult', 'mult_submit', 'submit_mult_primary',
                __('Primary'), 'b_primary.png', 'primary'
            ) ?>
            <?= PMA\libraries\Util::getButtonOrImage(
                'submit_mult', 'mult_submit', 'submit_mult_unique',
                __('Unique'), 'b_unique.png', 'unique'
            ) ?>
            <?= PMA\libraries\Util::getButtonOrImage(
                'submit_mult', 'mult_submit', 'submit_mult_index',
                __('Index'), 'b_index.png', 'index'
            ) ?>

            <?php if (! empty($tbl_storage_engine)
                        && ($tbl_storage_engine == 'MYISAM'
                        || $tbl_storage_engine == 'ARIA'
                        || $tbl_storage_engine == 'MARIA')): ?>
                <?= PMA\libraries\Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_fulltext',
                    __('Fulltext'), 'b_ftext.png', 'ftext'
                ) ?>
            <?php endif; ?>

            <?php if ($GLOBALS['cfgRelation']['centralcolumnswork']): ?>
                <?= PMA\libraries\Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_central_columns_add',
                    __('Add to central columns'), 'centralColumns_add.png',
                    'add_to_central_columns'
                ) ?>
                <?= PMA\libraries\Util::getButtonOrImage(
                    'submit_mult', 'mult_submit', 'submit_mult_central_columns_remove',
                    __('Remove from central columns'), 'centralColumns_delete.png',
                    'remove_from_central_columns'
                ) ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
</div>