<div id="partitions">
    <fieldset>
        <legend><?php echo __('Partitions')
            . PMA_Util::showMySQLDocu('partitioning'); ?>
        </legend>
        <table>
            <thead>
                <tr>
                    <th colspan="2">#</th>
                    <th><?php echo __('Name'); ?></th>
                    <th><?php echo __('Rows'); ?></th>
                    <th><?php echo __('Data length'); ?></th>
                    <th><?php echo __('Index length'); ?></th>
                    <th colspan="7"><?php echo __('Action'); ?></th>
                </tr>
            </thead>
            <tbody>
            <?php $odd = true; ?>
            <?php
                $titles = array(
                    'ANALYZE' => PMA_Util::getIcon('b_empty.png', __('Analyze')),
                    'CHECK' => PMA_Util::getIcon('eye.png', __('Check')),
                    'OPTIMIZE' => PMA_Util::getIcon('normalize.png', __('Optimize')),
                    'REBUILD' => PMA_Util::getIcon('b_empty.png', __('Rebuild')),
                    'REPAIR' => PMA_Util::getIcon('b_tblops.png', __('Repair')),
                    'TRUNCATE' => PMA_Util::getIcon('b_empty.png', __('Truncate')),
                    'DROP' => PMA_Util::getIcon('b_drop.png', __('Drop'))
                );
            ?>
            <?php foreach ($partitions as $partition): ?>
                <?php $hasSubPartitions = $partition->hasSubPartitions(); ?>
                <tr class="noclick <?php echo $odd ? 'odd' : 'even'; echo $hasSubPartitions ? ' marked' : '';?>">
                    <?php if ($hasSubPartitions): ?>
                        <td><?php echo $partition->getOrdinal(); ?></td>
                        <td></td>
                    <?php else: ?>
                        <td colspan="2"><?php echo $partition->getOrdinal(); ?></td>
                    <?php endif; ?>
                    <th><?php echo htmlspecialchars($partition->getName()); ?></th>
                    <td class="value"><?php echo $partition->getRows(); ?></td>
                    <td class="value"><?php
                        list($value, $unit) = PMA_Util::formatByteDown(
                            $partition->getDataLength(), 3, 1
                        );
                        ?>
                        <span><?php echo $value; ?></span>
                        <span class="unit"><?php echo $unit; ?></span>
                    </td>
                    <td class="value"><?php
                        list($value, $unit) = PMA_Util::formatByteDown(
                            $partition->getIndexLength(), 3, 1
                        );
                        ?>
                        <span><?php echo $value; ?></span>
                        <span class="unit"><?php echo $unit; ?></span>
                    </td>
                    <?php foreach ($titles as $operation => $title): ?>
                        <td>
                            <a  href="tbl_structure.php<?php echo $url_query; ?>&amp;partition_maintenance=1&amp;sql_query=<?php echo urlencode(
                                    "ALTER TABLE " . PMA_Util::backquote($table) . $operation . " PARTITION " . $partition->getName()
                                ) ?>"
                                id="partition_action_<?php echo $operation; ?>"
                                name="partition_action_<?php echo $operation; ?>"
                                class="ajax"
                            >
                                <?php echo $title; ?>
                            </a>
                        </td>
                    <?php endforeach; ?>

                    <?php if ($hasSubPartitions): ?>
                        <?php foreach ($partition->getSubParitions() as $subParition): ?>
                            <tr class="noclick <?php echo $odd ? 'odd' : 'even' ?>">
                                <td></td>
                                <td><?php echo $subParition->getOrdinal(); ?></td>
                                <td><?php echo htmlspecialchars($subParition->getName()); ?></td>
                                <td class="value"><?php echo $subParition->getRows(); ?></td>
                                <td class="value"><?php
                                    list($value, $unit) = PMA_Util::formatByteDown(
                                        $subParition->getDataLength(), 3, 1
                                    );
                                    ?>
                                    <span><?php echo $value; ?></span>
                                    <span class="unit"><?php echo $unit; ?></span>
                                </td>
                                <td class="value"><?php
                                    list($value, $unit) = PMA_Util::formatByteDown(
                                        $subParition->getIndexLength(), 3, 1
                                    );
                                    ?>
                                    <span><?php echo $value; ?></span>
                                    <span class="unit"><?php echo $unit; ?></span>
                                </td>
                                <td colspan="7"></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tr>
                <?php $odd = ! $odd; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </fieldset>
</div>