<?php
use PMA\libraries\Tracker;
use PMA\libraries\Util;

?>
<a href="#" id="printView"><?= Util::getIcon('b_print.png', __('Print'), true); ?></a>
<?php if (! $tbl_is_view && ! $db_is_system_schema): ?>
    <a href="sql.php<?= $url_query; ?>&amp;session_max_rows=all&amp;sql_query=<?= urlencode(
                'SELECT * FROM ' . Util::backquote($GLOBALS['table'])
                . ' PROCEDURE ANALYSE()'
            ); ?>" style="margin-right: 0;">
            <?= Util::getIcon(
                'b_tblanalyse.png',
                __('Propose table structure'),
                true
            ); ?>
    </a>
    <?= Util::showMySQLDocu('procedure_analyse'); ?>
    <?php if (Tracker::isActive()): ?>
        <a href="tbl_tracking.php<?= $url_query; ?>">
            <?= Util::getIcon('eye.png', __('Track table'), true); ?>
        </a>
    <?php endif; ?>
    <a href="#" id="move_columns_anchor">
        <?= Util::getIcon('b_move.png', __('Move columns'), true); ?>
    </a>
    <a href="normalization.php<?= $url_query; ?>">
        <?= Util::getIcon('normalize.png', __('Improve table structure'), true); ?>
    </a>
<?php endif; ?>
<?php if ($tbl_is_view && ! $db_is_system_schema): ?>
    <?php if (Tracker::isActive()): ?>
        <a href="tbl_tracking.php<?= $url_query; ?>">
            <?= Util::getIcon('eye.png', __('Track view'), true); ?>
        </a>
    <?php endif; ?>
<?php endif; ?>