<form action="tbl_structure.php" method="post">
    <?= PMA\libraries\URL::getHiddenInputs($db, $table); ?>
    <input type="hidden" name="edit_partitioning" value="true" />

    <fieldset>
        <legend><?= __('Edit partitioning'); ?></legend>
        <?= PMA\libraries\Template::get('columns_definitions/partitions')
            ->render(array('partitionDetails' => $partitionDetails)); ?>
    </fieldset>
    <fieldset class="tblFooters">
        <input type="submit" name="save_partitioning" value="<?= __('Save'); ?>">
    </fieldset>
</form>
