<td class="center print_ignore">
    <input type="checkbox" class="checkall" name="selected_fld[]" value="<?= htmlspecialchars($row['Field']); ?>" id="checkbox_row_<?= $rownum; ?>"/>
</td>
<td class="right"><?= $rownum; ?></td>
<th class="nowrap">
    <label for="checkbox_row_<?= $rownum; ?>">
        <?= preg_replace('/[\x00-\x1F]/', '&#x2051;', $displayed_field_name); ?>
    </label>
</th>
<td <?= $type_nowrap; ?>>
    <bdo dir="ltr" lang="en"><?= $extracted_columnspec['displayed_type']; ?>
        <?php if ($GLOBALS['cfgRelation']['commwork'] && $GLOBALS['cfgRelation']['mimework']
                    && $GLOBALS['cfg']['BrowseMIME'] && isset($mime_map[$row['Field']]['mimetype'])): ?>
    <br />MIME: <?= strtolower(str_replace('_', '/', $mime_map[$row['Field']]['mimetype'])); ?>
        <?php endif; ?>
    </bdo>
</td>
<td>
<?php if (! empty($field_charset)): ?>
    <dfn title="<?= PMA_getCollationDescr($field_charset); ?>"><?= $field_charset; ?></dfn>
<?php endif; ?>
</td>
<td class="column_attribute nowrap"><?= $attribute; ?></td>
<td><?= (($row['Null'] == 'YES') ? __('Yes') : __('No')); ?></td>
<td class="nowrap">
    <?php if (isset($row['Default'])): ?>
        <?php if ($extracted_columnspec['type'] == 'bit'): ?>
            <?= PMA\libraries\Util::convertBitDefaultValue($row['Default']); ?>
        <?php else: ?>
            <?= $row['Default']; ?>
        <?php endif;?>
    <?php else: ?>
        <i><?= _pgettext('None for default', 'None'); ?></i>
    <?php endif; ?>
</td>
<?php if ($GLOBALS['cfg']['ShowColumnComments']): ?>
    <td>
        <?= $comments; ?>
    </td>
<?php endif; ?>
<td class="nowrap"><?= mb_strtoupper($row['Extra']); ?></td>
<?php if (! $tbl_is_view && ! $db_is_system_schema): ?>
    <td class="edit center print_ignore">
        <a class="change_column_anchor ajax" href="tbl_structure.php<?= $url_query; ?>&amp;field=<?= $field_encoded; ?>&amp;change_column=1">
            <?= $titles['Change']; ?>
        </a>
    </td>
    <td class="drop center print_ignore">
        <a class="drop_column_anchor ajax" href="sql.php<?= $url_query; ?>&amp;sql_query=<?= urlencode(
                'ALTER TABLE ' . PMA\libraries\Util::backquote($table)
                . ' DROP ' . PMA\libraries\Util::backquote($row['Field']) . ';'); ?>&amp;dropped_column=<?= $field_encoded; ?>&amp;purge=1&amp;message_to_show=<?= urlencode(sprintf(__('Column %s has been dropped.'), htmlspecialchars($row['Field']))) ?>" >
            <?= $titles['Drop']; ?>
        </a>
    </td>
<?php endif; ?>