<thead>
<tr>
    <th class="print_ignore"></th>
    <th>#</th>
    <th><?php use PMA\libraries\Util; ?>

        <?= __('Name'); ?></th>
    <th><?= __('Type'); ?></th>
    <th><?= __('Collation'); ?></th>
    <th><?= __('Attributes'); ?></th>
    <th><?= __('Null'); ?></th>
    <th><?= __('Default'); ?></th>
    <?php if ($GLOBALS['cfg']['ShowColumnComments']): ?>
        <th><?= __('Comments'); ?></th>
    <?php endif; ?>
    <th><?= __('Extra'); ?></th>
     <!-- see tbl_structure.js, function moreOptsMenuResize() -->
     <?php if (! $db_is_system_schema && ! $tbl_is_view): ?>
        <?php
            $colspan = 9;
            if (Util::showIcons('ActionLinksMode')) {
                $colspan--;
            }
        ?>
        <th colspan="<?= $colspan; ?>" class="action print_ignore"><?= __('Action'); ?></th>
    <?php endif; ?>
</tr>
</thead>