<a style="display: none;" href="<?= $url; ?>" class="ajax saveLink">
    <?= \PMA\libraries\Util::getIcon('b_save.png', __('Save')); ?>
</a>
<a style="display: none;" href="#" class="cancelLink">
    <?= \PMA\libraries\Util::getIcon('b_close.png', __('Cancel')); ?>
</a>
<?= \PMA\libraries\Util::getImage(
    'b_help.png',
    __('Documentation'),
    array('style' => 'display:none', 'id' => 'docImage')
) ?>