<a style="display: none;" href="<?php echo $url; ?>" class="ajax saveLink">
    <?php echo \PMA\libraries\Util::getIcon('b_save.png', __('Save')); ?>
</a>
<a style="display: none;" href="#" class="cancelLink">
    <?php echo \PMA\libraries\Util::getIcon('b_close.png', __('Cancel')); ?>
</a>
<?php
echo \PMA\libraries\Util::getImage(
    'b_help.png',
    __('Documentation'),
    array('style' => 'display:none', 'id' => 'docImage')
);
?>