<tr class="var-row <?php echo $rowClass; ?>">
    <td class="var-action">
    <?php if ($editable): ?>
        <a href="#" class="editLink"><?php echo \PMA\libraries\Util::getIcon('b_edit.png', __('Edit')) ?></a>
    <?php else: ?>
        <span title="<?php echo __('This is a read-only variable and can not be edited') ?>" class="read_only_var">
            <?php echo \PMA\libraries\Util::getIcon('bd_edit.png', __('Edit')) ?>
        </span>
    <?php endif; ?>
    </td>
    <td class="var-name">
    <?php if ($docLink != null): ?>
        <span title="<?php echo htmlspecialchars(str_replace('_', ' ', $name)); ?>">
            <?php
                echo \PMA\libraries\Util::showMySQLDocu($docLink[1], false, $docLink[2] . '_' . $docLink[0], true);
                echo htmlspecialchars(str_replace('_', ' ', $name));
                echo '</a>';
            ?>
        </span>
    <?php else: ?>
        <?php echo htmlspecialchars(str_replace('_', ' ', $name)); ?>
    <?php endif; ?>
    </td>
    <td class="var-value value <?php echo ($isSuperuser ? ' editable' : '') ?>">&nbsp;<?php echo htmlspecialchars($value); ?></td>
</tr>