<tr class="var-row <?= $rowClass; ?>">
    <td class="var-action">
    <?php if ($editable): ?>
        <a href="#" data-variable="<?= htmlspecialchars($name) ?>" class="editLink"><?= \PMA\libraries\Util::getIcon('b_edit.png', __('Edit')) ?></a>
    <?php else: ?>
        <span title="<?= __('This is a read-only variable and can not be edited') ?>" class="read_only_var">
            <?= \PMA\libraries\Util::getIcon('bd_edit.png', __('Edit')) ?>
        </span>
    <?php endif; ?>
    </td>
    <td class="var-name">
    <?php if ($docLink != null): ?>
        <span title="<?= htmlspecialchars(str_replace('_', ' ', $name)); ?>">
            <?= \PMA\libraries\Util::showMySQLDocu($docLink[1], false, $docLink[2] . '_' . $docLink[0], true)
                , htmlspecialchars(str_replace('_', ' ', $name))
                , '</a>'
            ?>
        </span>
    <?php else: ?>
        <?= htmlspecialchars(str_replace('_', ' ', $name)); ?>
    <?php endif; ?>
    </td>
    <td class="var-value value <?= ($isSuperuser ? ' editable' : '') ?>">&nbsp;<?= htmlspecialchars($value); ?></td>
</tr>
