<div class="message welcome">
    <span> <?= $welcomeMessage ; ?> </span>
</div>
<?php
    /* @var $bookmark PMA\libraries\Bookmark */
    foreach ($bookmarks as $bookmark): ?>
        <div class="message collapsed bookmark" bookmarkid="<?= $bookmark->getId() ?>"
            targetdb="<?= htmlspecialchars($bookmark->getDatabase()) ?>">
            <?= PMA\libraries\Template::get('console/query_action')
                ->render(
                    array(
                        'parentDivClasses'  => 'action_content',
                        'contentArray'      => [
                            ['action collapse',         __('Collapse')],
                            ['action expand',           __('Expand')],
                            ['action requery',          __('Requery')],
                            ['action edit_bookmark',    __('Edit')],
                            ['action delete_bookmark',  __('Delete')],
                            ['text targetdb',           __('Database'), 'extraSpan' => htmlspecialchars($bookmark->getDatabase())],
                        ]
                    )
                );
            ?>
            <span class="bookmark_label <?= (empty($bookmark->getUser()) ? 'shared' : ''); ?>">
                <?= htmlspecialchars($bookmark->getLabel()) ; ?>
            </span>
            <span class="query">
                <?= htmlspecialchars($bookmark->getQuery()) ; ?>
            </span>
        </div>
<?php endforeach; ?>
