<div class="message welcome">
    <span> <?= $welcomeMessage ; ?> </span>
</div>
<?php
    foreach ($bookmarks as $val): ?>
        <div class="message collapsed bookmark" bookmarkid="<?= $val['id']; ?>"
            targetdb="<?= htmlspecialchars($val['db']) ?>">
            <?= PMA\libraries\Template::get('console/query_action')
                ->render(
                    array(
                        'parentDivClasses'  => 'action_content',
                        'contentArray'      => [
                            ['action collapse',         __('Collapse')],
                            ['action expand',           __('Expand')],
                            ['action requery',          __('Requery')],
                            ['action edit_bookmark',    __('Edit')],
                            ['action delete_bookmark',  __('Delete')],
                            ['text targetdb',           __('Database'), 'extraSpan' => htmlspecialchars($val['db'])],
                        ]
                    )
                );
            ?>
            <span class="bookmark_label <?= ($val['shared'] ? 'shared' : ''); ?>">
                <?= htmlspecialchars($val['label']) ; ?>
            </span>
            <span class="query">
                <?= htmlspecialchars($val['query']) ; ?>
            </span>
        </div>
<?php endforeach; ?>
