<div <?php if ($counter + 1 < $tables_cnt) echo 'style="page-break-after: always;"'; ?>>
    <h1><?php echo htmlspecialchars($table); ?></h1>

    <!-- Displays the comments of the table if MySQL >= 3.23 -->
    <?php if (!empty($show_comment)): ?>
        <?php echo __('Table comments:'); ?>
        <?php echo htmlspecialchars($show_comment); ?>
        <br /><br />
    <?php endif; ?>

    <?php echo PMA_getHtmlForTableStructure(
        $have_rel, $tbl_is_view, $columns, $analyzed_sql,
        $res_rel, $db, $table, $cfgRelation,
        $cfg, $showtable, $cell_align_left
    ); ?>

    <?php if ($multi_tables): ?>
        <hr />
    <?php endif; ?>
</div>
