<?php
/**
 * Display unordered list.
 *
 * $class - optional string - Contains the class name(s) of ul tag
 * $id - optional string - Contains the id of ul tag
 * $item - mandatory string|array - If string, this is the content
 *                                - Else, see templates/list/item.phtml
 * $content - mandatory string - Content to display if $item is empty
 */
?>
<ul<?= !empty($class) ? ' class="' . $class . '"' : null ?>
    <?= !empty($id) ? ' id="' . $id . '"' : null ?>>

    <?php if (!empty($items)): ?>
        <?php foreach ($items as $item): ?>
            <?php if (!is_array($item)): ?>
                <?php $item = array('content' => $item) ?>
            <?php endif; ?>
            <?= PMA\libraries\Template::get('list/item')
                ->render($item)
            ?>
        <?php endforeach; ?>
    <?php elseif (!empty($content)): ?>
        <?= $content ?>
    <?php endif; ?>
</ul>