<?= (! empty($dropdown_question)
    ? htmlspecialchars($dropdown_question) . '&nbsp;&nbsp;'
    : ''); ?><select name="<?= htmlspecialchars($select_name); ?>">
<?php foreach ($choices as $one_value => $one_label): ?>
    <option value="<?= htmlspecialchars($one_value); ?>"
            <?php if ($selected_value == $one_value): ?>
                selected="selected"
            <?php endif; ?>>
        <?= htmlspecialchars($one_label); ?>
    </option>
<?php endforeach; ?>
</select>