<?php $cfgRelation = PMA_getRelationsParam(); ?>
<?php if ($cfgRelation['relwork'] ||
    PMA_Util::isForeignKeySupported($engine)): ?>
    <ul id="topmenu2">
        <?php echo PMA_Util::getHtmlTab(array(
            'icon' => 'b_props',
            'link' => 'tbl_structure.php',
            'text' => __('Table structure'),
            'id' => 'table_strucuture_id'
        ), $url_params); ?>
        <?php echo PMA_Util::getHtmlTab(array(
            'icon' => 'b_relations',
            'link' => 'tbl_relation.php',
            'text' => __('Relation view'),
            'id' => 'table_relation_id'
        ), $url_params); ?>
    </ul>
    <div class="clearfloat"></div>
<?php endif; ?>
