<?php
$attribute_types = $GLOBALS['PMA_Types']->getAttributes();
$cnt_attribute_types = count($attribute_types);

$attribute = '';
if (isset($submit_attribute) && $submit_attribute != false) {
    $attribute = $submit_attribute;
} elseif (isset($columnMeta['Extra'])
    && $columnMeta['Extra'] == 'on update CURRENT_TIMESTAMP') {
    $attribute = 'on update CURRENT_TIMESTAMP';
} elseif (isset($extracted_columnspec['attribute'])) {
    $attribute = $extracted_columnspec['attribute'];
}

$attribute = mb_strtoupper($attribute);
?>
<select style="width: 7em;"
        name="field_attribute[<?= $columnNumber; ?>]"
        id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>">
    <?php for ($j = 0; $j < $cnt_attribute_types; $j++): ?>
        <option value="<?= $attribute_types[$j];?>"
                <?php if ($attribute == mb_strtoupper($attribute_types[$j])): ?>
                    selected="selected"
                <?php endif; ?>>
            <?= $attribute_types[$j]; ?>
        </option>
    <?php endfor; ?>
</select>