<select name="field_key[<?= $columnNumber;?>]"
        id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset);?>"
        data-index="">
    <option value="none_<?= $columnNumber; ?>">---</option>
    <option value="primary_<?= $columnNumber; ?>"
            title="<?= __("Primary"); ?>"
            <?= ((isset($columnMeta['Key']) && $columnMeta['Key'] == 'PRI') ? 'selected="selected"' : '');?>>
        PRIMARY
    </option>
    <option value="unique_<?= $columnNumber; ?>"
            title="<?= __("Unique"); ?>"
        <?= ((isset($columnMeta['Key']) && $columnMeta['Key'] == 'UNI') ? 'selected="selected"' : '');?>>
        UNIQUE
    </option>
    <option value="index_<?= $columnNumber; ?>"
            title="<?= __("Index"); ?>"
        <?= ((isset($columnMeta['Key']) && $columnMeta['Key'] == 'MUL') ? 'selected="selected"' : '');?>>
        INDEX
    </option>
    <option value="fulltext_<?= $columnNumber; ?>"
            title="<?= __("Fulltext"); ?>"
        <?= ((isset($columnMeta['Key']) && $columnMeta['Key'] == 'FULLTEXT') ? 'selected="selected"' : '');?>>
        FULLTEXT
    </option>
    <option value="spatial_<?= $columnNumber; ?>"
            title="<?= __("Spatial"); ?>"
        <?= ((isset($columnMeta['Key']) && $columnMeta['Key'] == 'SPATIAL') ? 'selected="selected"' : '');?>>
        SPATIAL
    </option>
</select>