<input id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
       type="text"
       name="field_comments[<?= $columnNumber; ?>]"
       size="12"
       maxlength="<?= PMA_MYSQL_INT_VERSION >= 50503 ? 1024 : 255; ?>"
       value="<?= (isset($columnMeta['Field']) && is_array($comments_map) && isset($comments_map[$columnMeta['Field']])) ?
                htmlspecialchars($comments_map[$columnMeta['Field']])
                : ''
              ?>"
       class="textfield" />