<input id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
       type="text"
       name="field_length[<?= $columnNumber; ?>]"
       size="<?= $length_values_input_size ?>"
       value="<?= htmlspecialchars($length_to_display); ?>"
       class="textfield" />
<p class="enum_notice" id="enum_notice_<?= $columnNumber ?>_<?= ($ci - $ci_offset); ?>">
    <a href="#" class="open_enum_editor">
        <?= __('Edit ENUM/SET values'); ?>
    </a>
</p>