<?php if ($privs_available) : ?>
    <input name="field_adjust_privileges[<?= $columnNumber; ?>]"
           id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
           checked="checked"
           type="checkbox"
           value="NULL"
           class="allow_null"/>

<?php else : ?>
    <input name="field_adjust_privileges[<?= $columnNumber; ?>]"
           id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
           disabled
           type="checkbox"
           value="NULL"
           class="allow_null"
           title="<?= __('You don\'t have sufficient privileges to perform this '
           . 'operation; Please refer to the documentation for more details');?>"/>
<?php endif; ?>