<select id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
        name="field_move_to[<?= $columnNumber; ?>]"
        size="1"
        width="5em">
    <option value="" selected="selected">&nbsp;</option>
    <option value="-first" <?= ($current_index == 0 ? ' disabled="disabled"' : ''); ?>>
        <?= __('first'); ?>
    </option>
    <?php for ($mi = 0, $cols = count($move_columns); $mi < $cols; $mi++): ?>
        <option value="<?= htmlspecialchars($move_columns[$mi]->name); ?>"
                <?= (($current_index == $mi || $current_index == $mi + 1) ? ' disabled="disabled"' : '');?>>
            <?= sprintf(__('after %s'), PMA\libraries\Util::backquote(htmlspecialchars($move_columns[$mi]->name))); ?>
        </option>
    <?php endfor; ?>
</select>