<table id="table_columns" class="noclick">
    <caption class="tblHeaders">
        <?= __('Structure'); ?>
        <?= PMA\libraries\Util::showMySQLDocu('CREATE_TABLE'); ?>
    </caption>
    <tr>
        <th>
            <?= __('Name'); ?>
        </th>
        <th>
            <?= __('Type') , PMA\libraries\Util::showMySQLDocu('data-types'); ?>
        </th>
        <th>
            <?= __('Length/Values') , PMA\libraries\Util::showHint(
                    __(
                        'If column type is "enum" or "set", please enter the values using'
                        . ' this format: \'a\',\'b\',\'c\'…<br />If you ever need to put'
                        . ' a backslash ("\") or a single quote ("\'") amongst those'
                        . ' values, precede it with a backslash (for example \'\\\\xyz\''
                        . ' or \'a\\\'b\').'
                    )
                ); ?>
        </th>
        <th>
            <?= __('Default') , PMA\libraries\Util::showHint(
                    __(
                        'For default values, please enter just a single value,'
                        . ' without backslash escaping or quotes, using this format: a'
                    )
                ); ?>
        </th>
        <th>
            <?= __('Collation'); ?>
        </th>
        <th>
            <?= __('Attributes'); ?>
        </th>
        <th>
            <?= __('Null'); ?>
        </th>

        <!-- Only for 'Edit' Column(s) -->
        <?php if (isset($_REQUEST['change_column'])
            && ! empty($_REQUEST['change_column'])
        ): ?>
            <th>
                <?= __('Adjust privileges') , PMA\libraries\Util::showDocu('faq', 'faq6-39'); ?>
            </th>
        <?php endif; ?>

        <?php
        // We could remove this 'if' and let the key information be shown and
        // editable. However, for this to work, structure.lib.php must be modified
        // to use the key fields, as tbl_addfield does.
        if (!$is_backup): ?>
            <th>
                <?= __('Index'); ?>
            </th>
        <?php endif; ?>

        <th>
            <abbr title="AUTO_INCREMENT">A_I</abbr>
        </th>
        <th>
            <?= __('Comments'); ?>
        </th>

        <?php if (PMA\libraries\Util::isVirtualColumnsSupported()): ?>
            <th>
                <?= __('Virtuality'); ?>
            </th>
        <?php endif; ?>

        <?php if (isset($fields_meta)): ?>
            <th>
                <?= __('Move column'); ?>
            </th>
        <?php endif; ?>

        <?php if ($mimework && $GLOBALS['cfg']['BrowseMIME']): ?>
            <th>
                <?= __('MIME type'); ?>
            </th>
            <th>
                <a href="transformation_overview.php<?= PMA_URL_getCommon(); ?>#transformation"
                   title="<?= __('List of available transformations and their options'); ?>"
                   target="_blank">
                    <?= __('Browser display transformation'); ?>
                </a>
            </th>
            <th>
                <?= __('Browser display transformation options'); ?>
                <?= PMA\libraries\Util::showHint(
                    __(
                        'Please enter the values for transformation options using this'
                        . ' format: \'a\', 100, b,\'c\'…<br />If you ever need to put'
                        . ' a backslash ("\") or a single quote ("\'") amongst those'
                        . ' values, precede it with a backslash (for example \'\\\\xyz\''
                        . ' or \'a\\\'b\').'
                    )
                ); ?>
            </th>
            <th>
                <a href="transformation_overview.php<?= PMA_URL_getCommon(); ?>#input_transformation"
                   title="<?= __('List of available transformations and their options'); ?>"
                   target="_blank">
                    <?= __('Input transformation'); ?>
                </a>
            </th>
            <th>
                <?= __('Input transformation options'); ?>
                <?= PMA\libraries\Util::showHint(
                    __(
                        'Please enter the values for transformation options using this'
                        . ' format: \'a\', 100, b,\'c\'…<br />If you ever need to put'
                        . ' a backslash ("\") or a single quote ("\'") amongst those'
                        . ' values, precede it with a backslash (for example \'\\\\xyz\''
                        . ' or \'a\\\'b\').'
                    )
                ); ?>
            </th>
        <?php endif; ?>
    </tr>
    <?php $odd_row = true;?>
    <?php foreach($content_cells as $content_row): ?>
        <tr class="<?= ($odd_row ? 'odd' : 'even'); ?>">
            <?php $odd_row = !$odd_row; ?>
            <?= PMA\libraries\Template::get('columns_definitions/column_attributes')
                ->render($content_row); ?>
        </tr>
    <?php endforeach; ?>
</table>
<br />