<select id="field_<?= $columnNumber; ?>_<?= ($ci - $ci_offset); ?>"
        size="1"
        name="field_<?= $type;?>[<?= $columnNumber;?>]">
    <option value="" title="<?= __('None'); ?>"></option>
    <?php if (isset($available_mime[$type]) && is_array($available_mime[$type])): ?>
        <?php foreach ($available_mime[$type] as $mimekey => $transform): ?>
            <?php
                $checked = isset($columnMeta['Field'])
                         && isset($mime_map[$columnMeta['Field']][$type])
                         && preg_match('@' . preg_quote($available_mime[$type . '_file'][$mimekey], '@') . '3?@i',
                                        $mime_map[$columnMeta['Field']][$type]) ? 'selected ' : '';
                $tooltip = PMA_getTransformationDescription(
                    $available_mime[$type . '_file'][$mimekey]
                );
                $parts = explode(":", $transform);
                $name = PMA_getTransformationName(
                    $available_mime[$type . '_file'][$mimekey]
                ) . ' (' . strtolower($parts[0]) . ":" . $parts[1] . ')';
            ?>
            <option value="<?= $available_mime[$type . '_file'][$mimekey]; ?>"
                    <?= $checked; ?>
                    title="<?= htmlspecialchars($tooltip); ?>">
                <?= htmlspecialchars($name); ?>
            </option>
        <?php endforeach; ?>
    <?php endif; ?>
</select>
